// 四期 v4.0：百兽图鉴扩编（14 → 50）。规格照旧：分布地固定、个体随机、杀兽取材是恶业。
// 六类：陆行 lu / 飞行 fei / 水行 shui / 凶兽 xiong / 灵植精怪 ling / 材料兽 cai。
export const BEASTS4 = {
  // ---- 陆行 ----
  beast_luotuoniao: {
    id: 'beast_luotuoniao', name: '漠行鸟', kind: 'lu', tier: 2,
    haunts: ['xm_xiangshi', 'xm_yisi'], intro: '大漠商队养的走禽，一日能行三百里沙路，性子倔得很——它认定的水井，八头骆驼拉不回头。',
    tame: { base: 0.4, flavor: '它低头打量你，像掌柜打量生客——漠行鸟认人，认的是「不带骗的」。' },
    mount: { kind: 'lu', speed: 2, desc: '漠行鸟，沙地上快如疾风——只是它嫌水，海边它闹脾气。' },
    material: { id: 'mat_niaoling', name: '漠行翎', desc: '一枚换羽期的翎毛，沙金色，商队都拿它做「信羽」。' },
  },
  beast_xuehu: {
    id: 'beast_xuehu', name: '踏雪虎', kind: 'lu', tier: 4,
    haunts: ['by_xueyuan', 'by_jianzhong'], intro: '北原雪原的霸主，四爪踏雪无声。剑冢的剑修都不猎它——「它踩着十万剑鸣走路，是这山里的半个主人。」',
    tame: { base: 0.15, flavor: '它与你对视了足足十息——踏雪虎不攻击「不怕它的」。你今天运气好，也可能不够好。' },
    mount: { kind: 'lu', speed: 3, desc: '踏雪虎，雪原上无声无息。骑着它走剑冢，万剑会给你让路——大概。' },
    material: { id: 'mat_hupi', name: '踏雪虎皮', desc: '一张自然蜕换的虎皮，白底墨纹，披上它风雪不侵。' },
  },
  beast_shitun: {
    id: 'beast_shitun', name: '石吞兽', kind: 'lu', tier: 3,
    haunts: ['kx_tianjie', 'kw_kuangshi'], intro: '专啃灵矿的圆滚滚石头兽，壳比矿硬。矿工恨它，铸剑师爱它——它啃过的矿，全是「精了」的。',
    tame: { base: 0.35, flavor: '它把你的鞋当矿啃了一口，又吐了——嫌你的鞋「品位不够」。' },
    mount: { kind: 'lu', speed: 1, desc: '石吞兽，走得慢，但它趴着的地方，准有矿。' },
    material: { id: 'mat_shitun_ke', name: '石吞壳片', desc: '一片蜕下的壳，色如铁精——锻剑时掺一线，剑身多三分「韧」。' },
  },
  beast_malanju: {
    id: 'beast_malanju', name: '稻草马', kind: 'ling', tier: 2,
    haunts: ['bc_yaotian', 'qingxi'], intro: '药田稻草人成精，学着田垄间跑的真马样子扎了四条腿。跑不快，但一夜能「看」完十亩田——它看过的田，虫不生。',
    tame: { base: 0.5, flavor: '它伸草绳编的脖子蹭了蹭你的袖口——稻草马认人，认的是「汗味」。' },
    mount: { kind: 'lu', speed: 1, desc: '稻草马，跑不快，可它走过一夜的田，第二日草叶都挺三分。' },
    material: { id: 'mat_daocao_sheng', name: '灵稻草绳', desc: '一股稻草马褪下的草绳，带着田土气——系在田边，虫不近。' },
  },
  beast_houwang: {
    id: 'beast_houwang', name: '白眉猴王', kind: 'lu', tier: 3,
    haunts: ['ss_shanmen', 'shanlu'], intro: '蜀山云栈上的猴群之王，白眉及肩。他偷过仙丹，也救过迷路的采药人——蜀山弟子都「供」着它，半是忌惮，半是敬意。',
    tame: { base: 0.25, flavor: '它把一枚偷来的野果分你一半——猴王敬「不抢它猴食的」。' },
    mount: { kind: 'lu', speed: 2, desc: '白眉猴王，攀云走栈如履平地。它驮你走险道，你给它剥松子——各取所需。' },
    material: { id: 'mat_houpi_guo', name: '猴儿酒', desc: '一葫芦猴儿酒——猴群藏了多年的野果酿的，你救过幼猴它才肯给。' },
  },
  beast_guniu: {
    id: 'beast_guniu', name: '独角金牛', kind: 'lu', tier: 3,
    haunts: ['kw_jianshan', 'kw_gongfang'], intro: '铸剑山庄养的役兽，额生独角，专把最难锻的精矿顶出炉膛。老铁匠说它前世必是个打铁的——「你看它顶矿的姿势，专业得很。」',
    tame: { base: 0.4, flavor: '它用独角轻轻挑了挑你的掌纹——金牛认「手上有茧的」。' },
    mount: { kind: 'lu', speed: 2, desc: '独角金牛，力大无穷——骑着它运矿下山，省八个壮汉。' },
    material: { id: 'mat_niujiao', name: '金牛独角鞘', desc: '牛角自然蜕下的角质鞘，入炉不熔——剑柄上缠一圈，握十年不裂。' },
  },
  beast_yetu: {
    id: 'beast_yetu', name: '望月玉兔', kind: 'ling', tier: 2,
    haunts: ['bc_yaowangmiao', 'poza'], intro: '药王庙后山的老白兔，逢月圆便坐起来望月，一望一夜。庙祝说它「在跟月里某位算旧账」——什么账，没人敢问。',
    tame: { base: 0.5, flavor: '它凑近嗅了嗅你带药味的袖口，打了个喷嚏——药气太冲，它嫌「呛」，但不讨厌。' },
    mount: { kind: 'lu', speed: 1, desc: '望月玉兔，跳得比你跑得快——骑它是想都别想，但它乐意「引路」。' },
    material: { id: 'mat_turong', name: '月华绒', desc: '一撮月圆夜落在玉兔窝边的绒毛，夜里微微发亮——安神。' },
  },
  beast_tuobei: {
    id: 'beast_tuobei', name: '驮碑龟', kind: 'lu', tier: 3,
    haunts: ['kx_tianjie', 'kx_yuxu'], intro: '昆仑墟里驮断碑的老龟，一只碑驮了上千年。守墟人路过都要拱手——「它驮的不是碑，是记性。」',
    tame: { base: 0.3, flavor: '它缓缓转过头看了你一眼——那一眼里有一千年的耐心。你自觉把腰弯低了一寸。' },
    mount: { kind: 'lu', speed: 1, desc: '驮碑龟，慢到「不急」成了它的一部分——骑着它，你的急性子能治好。' },
    material: { id: 'mat_guijia_wen', name: '龟甲拓片', desc: '一片龟甲自然蜕下的薄层，上面天然带着碑文纹路——拓下来，是一页「没人读过的经」。' },
  },
  beast_yezhu: {
    id: 'beast_yezhu', name: '獠牙野猪王', kind: 'xiong', tier: 3,
    haunts: ['shanlu', 'qingxi', 'by_xueyuan'], intro: '青溪村后山的祸害，獠牙有半尺长，掀翻过三户人家的篱笆。村口的悬赏一直没人领——领过的人都改行了。',
    tame: { base: 0.12, flavor: '它喷着响鼻把你拱倒在地，然后……大摇大摆走了。它不是认主，是「懒得理你」。' },
    material: { id: 'mat_zhuliao', name: '野猪獠牙', desc: '半尺长的獠牙，磨一磨能当匕首——猎户说，这是「山给的刀」。' },
  },
  beast_lanshen: {
    id: 'beast_lanshen', name: '懒瘫貛', kind: 'ling', tier: 1,
    haunts: ['poza', 'qingxi', 'shanlu'], intro: '一种懒到极处的獾，能在同一个洞里睡完一整个冬天。乡人说摸过它的人「沾福气」——其实是沾一身「不想干活」的气。',
    tame: { base: 0.6, flavor: '它睁开半只眼看了看，又睡了——在懒瘫貛的世界里，这就是「接纳」。' },
    mount: { kind: 'lu', speed: 1, desc: '懒瘫貛——好吧，它不驮你，你驮它。但它睡觉的地方，冬暖夏凉。' },
    material: { id: 'mat_huanrong', name: '貛绒', desc: '一撮貛绒，软得不像话——枕着它睡，能睡掉半个烦心事。' },
  },
  // ---- 飞行 ----
  beast_yanya: {
    id: 'beast_yanya', name: '崖燕', kind: 'fei', tier: 1,
    haunts: ['yh_xia', 'cl_dengtaya'], intro: '雁回峡的燕群，翅上有云纹。老船工说燕群绕船三圈是「报平安」——渔家信了一辈子，也灵了一辈子。',
    tame: { base: 0.55, flavor: '一只燕落在你肩头，蹭了蹭——崖燕认「走水路稳当的人」。' },
    mount: { kind: 'fei', speed: 1, desc: '崖燕驮不动人，但它认得的风路，船老大们愿意拿一坛酒来换。' },
    material: { id: 'mat_yanyu', name: '崖燕尾羽', desc: '一枚分叉的尾羽——老水手缝在船头，说是「燕识归途」。' },
  },
  beast_fengying: {
    id: 'beast_fengying', name: '风隼', kind: 'fei', tier: 2,
    haunts: ['yh_chemahang', 'tw_guanqiang', 'cl_dengtaya'], intro: '驿路上的隼，跟车马送信送出了名堂——它的爪环上刻着三代信使的名字。',
    tame: { base: 0.4, flavor: '它站在你手臂上掂了掂分量——风隼只落在「手臂稳」的人腕上。' },
    mount: { kind: 'fei', speed: 2, desc: '风隼，短程传信快过快马——它认了你的腕，认得你的路。' },
    material: { id: 'mat_sunling', name: '隼翎', desc: '一支隼翎，插在信封上，江湖人见了绕道——「这信，是隼护送的。」' },
  },
  beast_yegou: {
    id: 'beast_yegou', name: '夜枭鹰', kind: 'fei', tier: 3,
    haunts: ['guishi', 'hq_heishi', 'yizhuang'], intro: '鬼市上空的常客，专在子时盘旋。有人说是鬼市的「眼线」，有人说是守夜的神——鬼市掌柜的只说：「它叫它的，我们开我们的。」',
    tame: { base: 0.2, flavor: '它在黑暗里与你对视，瞳孔缩成一线——夜枭鹰认「夜里不心虚的」。' },
    mount: { kind: 'fei', speed: 2, desc: '夜枭鹰，夜行无声。骑着它走夜路，鬼市三更的门都会「恰好」开着。' },
    material: { id: 'mat_yingyu_hei', name: '枭羽', desc: '一枚黑透的枭羽——插在帽檐上，夜行的路都「让」你三分。' },
  },
  beast_huowu: {
    id: 'beast_huowu', name: '火舞雀', kind: 'fei', tier: 3,
    haunts: ['kw_jianlu', 'ss_shanmen'], intro: '栖在剑炉烟囱顶上的赤色小鸟，炉火越旺它舞得越欢。铸剑师说它是「炉火的魂」——它离去的炉子，出的剑都「闷」。',
    tame: { base: 0.3, flavor: '它落在你的锤柄上跳了三跳——火舞雀认「炉火纯青的手」。' },
    mount: { kind: 'fei', speed: 2, desc: '火舞雀，飞起来像一把撒出去的火星子——它栖在谁的剑鞘上，谁的剑就「带三分暖」。' },
    material: { id: 'mat_huoling_yu', name: '火翎', desc: '一枚尾翎入火不焚——锻剑时垫在剑坯下，「火气」匀三分。' },
  },
  beast_banjiu: {
    id: 'beast_banjiu', name: '斑鸠仙', kind: 'ling', tier: 1,
    haunts: ['shanbi_dong', 'shanlu'], intro: '山神庙檐下的老斑鸠，羽毛灰扑扑，胆子却比谁都大——它敢站庙里神像的头顶。乡人都说它是「山神的信鸟」。',
    tame: { base: 0.65, flavor: '它在你头顶落了落，又飞走了——斑鸠仙的「赐福」，就是肯在你头上站一站。' },
    mount: { kind: 'fei', speed: 1, desc: '斑鸠仙不驮人，但它落在谁家檐下，谁家当年顺顺当当。' },
    material: { id: 'mat_banjiu_yu', name: '灰羽', desc: '一枚普通的灰羽毛——山神庙开过光的，乡下人说能「挡小灾」。' },
  },

  // ---- 水行 ----
  beast_yinyu: {
    id: 'beast_yinyu', name: '银梭鱼', kind: 'shui', tier: 1,
    haunts: ['lj_huze', 'cl_aogang', 'qd_yucun'], intro: '漕河与近海的银色小鱼，游起来像一把撒出去的梭子。渔家的吉兆——「银梭过船头，网网不落空。」',
    tame: { base: 0.6, flavor: '它在你脚边的水里绕了个圈——银梭鱼认「水上吃饭的」。' },
    mount: { kind: 'shui', speed: 1, desc: '银梭鱼引路——它往哪儿窜，哪儿的水路今天「顺」。' },
    material: { id: 'mat_yinyu_lin', name: '银鳞', desc: '几片银鳞，渔家拿它们缀在网角——「鱼见了，当是自己人。」' },
  },
  beast_moyu: {
    id: 'beast_moyu', name: '墨斗鱼妖', kind: 'shui', tier: 2,
    haunts: ['nh_bujidao', 'nh_haishi'], intro: '南海商路上的老住户，高兴了给船队「让路」，不高兴了……一片黑水，什么罗盘都失灵。商盟给它立过「供例」。',
    tame: { base: 0.35, flavor: '它喷了你一脸墨——别恼，墨斗鱼妖只对「它觉得将来还得见的」人喷墨，算「留了记号」。' },
    mount: { kind: 'shui', speed: 2, desc: '墨斗鱼妖，水下最快的一笔「墨」——它驮你穿黑水，罗盘都省了。' },
    material: { id: 'mat_moyu_zhi', name: '妖墨', desc: '一小瓶妖墨——写在纸上千年不褪，鬼市大掌柜见了眼睛发亮。' },
  },
  beast_luochaoyu: {
    id: 'beast_luochaoyu', name: '落潮翁', kind: 'shui', tier: 3,
    haunts: ['cl_chuanwu', 'qd_yihui'], intro: '潮退时留在滩涂上的老鱼精，须长及地，会打瞌睡。修船的匠人拿它当「活水位」——它睡在哪儿，哪儿明天不涨潮。',
    tame: { base: 0.3, flavor: '它掀开一只眼皮看了看潮线，又睡了——落潮翁的「认」，就是没游走。' },
    mount: { kind: 'shui', speed: 2, desc: '落潮翁，游得不快，可它走过的地方，潮水「懂规矩」。' },
    material: { id: 'mat_chaoxu', name: '潮须', desc: '一截自然断落的老鱼须，浸了百年潮气——系在船底，浪「客气」三分。' },
  },
  beast_beihe: {
    id: 'beast_beihe', name: '负壳虾将', kind: 'shui', tier: 2,
    haunts: ['lg_jiaoluo', 'lg_huilang'], intro: '龙宫遗族的虾兵后代，背着半片碎甲，在遗迹里站岗站了上百年。它对每个来客行「礼」——行完礼，照旧拦路。',
    tame: { base: 0.4, flavor: '它把长枪一横，让出半步——虾将让路，是龙宫「认下了你」。' },
    mount: { kind: 'shui', speed: 1, desc: '负壳虾将，驮不了人，但它的「通行礼」比什么腰牌都好使。' },
    material: { id: 'mat_xiake', name: '虾将碎甲', desc: '半片旧甲，纹路是龙宫军制——锻进盾里，「挡」字当先。' },
  },
  beast_qiuqiu: {
    id: 'beast_qiuqiu', name: '秋秋螺', kind: 'ling', tier: 1,
    haunts: ['qd_yucun', 'cl_aogang'], intro: '滩涂上会「回答」的小螺——你喊一声，它应一声。渔家娃娃都拿它练胆：对着大海喊话，它替海回你。',
    tame: { base: 0.7, flavor: '你刚蹲下，它就把壳门开了——秋秋螺对谁都是一视同仁的「热情」。' },
    mount: { kind: 'shui', speed: 1, desc: '秋秋螺不驮人——但把它举到耳边，能听见三里外的浪声。' },
    material: { id: 'mat_qiuqiu_ke', name: '应声螺壳', desc: '一只老螺壳——贴耳一听，里面存着「上一任主人喊过的话」。' },
  },
  beast_haiyue: {
    id: 'beast_haiyue', name: '海月贝', kind: 'cai', tier: 2,
    haunts: ['qd_yihui', 'nh_haishi'], intro: '壳薄如月的海贝，月圆夜浮上水面「晒月亮」。采贝人说不准捞——「捞上来的月，就不亮了。」',
    tame: { base: 0.5, flavor: '它把壳微微张开一线——海月贝的「认」，是肯给你看一眼里面的珍珠光。' },
    material: { id: 'mat_yuebei', name: '月贝片', desc: '一片自然褪落的壳，薄得透光——嵌在窗上，月光进屋都「柔」三分。' },
  },
  beast_xuanwu_zai: {
    id: 'beast_xuanwu_zai', name: '玄武崽', kind: 'shui', tier: 5,
    haunts: ['yy_zhongceng'], intro: '妖渊中层传说的「黑水之壳」——甲如山岳，浮起时渊水让道。渔场的供桌朝的就是它。见过它的人，往后的日子都「稳」。',
    tame: { base: 0.05, flavor: '它缓缓睁开眼——那一眼里没有敌意，只有「时间」。你的心在这时间里静了下来。' },
    mount: { kind: 'shui', speed: 3, desc: '玄武崽，甲上能站十个人——黑水行舟，它就是「地」。' },
    material: { id: 'mat_xuanwu_lin', name: '玄武甲鳞', desc: '一枚巴掌大的甲鳞，重如山岳的「一角」——镇宅镇船，都镇得住。' },
  },
  beast_denglongshui: {
    id: 'beast_denglongshui', name: '引路灯水母', kind: 'ling', tier: 1,
    haunts: ['lg_huilang', 'yy_shangceng'], intro: '深海里提着「灯」的透明水母——灯亮的方向水路最稳。龙宫旧脉的水手都跟着它走：「跟着灯，别跟着心。」',
    tame: { base: 0.55, flavor: '它把灯凑近你半寸——灯水母的「认」，是肯给你「照一程」。' },
    material: { id: 'mat_dengzhu', name: '灯烛芯', desc: '它褪下的一缕灯芯——入水不熄，水手缝在舱顶，「夜航的胆」。' },
  },
  // ---- 凶兽 ----
  beast_nian: {
    id: 'beast_nian', name: '岁末年兽', kind: 'xiong', tier: 4,
    haunts: ['yizhuang', 'hq_luanzangling'], intro: '只在岁末最后一夜出没的凶兽，怕红、怕响、怕「人气旺」。乱葬岗的老人们年年除夕守一夜火堆——「火旺，它就不来。」',
    tame: { base: 0.08, flavor: '它在火光外与你对峙了半夜——最后退了半步。年兽的「认」，就是肯退这半步。' },
    material: { id: 'mat_nianjiao', name: '年兽角屑', desc: '一角兽角碎屑，火烧不化——乡人拿它做门神像的「骨」。' },
  },
  beast_shiwei: {
    id: 'beast_shiwei', name: '食雾蜃', kind: 'xiong', tier: 4,
    haunts: ['cl_dengtaya', 'qd_yihui'], intro: '吞雾吐楼的巨蜃，海市蜃楼就是它的「梦」。灯塔守夜人说：它做梦时别吵——「吵醒一场梦，海要翻三天。」',
    tame: { base: 0.1, flavor: '它的梦里出现了一座你的「楼」——食雾蜃的「认」，是把你也织进梦里。' },
    material: { id: 'mat_shen_ou', name: '蜃珠', desc: '一颗蜃吐的珠，里面锁着一小片「别人的梦」——夜里贴耳听，有海声。' },
  },
  beast_tiebeilang: {
    id: 'beast_tiebeilang', name: '铁背狼王', kind: 'xiong', tier: 3,
    haunts: ['tw_guanqiang', 'by_xueyuan'], intro: '边关外的狼群之王，背甲是历代猎人的箭攒出来的「铁」。铁瓦关的老卒都认得它——「它守着关外那片山，跟咱们守关一个道理。」',
    tame: { base: 0.12, flavor: '它收了呲开的牙，退后一步又站定——铁背狼王的「认」，是与你「划界而守」。' },
    material: { id: 'mat_langbei_tie', name: '狼背铁箭镞', desc: '从它背甲上替它取下的十几枚旧箭镞——老兵说：「这上头的债，算我们的，不算它的。」' },
  },
  beast_gudiao: {
    id: 'beast_gudiao', name: '噬蛊雕', kind: 'xiong', tier: 3,
    haunts: ['nj_zhanglin', 'nj_bazhai'], intro: '瘴林上空的巨雕，专食毒蛊——南疆人敬它如神。峒老说：它一次食蛊千枚，「瘴林这么多年没成死地，是它替山「滤」着毒。」',
    tame: { base: 0.15, flavor: '它落在你的肩头，爪子收得很轻——噬蛊雕只停「身上无毒念的」肩头。' },
    mount: { kind: 'fei', speed: 3, desc: '噬蛊雕，翼展两丈——骑着它过瘴林，蛊瘴自行退散。' },
    material: { id: 'mat_diao_yu', name: '滤毒翎', desc: '一支雕翎——挂在门前，蚊蛊不入户。南疆人的老讲究。' },
  },
  beast_shanxiao_lu: {
    id: 'beast_shanxiao_lu', name: '踮脚山魈', kind: 'xiong', tier: 2,
    haunts: ['shanlu', 'ss_shanmen'], intro: '爱学人走路的山魈，走路踮着脚尖，学人作揖，学人皱眉。你冲它挥手，它冲你挥手——挥着挥着，它就站到你身后了。',
    tame: { base: 0.3, flavor: '它学你抱拳——学得歪歪扭扭，可它是认真的。山魈认「肯陪它玩仪式的」。' },
    material: { id: 'mat_xiao_mao', name: '山魈毛', desc: '一撮偷拔来的山魈毛——绣在鞋垫上，走夜路「腿脚利索」。' },
  },
  // ---- 灵植精怪 ----
  beast_lingzhi_weng: {
    id: 'beast_lingzhi_weng', name: '灵芝翁', kind: 'ling', tier: 3,
    haunts: ['bc_yaotian', 'ss_shanmen'], intro: '一支成了精的老灵芝，胡子是菌盖的边。他专在采药人脚下「绊」人——绊倒的必是起了贪念、连幼芝都要挖的。',
    tame: { base: 0.3, flavor: '它摇了摇菌盖上的「胡子」，往你的药篓里挪了挪——灵芝翁的「认」，是肯跟你「下山」。' },
    material: { id: 'mat_lingzhi_xie', name: '灵芝屑', desc: '他身上自然簌落的菌屑——入药治「心浮」，老药农都认。' },
  },
  beast_liushu_qing: {
    id: 'beast_liushu_qing', name: '柳树精·青娘', kind: 'ling', tier: 2,
    haunts: ['qingxi', 'lj_shuimen'], intro: '青溪村口老槐边第三棵柳树的精魂。村人谁家有喜事，她在枝上「笑」——柳叶沙沙的。婚书祭文都去她枝下「过一遍」。',
    tame: { base: 0.4, flavor: '她垂下一缕柳丝，在你腕上绕了半圈——青娘的「认」，是肯「给你系个福」。' },
    material: { id: 'mat_liushao', name: '青娘柳枝', desc: '一截她赠的柳枝——插土即活，护宅。村人说比门神灵。' },
  },
  beast_yushu_tong: {
    id: 'beast_yushu_tong', name: '玉树童子', kind: 'ling', tier: 3,
    haunts: ['kx_yuxu', 'ss_jianzheng'], intro: '昆仑墟断玉里生出的树灵，身形是个孩童，衣袂是玉屑。他守着一口枯井——井里「等一个人」，等了一万年。',
    tame: { base: 0.2, flavor: '他把一枚玉叶按在你掌心——玉树童子的「认」，是信你会替他「接着等」。' },
    material: { id: 'mat_yuye', name: '玉叶', desc: '一枚玉屑凝的叶，永远「半温」——贴身戴着，心境「清」三分。' },
  },
  beast_daomai: {
    id: 'beast_daomai', name: '稻穗精·稔儿', kind: 'ling', tier: 1,
    haunts: ['qingxi', 'bc_yaotian'], intro: '秋收时田里最沉的那株稻成了精，是个总「低着头」的小姑娘。村人秋祭给她留第一把新米——「她低头，是替全村谢天。」',
    tame: { base: 0.55, flavor: '她把一粒新米放进你的掌心——稔儿的「认」，是肯把「今年最好的」给你。' },
    material: { id: 'mat_daosui', name: '双穗稻', desc: '一株双穗的稻种——来年撒进田里，那块田「不荒」。' },
  },
  // ---- 材料兽 ----
  beast_jinchan: {
    id: 'beast_jinchan', name: '吐钱金蟾', kind: 'cai', tier: 2,
    haunts: ['xiaojinku', 'guishi'], intro: '鬼市金库的「编外守库员」，每月吐一枚「库纹金」。大掌柜的给它的俸禄是三只油炸蚕蛹——「比库房钥匙好使。」',
    tame: { base: 0.3, flavor: '它把一枚「库纹金」推到你脚边——金蟾的「认」，是肯与你「对分」。' },
    material: { id: 'mat_kujin', name: '库纹金', desc: '一枚带着鬼市金库纹的赤金——江湖硬通货，比银票好使。' },
  },
  beast_canwang: {
    id: 'beast_canwang', name: '天蚕王', kind: 'cai', tier: 3,
    haunts: ['bc_yaotian', 'ss_shanmen'], intro: '蚕中百年一遇的王，吐的丝「一夜成茧，三日成衣」。药王谷养了它三代——每代蚕王结茧那日，全谷焚香。',
    tame: { base: 0.25, flavor: '它在你指尖吐了一缕丝，绕了一圈——天蚕王的「认」，是给你「量个尺寸」。' },
    material: { id: 'mat_tiancan_si', name: '天蚕丝', desc: '一缕天蚕丝，细过发，韧过铁——软甲的内衬，用它。' },
  },
  beast_yuji_jing: {
    id: 'beast_yuji_jing', name: '雨绩精', kind: 'ling', tier: 2,
    haunts: ['lj_shuimen', 'cl_huozhan'], intro: '雨丝里织布的小精怪，织出的「雨帛」轻若无物。漕帮的船帆角上都缝一片——「雨打不透，风撕不动。」',
    tame: { base: 0.35, flavor: '它借你的袖口「晾」了一匹雨帛——雨绩精的「认」，是肯把活儿「放」你这儿。' },
    material: { id: 'mat_yubo', name: '雨帛', desc: '一角雨织的帛——雨天顶在头上，「雨」认得它，会绕着走。' },
  },
  beast_kuncai: {
    id: 'beast_kuncai', name: '鲲鳞幼鱼', kind: 'shui', tier: 4,
    haunts: ['yy_shangceng', 'qd_yihui'], intro: '传说鲲鹏遗在浅海的幼裔，鳞大如瓦。它自己也不知道自己会长成什么——渔家不捕它：「万一呢。谁家网敢兜『万一』。」',
    tame: { base: 0.12, flavor: '它用瓦大的鳞片替你挡了一阵浪——鲲鳞幼鱼的「认」，是先「护」后「熟」。' },
    mount: { kind: 'shui', speed: 3, desc: '鲲鳞幼鱼——它现在驮你如驮一片叶。养大了……海上人说「养大了再说」。' },
    material: { id: 'mat_kunlin', name: '鲲鳞', desc: '一枚蜕下的巨鳞，海浪一过它就「唱」——挂在船头，浪「报信」。' },
  },
};
