// 二期 v2.0：13 新出身（总 16）。规格见 02-世界蓝图出身表。
// 结构与 fates.js 完全一致，尾部 Object.assign 合入。
export const ORIGINS2 = {
  jiangmen: {
    id: 'jiangmen', name: '将门之后',
    startCity: 'tiewa', startArea: 'tw_guanqiang', startNode: 'tw_guanqiang',
    startMoney: 5,
    intro: '你祖父随大衍开国，你父亲戍在铁瓦关。将门的孩子先学会的不是武，是"规矩"——枪要立直，人要站直。可如今家道中落，你手里只剩半部家传枪谱。',
    fates: [
      {
        id: 'jm_f1', originId: 'jiangmen', age: 16,
        laichu: '父亲战死在关外，灵柩回乡那日，半城老兵出来接。你跪在灵前，把家传枪谱的第一页背给了他听——那是他教你背的最后一课。',
        ruanle: '父亲留在灵柩里的一枚箭簇——取自他心头。大夫说，他中箭后还站了一炷香。',
        gouzi: '关外来了一队生面孔，说是"商队"，可在茶棚里用军中的切口讨水。祖父的老部下如今在关里当戍将——他派人捎话：让你"别出关"。',
        hiddenLine: 'hl_jiangmen_jiancu',
        startCity: 'tiewa', startArea: 'tw_guanqiang', startNode: 'tw_guanqiang',
        variants: ['bian_junying_shitou', 'bian_guanwai_yaoshou', 'bian_shouqian_beiqian'],
        lifeNodes: ['ln_jiangmen_1'],
        startItems: [{ id: 'item_qiangpu', name: '半部家传枪谱', desc: '前半部练气力，后半部没了。父亲说，后半部"要用命去写"。', kind: 'relic' }],
      },
      {
        id: 'jm_f2', originId: 'jiangmen', age: 15,
        laichu: '祖父获罪那年，家产抄没，门客散尽。你随母亲投亲不成，在铁瓦关外安了家。军中旧识偷偷接济，母亲不肯收——她只让你把枪练直。',
        ruanle: '母亲缝的护腕，磨破了三副她也不许你换新的。"将门的孩子，手上的茧就是脸面。"',
        gouzi: '戍将私下寻你：关中要选亲兵，凭你家学，一测就能进。可他压低了声音说——"进去之后，有些事你要替我看着。"',
        hiddenLine: 'hl_jiangmen_qinbing',
        startCity: 'tiewa', startArea: 'tw_guanqiang', startNode: 'tw_guanqiang',
        variants: ['bian_junying_shitou', 'bian_guanwai_yaoshou', 'bian_shouqian_beiqian'],
        lifeNodes: ['ln_jiangmen_1'],
        startItems: [],
      },
    ],
  },

  shuxiang: {
    id: 'shuxiang', name: '书香门第',
    startCity: 'tianqi', startArea: 'tq_fangshi', startNode: 'dongshi',
    startMoney: 6,
    intro: '你家三代读书，堂上挂着"晴耕雨读"。你七岁开蒙，十三岁能作策论，先生说你该去考。可你偷读的，从来是书肆里那些"闲书"——山海志异，剑侠传闻。',
    fates: [
      {
        id: 'sx_f1', originId: 'shuxiang', age: 16,
        laichu: '父亲是国子监的博士，一生没做过官。他说读书人骨头要硬，可他咳血的时候，还是让你去东市当了母亲的嫁妆镯。',
        ruanle: '父亲批注过的那本《山海经》——他的字密密麻麻，比原文还多。有些批注你越读越觉得，不像是在说书，像是在说"真事"。',
        gouzi: '书肆掌柜私下给你看了一页残卷，说"你父亲二十年前抄过一部一样的"。抄本如今在谁手里，掌柜不肯说。',
        hiddenLine: 'hl_shuxiang_canjuan',
        startCity: 'tianqi', startArea: 'tq_fangshi', startNode: 'dongshi',
        variants: ['bian_keju_zhaoxie', 'bian_shuyuan_lun', 'bian_huolang'],
        lifeNodes: ['ln_shuxiang_1'],
        startItems: [{ id: 'item_shanhaijing', name: '父亲的《山海经》批注本', desc: '纸页发脆。其中一页折了角，批注只有四个字："此兽尚在。"', kind: 'relic' }],
      },
      {
        id: 'sx_f2', originId: 'shuxiang', age: 17,
        laichu: '家道败落，你替书肆抄书糊口。抄得多了，你发现同一部书，各家的本子不一样——有的多了半章，有的少了一句。你开始留底稿。',
        ruanle: '你自己抄书的润笔攒下的三十文钱——第一笔"自己挣的钱"，你一直没舍得花。',
        gouzi: '一位落第老举人来书肆借宿，看了你抄的书，忽然说："你识字的路子不对——你不是学出来的，是悟出来的。想不想学点书里没有的？"',
        hiddenLine: 'hl_shuxiang_laojuren',
        startCity: 'tianqi', startArea: 'tq_fangshi', startNode: 'dongshi',
        variants: ['bian_keju_zhaoxie', 'bian_shuyuan_lun', 'bian_huolang'],
        lifeNodes: ['ln_shuxiang_1'],
        startItems: [],
      },
    ],
  },

  shijing: {
    id: 'shijing', name: '市井无赖',
    startCity: 'tianqi', startArea: 'tq_fangshi', startNode: 'sipailou',
    startMoney: 3,
    intro: '你生在四牌楼，长在四牌楼。赌坊的规矩你懂，衙役的棒子你躲得开，谁家的狗见了你都夹尾巴。人说你是个无赖——可四牌楼的老人知道，你这无赖，赊的账都记着还。',
    fates: [
      {
        id: 'sj_f1', originId: 'shijing', age: 17,
        laichu: '爹是脚夫，抬货摔死了；娘给人浆洗，熬瞎了眼。你从十岁起在坊市"讨生活"——讨来的，一半进了娘的药罐。',
        ruanle: '娘的眼睛。郎中说要一百两，你数过四牌楼所有的赌档——加起来也凑不出十两。',
        gouzi: '堂口管事看上你的"机灵"，让你跑一趟腿，说跑成了，你娘的眼"有人管"。他没说拿什么管。',
        hiddenLine: 'hl_shijing_tangkou',
        startCity: 'tianqi', startArea: 'tq_fangshi', startNode: 'sipailou',
        variants: ['bian_du_fuyi', 'bian_yashu_zhua', 'bian_gaibang_shouming'],
        lifeNodes: ['ln_shijing_1'],
        startItems: [{ id: 'item_cipen', name: '娘的瓷盆', desc: '浆洗衣裳用的粗瓷盆，边上磕了三个口。你说等翻了身，给她换个金的——娘笑你贫嘴。', kind: 'relic' }],
      },
      {
        id: 'sj_f2', originId: 'shijing', age: 16,
        laichu: '你是赌坊后巷捡回来的孩子，谁也不知道爹娘是谁。坊市养大你，你也养着坊市——哪家有难处，你手脚快，夜里"顺"点东西出来，天亮前再"还"回去一半。',
        ruanle: '赌坊看场子的跛脚老周。他挨打的时候总把你挡在身后，去年冬天他没熬过去。',
        gouzi: '鬼市的守门人夜里叫住你："小子，你这双眼睛，天生该吃地下这碗饭。有个买卖，敢不敢接？"',
        hiddenLine: 'hl_shijing_guishi',
        startCity: 'tianqi', startArea: 'tq_fangshi', startNode: 'sipailou',
        variants: ['bian_du_fuyi', 'bian_yashu_zhua', 'bian_gaibang_shouming'],
        lifeNodes: ['ln_shijing_1'],
        startItems: [],
      },
    ],
  },

  haidao: {
    id: 'haidao', name: '海岛渔家',
    startCity: 'canglan', startArea: 'cl_aogang', startNode: 'cl_yushi',
    startMoney: 4,
    intro: '你生在船上，学走路先学的描浪。阿公说，海是活的，它心情好给你鱼，心情不好收人——你要敬它，也要认得它的每一张脸。',
    fates: [
      {
        id: 'hd_f1', originId: 'haidao', age: 16,
        laichu: '阿爹的船三年前没在一场黑风里。船上七个人，回来两个。阿公不许你出海，你就夜里偷偷跟商队学摇橹——海的事，阿公拦不住你。',
        ruanle: '阿爹留下的海图，角上烧掉了一块。烧掉的那块画的是什么，阿公喝了酒就骂，骂完就哭。',
        gouzi: '货栈的番商出高价收"会潜水的"——说东海底下有处古迹，能闭气三炷香的，赏钱够阿公后半辈子。',
        hiddenLine: 'hl_haidao_haitu',
        startCity: 'canglan', startArea: 'cl_aogang', startNode: 'cl_yushi',
        variants: ['bian_heifeng_yusheng', 'bian_jiaorenlei', 'bian_dubiao_yuye'],
        lifeNodes: ['ln_haidao_1'],
        startItems: [{ id: 'item_haitu', name: '阿爹的残海图', desc: '图上标着一处"旋水"，旁边是阿爹的字：勿入。——可旋水的位置，恰好在图上烧掉的那块旁边。', kind: 'relic' }],
      },
      {
        id: 'hd_f2', originId: 'haidao', age: 15,
        laichu: '你是涨潮时被浪送上沙滩的婴孩，捡你的人家把你当自家养。你的眼睛是浅碧色的，渔村人说你是"海的孩子"。',
        ruanle: '养母的咳嗽。一到冬季她夜里咳得整条船都在晃——你出海的日子里，最怕听见风声像她咳嗽。',
        gouzi: '海神庙的老庙祝近来总看你，看得你发毛。昨夜他在你门上贴了道符，天亮你去找他，他说："不是防你，是替你挡。有些东西认得你。"',
        hiddenLine: 'hl_haidao_haizi',
        startCity: 'canglan', startArea: 'cl_aogang', startNode: 'cl_yushi',
        variants: ['bian_heifeng_yusheng', 'bian_jiaorenlei', 'bian_dubiao_yuye'],
        lifeNodes: ['ln_haidao_1'],
        startItems: [],
      },
    ],
  },

  yaopu: {
    id: 'yaopu', name: '药铺学徒',
    startCity: 'baicao', startArea: 'bc_yaogu', startNode: 'bc_yaoshi',
    startMoney: 3,
    intro: '你在百草坞的药铺当学徒，五年了。抓药的手稳，认药的嘴严——师父说，药铺的孩子两条命：一条自己的，一条记在药方上的。',
    fates: [
      {
        id: 'yp_f1', originId: 'yaopu', age: 15,
        laichu: '师父捡你回来那年你七岁，发着高热躺在药王庙门口。他救了你的命，也救了你的"鼻子"——你对药香天生敏，三十分编的药，你闻一口就知道谁错了。',
        ruanle: '师父的咳疾。他给人治病一辈子，自己的病拖到如今——他说药材太贵，"留着给用得上的人"。',
        gouzi: '试毒巷的老毒师夜里来铺子，扔下一株你从没见过的草："认得出，教你认一百种。认不出——拿你师父的命抵。"',
        hiddenLine: 'hl_yaopu_dushi',
        startCity: 'baicao', startArea: 'bc_yaogu', startNode: 'bc_yaoshi',
        variants: ['bian_yaotian_qie', 'bian_wenyi_jiuzhen', 'bian_yaoling'],
        lifeNodes: ['ln_yaopu_1'],
        startItems: [{ id: 'item_yaochu', name: '师父的药杵', desc: '枣木的，磨得溜光。师父说杵声匀，药性才匀。', kind: 'relic' }],
      },
      {
        id: 'yp_f2', originId: 'yaopu', age: 16,
        laichu: '你娘是药铺的药婆，难产走的。爹去南方贩药，一去五年没信。你在这铺子里从杂役做到学徒——药铺的孩子，闻着药香长大，命里带着苦味。',
        ruanle: '爹留下的南方药录，最后一页夹着半张南海商路的船票——是他没来得及用的那张。',
        gouzi: '药田近日夜里有响动，守田的说看见"小人儿"偷跑。掌柜要报官，可你知道那不是贼——那是《本草拾遗》里写的"地精"，是药材成了精。',
        hiddenLine: 'hl_yaopu_renshen',
        startCity: 'baicao', startArea: 'bc_yaogu', startNode: 'bc_yaoshi',
        variants: ['bian_yaotian_qie', 'bian_wenyi_jiuzhen', 'bian_yaoling'],
        lifeNodes: ['ln_yaopu_1'],
        startItems: [],
      },
    ],
  },

  qigai: {
    id: 'qigai', name: '乞丐',
    startCity: 'tianqi', startArea: 'tq_fangshi', startNode: 'chengmen_dashi',
    startMoney: 1,
    intro: '天启城十万口人，你要饭的地方有讲究：东市要早饭，四牌楼要午饭，城隍庙要晚饭——这是丐帮的规矩。规矩之内你是乞儿，规矩之外，你什么消息都知道。',
    fates: [
      {
        id: 'qg_f1', originId: 'qigai', age: 15,
        laichu: '你在城隍庙的供桌底下长大，管庙的老庙祝瞎了眼，心不瞎。他教你认字，用的是香灰——他说："要饭不丢人，不识字才丢人。"',
        ruanle: '老庙祝。他冬天越来越熬不住了，你讨来的热粥总是先端给他。',
        gouzi: '丐帮的老龙头传下话来：城里来了几拨"生面孔"，各要饭的都得"帮着看"。看的不是脸——是鞋。',
        hiddenLine: 'hl_qigai_xie',
        startCity: 'tianqi', startArea: 'tq_fangshi', startNode: 'chengmen_dashi',
        variants: ['bian_gaibang_shouming', 'bian_chenghuang_yejian', 'bian_yashu_zhua'],
        lifeNodes: ['ln_qigai_1'],
        startItems: [{ id: 'item_xianghui_zi', name: '香灰写的字帖', desc: '老庙祝用香灰在地上写的字，你用炭描在破布上收着。第一课教的是你自己的名字。', kind: 'relic' }],
      },
      {
        id: 'qg_f2', originId: 'qigai', age: 17,
        laichu: '饥荒那年全家只剩下你。你跟着乞儿队伍从北走到天启，一路学会了看脸色、听脚步、抢在别人前头占桥洞。你比谁都清楚：活着这件事，是门手艺。',
        ruanle: '小豆子——半路上捡的哑巴小孩，去年冬天没能熬过去。你答应过他，"翻身后买糖人"。',
        gouzi: '你昨夜在桥洞听见两个黑衣人低声说话，说了个名字——那名字前几日城门口的海捕文书上，赏银三百两。',
        hiddenLine: 'hl_qigai_haibu',
        startCity: 'tianqi', startArea: 'tq_fangshi', startNode: 'chengmen_dashi',
        variants: ['bian_gaibang_shouming', 'bian_chenghuang_yejian', 'bian_yashu_zhua'],
        lifeNodes: ['ln_qigai_1'],
        startItems: [],
      },
    ],
  },

  liehu: {
    id: 'liehu', name: '猎户之子',
    startCity: 'xiangye', startArea: 'xiangye_wild', startNode: 'shanlu',
    startMoney: 3,
    intro: '你爹是猎户，你爷爷也是。弓开满月的年纪你比谁都早，兽踪、套索、下风口的讲究，是你家的"家学"。山里人说：猎户打猎是谋生，可有些东西，打了是要遭报应的。',
    fates: [
      {
        id: 'lh_f1', originId: 'liehu', age: 16,
        laichu: '爹在去年冬天猎一头白鹿时失踪了。白鹿没打回来，爹也没回来。你沿着血迹找到崖边，血迹断了——崖下是云。',
        ruanle: '爹的猎刀，刀柄上刻着你们家的规矩："打三留一。"留的那条命，是给山的。',
        gouzi: '近日山里的兽集体往北迁，老人们说这是"山要变"。猎王寨放话：谁能查清兽群为何而迁，寨里传他"御兽的法"。',
        hiddenLine: 'hl_liehu_bailu',
        startCity: 'xiangye', startArea: 'xiangye_wild', startNode: 'shanlu',
        variants: ['bian_shouqian_beiqian', 'bian_liewang_yaoqing', 'bian_houshan'],
        lifeNodes: ['ln_liehu_1'],
        startItems: [{ id: 'item_hun Dao'.replace(' ', ''), name: '爹的猎刀', desc: '刀柄刻着"打三留一"。刀刃有七个豁口——七个大猎季，七头大兽。', kind: 'weapon' }],
      },
      {
        id: 'lh_f2', originId: 'liehu', age: 17,
        laichu: '娘改嫁去了猎王寨的人家，你随了过去。寨里孩子笑你"拖油瓶"，你不吭声——你把笑你的人的暗哨位置全记下来了。',
        ruanle: '你自己的哑弓——上个月猎熊时被熊掌拍裂了，你用鱼胶缠了七层，还能开。',
        gouzi: '猎王寨的老寨主病重，寨里明面上平静，暗地里三房在争"传艺"。有人找上你：替他盯一个人，报酬是"进内寨学艺"。',
        hiddenLine: 'hl_liehu_neizhai',
        startCity: 'xiangye', startArea: 'xiangye_wild', startNode: 'shanlu',
        variants: ['bian_shouqian_beiqian', 'bian_liewang_yaoqing', 'bian_houshan'],
        lifeNodes: ['ln_liehu_1'],
        startItems: [],
      },
    ],
  },

  biaoshi: {
    id: 'biaoshi', name: '镖师之后',
    startCity: 'yanhui', startArea: 'yh_cheng', startNode: 'yh_biaoju',
    startMoney: 5,
    intro: '平安号走镖三十年没失过手，直到你爹走的那一单。镖丢了，人回来了，可"平安"二字在他脸上再没出现过。他把趟子手的活儿塞给你："从最底下干起。"',
    fates: [
      {
        id: 'bs_f1', originId: 'biaoshi', age: 16,
        laichu: '爹从走镖的头把交椅退成了看仓库的，酒越喝越多。他不说那一单的事，你也不问——可你翻过他锁着的旧账，那一单的货单上，货主的名字被水渍晕开了。',
        ruanle: '爹的腰伤。阴雨天他整宿睡不着，你夜里听见他翻身，就在心里把"查清那一单"再说一遍。',
        gouzi: '总镖头把你叫去："后生，有单小镖，不挣钱——但你爹当年没走完的那条线。敢不敢接？"',
        hiddenLine: 'hl_biaoshi_danyi',
        startCity: 'yanhui', startArea: 'yh_cheng', startNode: 'yh_biaoju',
        variants: ['bian_dubiao_yuye', 'bian_tangzi_lianbiao', 'bian_du_fuyi'],
        lifeNodes: ['ln_biaoshi_1'],
        startItems: [{ id: 'item_biaodai', name: '爹的镖旗穗子', desc: '平安号镖旗上的红穗子，那一单之后被爹扯下来收着。他说"旗在镖在"，可他不敢再挂。', kind: 'relic' }],
      },
      {
        id: 'bs_f2', originId: 'biaoshi', age: 15,
        laichu: '你是镖师遗孤，娘改嫁后你在平安号的马棚长大。趟子手们教你喊镖——"合吾——"一嗓子喊出去，你觉得自己天生就该在这条道上。',
        ruanle: '老镖师们凑钱给你打的短刀。刀是你自己选的样式——"轻，快，能藏袖子里。"',
        gouzi: '漕帮的人和号里管事私下碰头，你在柴堆后听见了半句："……那条道上的货，往后平安号不碰，谁碰谁死。"',
        hiddenLine: 'hl_biaoshi_caodao',
        startCity: 'yanhui', startArea: 'yh_cheng', startNode: 'yh_biaoju',
        variants: ['bian_dubiao_yuye', 'bian_tangzi_lianbiao', 'bian_du_fuyi'],
        lifeNodes: ['ln_biaoshi_1'],
        startItems: [],
      },
    ],
  },

  zuinu: {
    id: 'zuinu', name: '罪奴',
    startCity: 'tianqi', startArea: 'tq_huangcheng', startNode: 'gongmen',
    startMoney: 0,
    intro: '全家获罪那年你八岁，没入官奴营。十年了，你学会了低头、闭嘴、把恨咽下去。可你的手比谁都稳——抄书、缝补、磨墨、递刀。奴籍在身，命不是自己的；可眼睛是。',
    fates: [
      {
        id: 'zn_f1', originId: 'zuinu', age: 18,
        laichu: '你在官奴营抄了十年书——营里缺个识字的。你爹是获罪前的刑部主事，你抄的公文里，有当年你家的案卷。你一个字一个字地抄，一个字一个字地记。',
        ruanle: '你娘临别塞给你的一枚顶针——和"那个抄没的府"一样，是你家仅剩的东西。',
        gouzi: '一位老太监把你调出奴营去"整理档案"。他说："你爹当年没写完的那份东西，还压在架子上。你想不想看？"',
        hiddenLine: 'hl_zuinu_anjuan',
        startCity: 'tianqi', startArea: 'tq_huangcheng', startNode: 'gongmen',
        variants: ['bian_nuying_guxi', 'bian_jiuming_yinhen', 'bian_yashu_zhua'],
        lifeNodes: ['ln_zuinu_1'],
        startItems: [{ id: 'item_dingzhen_nu', name: '娘的顶针', desc: '铜的，磨得发亮。和天下所有的顶针都一样，可这是你家的。', kind: 'relic' }],
      },
      {
        id: 'zn_f2', originId: 'zuinu', age: 17,
        laichu: '旧主家败落前，你是府里的"影子"——替少爷挨打，替小姐传信。府没之后，你在奴营遇见了当年对你最狠的管家：他也成了奴。你救了他——不是心善，是想让他活着看。',
        ruanle: '小姐。她被没入教坊那天，隔着车帘看了你一眼。那一眼是"活下去"的意思，你认。',
        gouzi: '夜里有人翻进奴营，往你草席下塞了一样东西：半块玉佩——和小姐被抄走的那块，纹路对得上。塞东西的人，已经不见了。',
        hiddenLine: 'hl_zuinu_yupei',
        startCity: 'tianqi', startArea: 'tq_huangcheng', startNode: 'gongmen',
        variants: ['bian_nuying_guxi', 'bian_jiuming_yinhen', 'bian_yashu_zhua'],
        lifeNodes: ['ln_zuinu_1'],
        startItems: [],
      },
    ],
  },

  youfang: {
    id: 'youfang', name: '游方道人弟子',
    startCity: 'xiangye', startArea: 'xiangye_wild', startNode: 'poza',
    startMoney: 2,
    intro: '师父是个云游道人，收你做徒弟那年他自称一百二十岁——看着像五十。三年里他带你走了十一个州，教你观气、认路、看天。今年开春，他在破山神庙里坐化了，临终一句话："剩下路，你自己走。"',
    fates: [
      {
        id: 'yf_f1', originId: 'youfang', age: 16,
        laichu: '师父坐化前三天，把他的"度牒"给了你。度牒是真的，"游方道人"四个字磨得快没了。他说："庙里的道是官家的道，路边的道，才是活的。"',
        ruanle: '师父的桃木杖，杖头缠着九圈红线。他说一圈是一个"该还的愿"——九个愿是哪九个，他只来得及说三个。',
        gouzi: '你替师父守灵七日，第八日清早，灵前的香灰上多了一行脚印——从庙门进来，到蒲团前，消失。脚印很小，像孩子，也像别的什么。',
        hiddenLine: 'hl_youfang_jiaoyin',
        startCity: 'xiangye', startArea: 'xiangye_wild', startNode: 'poza',
        variants: ['bian_duodie_zhenren', 'bian_guanzhong_shengqi', 'bian_yaoling'],
        lifeNodes: ['ln_youfang_1'],
        startItems: [{ id: 'item_taomuzhang', name: '师父的桃木杖', desc: '九圈红线。师父说杖是拿来扶的，不是拿来打的——"打人用理。"', kind: 'weapon' }],
      },
      {
        id: 'yf_f2', originId: 'youfang', age: 17,
        laichu: '你是师父半路"顺"来的——他说是你父母自愿，你疑心不是。三年师徒，他教得严，可你夜里咳，他会整宿守着。',
        ruanle: '你自己都不知道的"来历"。师父临终说过半句："你的血——"后头的，他没能说完。',
        gouzi: '师父坐化后，陆续有人来找"他的东西"。找的人一拨比一拨客气，也一拨比一拨危险——师父到底留下了什么？',
        hiddenLine: 'hl_youfang_yuanlai',
        startCity: 'xiangye', startArea: 'xiangye_wild', startNode: 'poza',
        variants: ['bian_duodie_zhenren', 'bian_guanzhong_shengqi', 'bian_yaoling'],
        lifeNodes: ['ln_youfang_1'],
        startItems: [],
      },
    ],
  },

  shijia: {
    id: 'shijia', name: '世家旁支',
    startCity: 'linjiang', startArea: 'lj_cheng', startNode: 'lj_shuyuan',
    startMoney: 8,
    intro: '河东柳氏是百年世家，你是旁支的旁支——族谱上你的名字小得要眯眼找。族人宴席坐末座，家学进旁听席。可你读书比嫡系好，练武比嫡系狠——旁支的孩子，要么认命，要么挣命。',
    fates: [
      {
        id: 'sja_f1', originId: 'shijia', age: 16,
        laichu: '你爹一生替嫡系管账，分毫不差，临老却背了个"账目不清"的锅，气病在床。你知道是谁做的手脚——那个人如今管着族里半数生意。',
        ruanle: '你爹的算盘。档珠磨得发亮。他昏迷前握着你的手说："账是清的。人不清。"',
        gouzi: '族学开考，头名可入族谱正卷、领家学传承。你报了名——管事的笑："旁支也配？"他把你的考卷抽走了。',
        hiddenLine: 'hl_shijia_zhangmu',
        startCity: 'linjiang', startArea: 'lj_cheng', startNode: 'lj_shuyuan',
        variants: ['bian_zuxue_doukao', 'bian_liujia_lianwu', 'bian_keju_zhaoxie'],
        lifeNodes: ['ln_shijia_1'],
        startItems: [{ id: 'item_suanpan', name: '爹的算盘', desc: '档珠发亮。爹说算盘响的时候，天下没有算不清的账——除了人心。', kind: 'relic' }],
      },
      {
        id: 'sja_f2', originId: 'shijia', age: 17,
        laichu: '你是庶出，生母是家养的绣娘。嫡母容你读书，是拿你当嫡系子弟的"磨刀石"——每次考比，你都要"输得恰到好处"。',
        ruanle: '生母绣了一半的百子图。她走时手还捏着针。你说等你出息了，替她绣完——针脚你不敢动，怕手生。',
        gouzi: '临江书院的山长看了你的文章，说"此子当出族"。他递来一份荐书——去天启的官学。族里会放你走吗？',
        hiddenLine: 'hl_shijia_shanzhang',
        startCity: 'linjiang', startArea: 'lj_cheng', startNode: 'lj_shuyuan',
        variants: ['bian_zuxue_doukao', 'bian_liujia_lianwu', 'bian_keju_zhaoxie'],
        lifeNodes: ['ln_shijia_1'],
        startItems: [],
      },
    ],
  },

  yaozu: {
    id: 'yaozu', name: '妖族遗孤',
    startCity: 'huangquan', startArea: 'tq_dixia', startNode: 'hq_yaorenfang',
    startMoney: 3,
    intro: '你能听见别人听不见的声音：地下的水，梁上的风，还有人心深处那点"真话"。娘说这是"血脉"，要藏好。娘走后，藏血脉这件事，成了你一个人的功课。',
    fates: [
      {
        id: 'yz_f1', originId: 'yaozu', age: 16,
        laichu: '娘是白狐，化形在黄泉集替人"听讼"过活。她走得急，留下的话只有一句："别信化的形，要认真的心。"你如今替妖人坊看铺子，活的、化形的、半化的，你都接。',
        ruanle: '娘留下的那缕白毛，用红绳系着。她说血统能护你三次——用了几次，你不知道，也数不清。',
        gouzi: '昨夜有个"人"来坊里寻你，进门就变回原形——是东荒来的白狐，娘的旧识。他说："东荒那边，你娘留下的东西该去取了。可这条路上的猎妖人，也该到齐了。"',
        hiddenLine: 'hl_yaozu_donghuang',
        startCity: 'huangquan', startArea: 'tq_dixia', startNode: 'hq_yaorenfang',
        variants: ['bian_lieyaoren_zhui', 'bian_huaxing_lukou', 'bian_chenghuang_yejian'],
        lifeNodes: ['ln_yaozu_1'],
        startItems: [{ id: 'item_baimao', name: '娘的白毛', desc: '红绳系着的一缕白毛，莹莹地亮。娘说血统能护你——三次。', kind: 'relic' }],
      },
      {
        id: 'yz_f2', originId: 'yaozu', age: 15,
        laichu: '你不知道自己是什么。耳朵尖，眼睛在暗处会亮，闻得出"怕"的味道。你在人间混着，白天装人，夜里数星星——星星里有一颗，总在你失眠的夜里特别亮。',
        ruanle: '养大你的卖艺老汉。他不知你是"什么"，可他捡到你那天说的是："有口气的，都养。"',
        gouzi: '老汉新收的学徒看你的眼神不对——他袖子里有罗盘，罗盘的针，总指着你。',
        hiddenLine: 'hl_yaozu_luopan',
        startCity: 'huangquan', startArea: 'tq_dixia', startNode: 'hq_yaorenfang',
        variants: ['bian_lieyaoren_zhui', 'bian_huaxing_lukou', 'bian_chenghuang_yejian'],
        lifeNodes: ['ln_yaozu_1'],
        startItems: [],
      },
    ],
  },

  geji: {
    id: 'geji', name: '将军府歌姬',
    startCity: 'tianqi', startArea: 'tq_huangcheng', startNode: 'neishi',
    startMoney: 6,
    intro: '你是将军府养的歌姬，签的乐籍。你唱的曲子将军爱听，将军的心事你就都知道了——有些知道了要装不知道，有些知道了，能救命。',
    fates: [
      {
        id: 'gj_f1', originId: 'geji', age: 16,
        laichu: '你娘也是歌姬，唱到四十岁嗓子哑了，被"放出府"，实际是扔出去的。她临走教你最后一支曲子："这支曲子不能在府里唱——记住了，什么时候都不能。"',
        ruanle: '你娘。你不知道她在哪，只知道府里的管事每年往城外送一次米——送米的骡车，你偷偷跟过一次，跟丢了。',
        gouzi: '昨夜你唱错了半句——是故意的。你听见帘子后头有人放下茶盏，轻轻笑了一声。那笑声，你不是第一次听见。',
        hiddenLine: 'hl_geji_quzi',
        startCity: 'tianqi', startArea: 'tq_huangcheng', startNode: 'neishi',
        variants: ['bian_jiangjun_mimi', 'bian_yueji_chuji', 'bian_shuyuan_lun'],
        lifeNodes: ['ln_geji_1'],
        startItems: [{ id: 'item_pipa', name: '娘的旧琵琶', desc: '弦断了两根，声音反而更哑更沉。娘说哑嗓子唱歌，"是把话往骨头里说"。', kind: 'relic' }],
      },
      {
        id: 'gj_f2', originId: 'geji', age: 17,
        laichu: '乐籍的册子上你是"没来路的孩子"，教曲的嬷嬷说是荒年捡的。你的嗓子是百年不遇的"云遮月"，府里拿你当宝贝，也拿你当"耳朵"——宴上的宾客说什么，你都得"唱"出来。',
        ruanle: '和你一起进府的小丫头，如今在灶房做工。她笨，学不会曲子，可全府只有她会在你挨罚后，偷偷塞半个热饼。',
        gouzi: '兵部的一位大人酒后失言，说了句"北边要出事"。满堂宾客都醉了，只有你在唱——只有你听见了。',
        hiddenLine: 'hl_geji_beibian',
        startCity: 'tianqi', startArea: 'tq_huangcheng', startNode: 'neishi',
        variants: ['bian_jiangjun_mimi', 'bian_yueji_chuji', 'bian_shuyuan_lun'],
        lifeNodes: ['ln_geji_1'],
        startItems: [],
      },
    ],
  },
};

// ---------- 开局变故（13 出身专属启蒙线，各 2 条，与全局池合用） ----------
export const VARIANTS2 = {
  bian_junying_shitou: {
    id: 'bian_junying_shitou', title: '入营试枪',
    text: '戍将在校场设了"试枪台"，关外流民子弟都能试。轮到你，你把家传枪的路数走了一遍——收枪时台下没人喝彩，只有几个老兵互相看了一眼。当晚，营里来了人："明日卯时，帐前听点。"',
    effect: { kind: 'shitou', ledger: { type: '记', text: '校场试枪，入老兵法眼' }, trait: { gang: 2 }, gongfa: { id: 'gf_jiajun_qiang', name: '家传枪法（残）', desc: '将门家学的前半部。招不多，式式都是战场搏命的路子。', level: 1, realm: 'wudao' } },
  },
  bian_guanwai_yaoshou: {
    id: 'bian_guanwai_yaoshou', title: '关外妖兽夜袭',
    text: '夜里关墙外传来兽吼，守卒说是"狼"，可狼不撞墙。你跟着老兵上了墙头，火把底下看见的东西让所有人闭了嘴——那不是狼。它退回黑暗前，朝城头"看"了一眼，眼睛是竖的。',
    effect: { kind: 'yaoshou', ledger: null, trait: { meng: 1 }, gongfa: null },
  },
  bian_keju_zhaoxie: {
    id: 'bian_keju_zhaoxie', title: '科场代笔',
    text: '一位考生塞给你十两银子，让你替他写一篇策论。你写了——写得比他自己的前程还用心。放榜那日他中了，你站在人群里看报喜的队伍过去，忽然明白了一件事：这世上的文章，和这世上的道理，是两回事。',
    effect: { kind: 'daibi', ledger: { type: '记', text: '科场代笔，看破文章与道理两途' }, trait: { mou: 1 }, gongfa: null },
  },
  bian_shuyuan_lun: {
    id: 'bian_shuyuan_lun', title: '书院论道',
    text: '书院的月讲上，一位游学士子和山长论"格物"。他说：格物不是读书，是把东西拆开来看。满座学子哄笑，你却听见自己心跳漏了一拍——你想起父亲批注《山海经》时说的话："这书里的兽，要一只一只去看。"',
    effect: { kind: 'lundao', ledger: null, trait: { wu: 2 }, gongfa: { id: 'gf_shuxin_wen', name: '文心诀（散传）', desc: '游学士子留的养气法，说"文气也是气"。练起来慢，可胜在心正。', level: 1, realm: 'lianqi' } },
  },
  bian_du_fuyi: {
    id: 'bian_du_fuyi', title: '赌坊逼迫',
    text: '你替娘赊的药钱，被药铺掌柜转手"抵"进了赌坊——他说这也是没办法。赌坊的人堵着你："十天，二十两。你娘的眼睛，还是你自己的手指，选一样。"',
    effect: { kind: 'duzhai', ledger: { type: '债', text: '欠赌坊二十两，限十日' }, trait: { yin: 2 }, gongfa: null },
  },
  bian_yashu_zhua: {
    id: 'bian_yashu_zhua', title: '衙役抓人',
    text: '街坊的哑巴张被抓了——说他"偷了官盐"。满街没人吭声，只有你知道那晚他在帮你搬你娘的药。衙役问："有人保他吗？"满街的人都在看你。',
    effect: { kind: 'zhuaren', ledger: { type: '恩', text: '为哑巴张作保，坊里记你一回' }, trait: { xia: 2 }, gongfa: null },
  },
  bian_heifeng_yusheng: {
    id: 'bian_heifeng_yusheng', title: '黑风海难余生',
    text: '你偷偷跟了商队的船出海，半路撞上黑风。船碎的时候你抱住了一块舱板，在海里漂了一夜——你听见了不该听见的声音：海底很深的地方，有"东西"在呼吸。天亮你被渔船捞起，从此你怕海，又更想海。',
    effect: { kind: 'haisheng', ledger: null, trait: { jue: 2 }, gongfa: { id: 'gf_biqi_shu', name: '闭气术（散传）', desc: '那夜你在水里自己"悟"出来的换气法子——人的肺在水里能撑多久，全看心稳不稳。', level: 1, realm: 'lianqi' } },
  },
  bian_jiaorenlei: {
    id: 'bian_jiaorenlei', title: '鲛人泪',
    text: '退潮后你在滩涂上捡到一个昏迷的"人"——她的眼睛是海的深蓝。你把她藏进自家船舱养了三日。她走时在水边回头，落了一滴泪，泪珠落在你手心，是温的，凉下去之后，你整夜梦见发光的宫殿。',
    effect: { kind: 'jiaoren', ledger: { type: '恩', text: '救过一位鲛人' }, trait: { fu: 2 }, gongfa: null },
  },
  bian_yaotian_qie: {
    id: 'bian_yaotian_qie', title: '药田失窃',
    text: '药田夜里遭了贼，丢的是三株"九节兰"——师父半年的心血。掌柜要报官，师父却拦住了："贼只偷了兰草，没动别的。官府抓不住这号贼。"夜里你守田，三更时分，真的看见了一个"小人儿"。',
    effect: { kind: 'yaotian', ledger: null, trait: { chi: 1 }, gongfa: null },
  },
  bian_wenyi_jiuzhen: {
    id: 'bian_wenyi_jiuzhen', title: '瘟疫义诊',
    text: '邻村闹时疫，师父带你去义诊。七日里你见惯了生死，手上的药勺没抖过一次。回程路上师父说了平生最重的一句话："手稳不是天赋，是见过了之后还敢伸手。你今日，算出师了一半。"',
    effect: { kind: 'yizhen', ledger: { type: '功德', text: '时疫义诊七日，活人无算' }, trait: { ren: 2 }, gongfa: { id: 'gf_yuli_jue', name: '御力诀（师传）', desc: '师父的看家养气法——"医者练气不为杀，为的是手稳、心定、命长，多救几个人。"', level: 1, realm: 'lianqi' } },
  },
  bian_gaibang_shouming: {
    id: 'bian_gaibang_shouming', title: '丐帮受名',
    text: '老龙头在城隍庙后头单独见了你，扔给你一根打狗棒——不是叫你打狗，是"开口棒"：城门内外十三个桥洞、八条暗巷，谁家添丁谁家死人，你都得"知道"。受棒那日他只说了一句："嘴要严。命才长。"',
    effect: { kind: 'shouming', ledger: { type: '记', text: '受丐帮开口棒，入消息一门' }, trait: { min: 2 }, gongfa: null },
  },
  bian_chenghuang_yejian: {
    id: 'bian_chenghuang_yejian', title: '城隍庙夜见',
    text: '中元夜你在庙里守夜，三更时供桌上的长明灯自己亮了——不是火，是"光"。光里有个影子朝你作了个揖，你鬼使神差也回了礼。第二天老庙祝摸着你的头顶说："它认下你了。这庙里，以后你也是半个主人。"',
    effect: { kind: 'yejian', ledger: null, trait: { yin: 2 }, gongfa: { id: 'gf_anxi_gong', name: '安息功（庙传）', desc: '老庙祝口传的安神法。练它的人夜里不做噩梦——也少见"不干净的东西"。', level: 1, realm: 'lianqi' } },
  },
  bian_shouqian_beiqian: {
    id: 'bian_shouqian_beiqian', title: '兽群北迁',
    text: '你蹲了三个山头，终于看清了兽群北迁的真相：不是猎杀，是"避"——它们在避开什么。北边的地平线上，有你从没见过的云。你把这事记在心里，没跟任何人说。',
    effect: { kind: 'shouqian', ledger: null, trait: { cha: 2 }, gongfa: null },
  },
  bian_liewang_yaoqing: {
    id: 'bian_liewang_yaoqing', title: '猎王寨相邀',
    text: '猎王寨的巡山队"偶遇"了你，队首的老猎师看了你的弓、你的靴、你手上的茧，只说了一句："后生，寨里一季一次的「开山猎」，缺人手。凭本事来。"',
    effect: { kind: 'xiangyao', ledger: { type: '记', text: '受猎王寨开山猎之邀' }, trait: { meng: 1 }, gongfa: { id: 'gf_shexin_gong', name: '射心功（猎传）', desc: '猎户的养气法："箭出之前，先射自己的心。心动，箭就歪。"', level: 1, realm: 'wudao' } },
  },
  bian_dubiao_yuye: {
    id: 'bian_dubiao_yuye', title: '独镖遇雨',
    text: '你头一回独自走短镖，半路遇上山洪冲断了桥。镖货是十坛酒，救人还是救镖——你把镖旗插在桥头上，背着一个被困的老货郎蹚过了水。回来镖头骂你"没规矩"，骂完塞给你一贯钱："这钱不是赏，是"规矩之外、人心之内"的份例。"',
    effect: { kind: 'dubiao', ledger: { type: '功德', text: '断桥救老货郎，弃镖保人' }, trait: { xia: 2 }, gongfa: null },
  },
  bian_tangzi_lianbiao: {
    id: 'bian_tangzi_lianbiao', title: '堂子练镖',
    text: '平安号的演武堂夜里不熄灯。你睡在马棚，就夜里起来练——第一月练"稳"，第二月练"快"，第三月，老镖头站在你身后看了半夜，丢下一句话："手上有三分才了，就敢托六分的镖。小子，你胆子比手快。"',
    effect: { kind: 'lianbiao', ledger: null, trait: { gang: 1 }, gongfa: { id: 'gf_hubiao_dao', name: '护镖刀（号传）', desc: '平安号趟子手的看家刀法。不求杀人，求的是"货不动，人不倒"。', level: 1, realm: 'wudao' } },
  },
  bian_nuying_guxi: {
    id: 'bian_nuying_guxi', title: '奴营故隙',
    text: '奴营里你抄书的名声传开了，管营的差役让你替他写家书——写了一封，他老婆哭着回了信。他红着眼圈塞给你半块饼："……你写的字，像人话。"从那以后，营里的差役们写家书都找你。你用一封信一封信，把自己抄出了"能走动"的境地。',
    effect: { kind: 'guxi', ledger: null, trait: { ren: 1 }, gongfa: null },
  },
  bian_jiuming_yinhen: {
    id: 'bian_jiuming_yinhen', title: '旧命印痕',
    text: '一个老奴临死前抓着你的手，往你掌心按了一样东西——一小片烧焦的绢。他说："当年案子里……还有一份没烧完的。"你还没来得及问，他手就凉了。绢上的字迹，你认得——是你爹的。',
    effect: { kind: 'yinhen', ledger: { type: '记', text: '老奴遗绢，案有未烬之页' }, trait: { yin: 2 }, gongfa: null },
  },
  bian_duodie_zhenren: {
    id: 'bian_duodie_zhenren', title: '夺嫡真人',
    text: '师父坐化的第七日，来了个骑驴的老者，在你师父灵前坐了一夜。走时他叫住你："你师父当年欠我半局棋。他走了，账在你身上——十日后来城南听雨桥。你要是聪明，就别来。"',
    effect: { kind: 'duodie', ledger: { type: '记', text: '受"听雨桥半局棋"之约' }, trait: { wu: 2 }, gongfa: null },
  },
  bian_guanzhong_shengqi: {
    id: 'bian_guanzhong_shengqi', title: '观中生气',
    text: '你守灵那几夜，山神庙破了个洞的屋顶漏下月光，正照在你师父坐化的蒲团上。第三夜，你看见月光里浮起一缕白气——像师父还坐在那儿打坐。你慌了，可白气散前，你分明听见一声笑——是师父的笑。',
    effect: { kind: 'shengqi', ledger: null, trait: { jue: 1 }, gongfa: { id: 'gf_guanqi_shu', name: '观气术（师传）', desc: '师父的看家本事："气在人前，理在气先。看得见气，就骗不了你。"', level: 1, realm: 'lianqi' } },
  },
  bian_zuxue_doukao: {
    id: 'bian_zuxue_doukao', title: '族学夺考',
    text: '你把抽走考卷的管事告到了族老面前——没告赢，可满堂族老都记住了你的名字。散会后，一位平日不理族务的老族长拦住你："后生，明日起，家学后院的书楼，你可以进。名分没有，书，管够。"',
    effect: { kind: 'duokao', ledger: { type: '记', text: '族学夺考，虽败犹进书楼' }, trait: { gang: 2 }, gongfa: null },
  },
  bian_liujia_lianwu: {
    id: 'bian_liujia_lianwu', title: '柳家练武',
    text: '族里武堂不收旁支，你就爬墙头看。看了一个月，教习忽然点名让你下场——原来他早看见了。"柳家的枪，认的是骨相，不是族谱。"他扔给你一杆枪，"接得住，你就姓柳。接不住，滚回去读书。"',
    effect: { kind: 'lianwu', ledger: null, trait: { meng: 1 }, gongfa: { id: 'gf_liujia_qiang', name: '柳家枪（族传）', desc: '河东柳氏的看家枪法。讲究"一寸长一寸强"，更讲究"枪出如族规——不容情"。', level: 1, realm: 'wudao' } },
  },
  bian_lieyaoren_zhui: {
    id: 'bian_lieyaoren_zhui', title: '猎妖人追猎',
    text: '一个带罗盘的猎妖人进了黄泉集，罗盘的针直指妖人坊。坊里半化的孩子们吓哭了，你站到铺子门口——罗盘的针，一半指你，一半指你身后。你带他绕了三条巷子，最后在死巷里转身："要收，先收我。"',
    effect: { kind: 'zhui', ledger: { type: '记', text: '独面猎妖人，护坊中半妖' }, trait: { xia: 2 }, gongfa: null },
  },
  bian_huaxing_lukou: {
    id: 'bian_huaxing_lukou', title: '化形路口',
    text: '你娘留下的血气到了"化形"的关口：夜里发热，骨头缝里像有东西要顶出来。妖人坊的老婆婆看了你一眼，只说："化形的路有两条——全化成人，忘掉来路；守住原形，人就当你是妖。你自己挑。"',
    effect: { kind: 'huaxing', ledger: null, trait: { jue: 2 }, gongfa: { id: 'gf_yaoli_qimeng', name: '妖力启蒙', desc: '血脉自带的吐纳法，走的是妖的路子——快，野，人间功法压不住的那种活。', level: 1, realm: 'lianqi' } },
  },
  bian_jiangjun_mimi: {
    id: 'bian_jiangjun_mimi', title: '将军密事',
    text: '你在屏风后唱曲，听见将军和一个夜客低语了三个字——"那件事"。夜客走后，将军单独传你："今晚你什么都没听见。唱完这曲，赏你出府一日——去哪儿？"他看着你，等你接话。你唱完了曲，说："民女哪儿也不去，府里有人等米下锅。"将军笑了，赏了双倍的月钱——从那天起，他知道你是"懂事的"。',
    effect: { kind: 'mimi', ledger: { type: '记', text: '闻将军密事，以"懂事"自保' }, trait: { mou: 2 }, gongfa: null },
  },
  bian_yueji_chuji: {
    id: 'bian_yueji_chuji', title: '乐籍除籍',
    text: '教曲的嬷嬷拿着一份文书来寻你：有人替你赎了乐籍——无名无姓，钱是现银。嬷嬷说："拿了它，你自由了。可府里的门，也就关了。"你捏着文书，想起娘——她等了一辈子的，就是这张纸。',
    effect: { kind: 'chuji', ledger: { type: '恩', text: '受无名客赎身之恩，乐籍得脱' }, trait: { fu: 2 }, gongfa: null },
  },
};

// ---------- 隐秘线 ----------
export const HIDDEN_LINES2 = {
  hl_jiangmen_jiancu: { id: 'hl_jiangmen_jiancu', title: '箭簇之仇', hint: '父亲的死不是"战死"两个字能说完的。关外那队用切口讨水的"商队"，和那个箭簇，是同一件事。', hook: 'ev_jiancu_zhui' },
  hl_jiangmen_qinbing: { id: 'hl_jiangmen_qinbing', title: '亲兵眼线', hint: '戍将让你"替他看着"的东西，比一支亲兵的操练重得多。', hook: 'ev_qinbing_kan' },
  hl_shuxiang_canjuan: { id: 'hl_shuxiang_canjuan', title: '父亲的抄本', hint: '父亲二十年前抄过一部残卷。抄本在哪，谁在找它——书肆掌柜知道一半。', hook: 'ev_canjuan_xun' },
  hl_shuxiang_laojuren: { id: 'hl_shuxiang_laojuren', title: '落第举人', hint: '老举人要教的"书里没有的东西"，可能是学问，也可能是别的什么——他的眼睛不像读书人的眼睛。', hook: 'ev_laojuren_jiao' },
  hl_shijing_tangkou: { id: 'hl_shijing_tangkou', title: '堂口的人情', hint: '管事说娘的眼"有人管"。天底下没有白给的人情，尤其是地下的。', hook: 'ev_tangkou_baochou' },
  hl_shijing_guishi: { id: 'hl_shijing_guishi', title: '鬼市买卖', hint: '守门人说的"买卖"不简单——他的眼睛在看你的时候，一直在看别处。', hook: 'ev_guishi_maimai' },
  hl_haidao_haitu: { id: 'hl_haidao_haitu', title: '残图旋水', hint: '烧掉的那块海图，和"旋水"的位置对得上。阿公知道他儿子当年看见了什么。', hook: 'ev_xuanshui_mi' },
  hl_haidao_haizi: { id: 'hl_haidao_haizi', title: '海的孩子', hint: '老庙祝贴的符是"替你挡"——挡的东西认得你，说明你也认得它。你的血里，有海的东西。', hook: 'ev_haizi_xue' },
  hl_yaopu_dushi: { id: 'hl_yaopu_dushi', title: '毒师的百草', hint: '老毒师的"一百种草"是一张入门票——进了他的门，出来就难了。', hook: 'ev_dushi_baicao' },
  hl_yaopu_renshen: { id: 'hl_yaopu_renshen', title: '药田地精', hint: '偷九节兰的"小人儿"不是贼。地精护参，参通地气——药田底下有东西。', hook: 'ev_dijing_canyuan' },
  hl_qigai_xie: { id: 'hl_qigai_xie', title: '看鞋', hint: '老龙头让全城乞儿"看鞋"。鞋底的花纹能认人——这是丐帮最老的"账"。', hook: 'ev_kanxie_jizhang' },
  hl_qigai_haibu: { id: 'hl_qigai_haibu', title: '海捕之名', hint: '三百两赏格的那个人，你知道他在哪。报官，还是不报——这名字烫手。', hook: 'ev_haibu_ming' },
  hl_liehu_bailu: { id: 'hl_liehu_bailu', title: '白鹿引路', hint: '爹猎白鹿没回来。老人们说白鹿是"山的信使"——它引你爹去了哪，只有山知道。', hook: 'ev_bailu_yin' },
  hl_liehu_neizhai: { id: 'hl_liehu_neizhai', title: '内寨暗哨', hint: '替三房"盯人"的眼睛，迟早也要被别人盯上。', hook: 'ev_neizhai_anshao' },
  hl_biaoshi_danyi: { id: 'hl_biaoshi_danyi', title: '未竟之镖', hint: '爹没走完的那条线，货单上被水晕开的名字——走一遍，就都清楚了。', hook: 'ev_weijing_biao' },
  hl_biaoshi_caodao: { id: 'hl_biaoshi_caodao', title: '漕道黑货', hint: '"那条道上的货谁碰谁死"——平安号知道死字怎么写，可有人偏要碰。', hook: 'ev_caodao_heihuo' },
  hl_zuinu_anjuan: { id: 'hl_zuinu_anjuan', title: '未烬案卷', hint: '父亲"没写完的那份东西"压在架上。它当年烧了别人的全家，如今也压着你的命。', hook: 'ev_anjuan_wei' },
  hl_zuinu_yupei: { id: 'hl_zuinu_yupei', title: '半块玉佩', hint: '纹路对得上的半块玉——送它的人，是替小姐，还是替仇家？', hook: 'ev_yupei_ban' },
  hl_youfang_jiaoyin: { id: 'hl_youfang_jiaoyin', title: '香灰脚印', hint: '灵前的脚印没出去——师父的九个愿里，有一个"愿主"自己来了。', hook: 'ev_jiaoyin_yuan' },
  hl_youfang_yuanlai: { id: 'hl_youfang_yuanlai', title: '你的血', hint: '师父没说完的半句话。他一生物质不外泄，临终破例——你的血里，有大事。', hook: 'ev_nide_xue' },
  hl_shijia_zhangmu: { id: 'hl_shijia_zhangmu', title: '账目不清', hint: '做手脚的那个人管着半数族产。扳倒他，你爹的锅就翻了——可扳不倒，你家就完了。', hook: 'ev_zhangmu_fan' },
  hl_shijia_shanzhang: { id: 'hl_shijia_shanzhang', title: '山长荐书', hint: '族里放不放你走，不看你，看"磨刀石"还有没有用。', hook: 'ev_jianshu_fang' },
  hl_yaozu_donghuang: { id: 'hl_yaozu_donghuang', title: '东荒遗物', hint: '娘在东荒留下的东西，猎妖人也知道。取物之路，就是猎场。', hook: 'ev_donghuang_qu' },
  hl_yaozu_luopan: { id: 'hl_yaozu_luopan', title: '罗盘指你', hint: '罗盘的针总指着你——同门师兄弟里，出了"看货"的人。', hook: 'ev_luopan_zhi' },
  hl_geji_quzi: { id: 'hl_geji_quzi', title: '禁曲', hint: '娘说那支曲子什么时候都不能唱。帘后的笑声听过不止一次——有人在等它响。', hook: 'ev_jinqu_xiang' },
  hl_geji_beibian: { id: 'hl_geji_beibian', title: '北边要出事', hint: '兵部大人的酒后失言。"北边"是哪儿，"出事"是什么事——你的嗓子能换答案。', hook: 'ev_beibian_shi' },
};

// ---------- 人生节点 ----------
export const LIFE_NODES2 = {
  ln_jiangmen_1: {
    id: 'ln_jiangmen_1', title: '将门的枪', triggerAge: 18,
    text: '校场的老兵们凑了份子钱，给你重打了一杆枪。枪成那日，最老的老兵问你："娃，这杆枪举起来，就放不下了。你想拿它做什么？"',
    options: [
      { label: '从军戍关，重立将门的功名', effect: { stat: { wugongXiuwei: 40 }, ledger: { type: '誓', text: '以枪立誓，重振将门' } } },
      { label: '查清父亲战死的真相，再谈功名', effect: { ledger: { type: '记', text: '先问真相，后问功名' }, trait: { cha: 2 } } },
      { label: '卖了枪谱，做个普通人', effect: { stat: { money: 30 }, ledger: { type: '债', text: '变卖枪谱，将门落幕' } } },
    ],
  },
  ln_shuxiang_1: {
    id: 'ln_shuxiang_1', title: '读书人的路', triggerAge: 18,
    text: '秋闱在即。书肆掌柜替你留了个位子，父亲的书案上还压着他没批完的卷子。先生问："考，还是不考？"',
    options: [
      { label: '应试科举，走正途功名', effect: { stat: { xiwei: 20 }, ledger: { type: '誓', text: '应试秋闱，光耀门楣' } } },
      { label: '不考了——去"看"父亲批注里的那些东西', effect: { ledger: { type: '记', text: '弃考寻真，以天地为书' }, trait: { wu: 2 } } },
      { label: '先考，考完再走', effect: { stat: { xiwei: 10, money: 10 }, ledger: null } },
    ],
  },
  ln_shijing_1: {
    id: 'ln_shijing_1', title: '四牌楼的规矩', triggerAge: 18,
    text: '堂口管事和坊里的老户同时找到你：管事要你入伙，老户们凑钱求你"别走那条路"。四牌楼看着你的眼睛。',
    options: [
      { label: '入堂口——先挣钱，再谈干净', effect: { move: { city: 'tianqi', area: 'tq_dixia', node: 'tangkou' }, ledger: { type: '誓', text: '入堂口，走地下路' } } },
      { label: '不入伙，凭手艺吃饭', effect: { ledger: { type: '诺', text: '守着坊市，不走地下' }, trait: { juan: 2 } } },
      { label: '带着娘离开天启城', effect: { move: { city: 'linjiang', area: 'lj_cheng', node: 'lj_shuimen' }, ledger: null } },
    ],
  },
  ln_haidao_1: {
    id: 'ln_haidao_1', title: '第一次出海', triggerAge: 17,
    text: '商队的船缺个熟水性的，报酬够给阿公扯半年的药。船老大看着你："后生，海不认人情。上不上？"',
    options: [
      { label: '上船出海——海里的事，海里见', effect: { stat: { xiwei: 10 }, ledger: { type: '誓', text: '出海讨生活，以海为田' } } },
      { label: '留在岸上，学造船', effect: { ledger: { type: '记', text: '转投船坞，学造船艺' } } },
      { label: '听阿公的话，不再碰海', effect: { ledger: null, trait: { juan: 2 } } },
    ],
  },
  ln_yaopu_1: {
    id: 'ln_yaopu_1', title: '药师的活路', triggerAge: 17,
    text: '师父的咳疾越来越重。药铺的进项养得起铺子，养不起"大药"——除非，走试毒巷那条来钱快的路。',
    options: [
      { label: '接试毒巷的活，来快钱救师父', effect: { stat: { money: 40 }, ledger: { type: '债', text: '为救师入试毒巷，沾了灰路' } } },
      { label: '进山采药，以命换药', effect: { ledger: { type: '诺', text: '入山寻药，不碰灰路' }, trait: { meng: 1 } } },
      { label: '守着铺子慢慢熬', effect: { ledger: null } },
    ],
  },
  ln_qigai_1: {
    id: 'ln_qigai_1', title: '开口棒的取舍', triggerAge: 17,
    text: '老龙头要收你做"开口棒"的正式传人——从此城里的消息过你的耳朵，你也从此是"丐帮的人"。',
    options: [
      { label: '受棒入帮，做消息的眼睛', effect: { ledger: { type: '誓', text: '受丐帮开口棒，入帮' }, stat: { money: 20 } } },
      { label: '只做散乞，不入帮规', effect: { ledger: { type: '诺', text: '不入帮，做个自在乞儿' }, trait: { juan: 2 } } },
      { label: '用攒下的消息换一张离开天启的路引', effect: { move: { city: 'yanhui', area: 'yh_cheng', node: 'yh_changjie' }, ledger: null } },
    ],
  },
  ln_liehu_1: {
    id: 'ln_liehu_1', title: '猎户的山规', triggerAge: 17,
    text: '你头一回独立进山，就在崖边撞见了那头白鹿——它站在你爹失踪的地方，回头看你。开枪，还是不开？',
    options: [
      { label: '举弓——猎户的规矩，猎场无圣', effect: { stat: { wugongXiuwei: 30 }, ledger: { type: '记', text: '崖边失手，白鹿遁云' } } },
      { label: '放下弓，跟着它走', effect: { ledger: { type: '记', text: '随白鹿入云雾，见山中之秘' }, trait: { jue: 2 } } },
      { label: '退下山，从此不猎白兽', effect: { ledger: { type: '诺', text: '立誓不猎白兽' }, trait: { ren: 2 } } },
    ],
  },
  ln_biaoshi_1: {
    id: 'ln_biaoshi_1', title: '头一趟镖', triggerAge: 17,
    text: '总镖头给了你一趟"没名字"的小镖——没人愿走，也没人管你走成走不成。镖单上的货，你自己掂量。',
    options: [
      { label: '不开箱，走完就是', effect: { stat: { wugongXiuwei: 20, money: 15 }, ledger: { type: '记', text: '走完头趟无名镖' } } },
      { label: '偷偷开箱看看', effect: { ledger: { type: '记', text: '私验镖货，见箱中之秘' }, trait: { cha: 2 } } },
      { label: '退镖——这单不对劲', effect: { ledger: { type: '诺', text: '退无名镖，守平安号规矩' }, trait: { juan: 1 } } },
    ],
  },
  ln_zuinu_1: {
    id: 'ln_zuinu_1', title: '奴籍的枷', triggerAge: 19,
    text: '老太监给你指了条路：有份差事，办成了，脱籍。可那差事办的，是你家的仇人的事——办成了，仇人更加高升。',
    options: [
      { label: '先脱籍——身份都没有，谈什么报仇', effect: { ledger: { type: '记', text: '办差脱籍，忍辱先立身' }, trait: { yin: 2 } } },
      { label: '拒了——不为仇人抬轿', effect: { ledger: { type: '诺', text: '拒差守节，宁为奴不折腰' }, trait: { gang: 2 } } },
      { label: '接差，但在差事里做手脚', effect: { ledger: { type: '记', text: '借差行私，暗动手脚' }, trait: { mou: 2 } } },
    ],
  },
  ln_youfang_1: {
    id: 'ln_youfang_1', title: '九愿之始', triggerAge: 17,
    text: '你数着桃木杖上的红线，想起师父说"一圈是一个该还的愿"。第一个愿，他知道地方：城隍庙，替一个死了三十年的妇人，上一炷香。',
    options: [
      { label: '从第一愿开始，一愿一愿还', effect: { ledger: { type: '诺', text: '承师九愿，一愿一还' }, trait: { xin: 2 } } },
      { label: '不还愿——先弄清师父到底欠了什么', effect: { ledger: { type: '记', text: '先查九愿根由' }, trait: { cha: 2 } } },
      { label: '把杖埋了——愿是师父的，路是你的', effect: { ledger: { type: '债', text: '埋杖断愿，自行其路' } } },
    ],
  },
  ln_shijia_1: {
    id: 'ln_shijia_1', title: '旁支的姓', triggerAge: 18,
    text: '族老们议定：旁支子弟想入正卷，要么立"功"——替族里办成一件大事；要么立"艺"——在族比里夺魁。你只能选一条。',
    options: [
      { label: '办差立功——去管事手下当差', effect: { stat: { money: 25 }, ledger: { type: '记', text: '入族办差，忍气立功' } } },
      { label: '族比夺艺——武堂见真章', effect: { stat: { wugongXiuwei: 35 }, ledger: { type: '誓', text: '族比夺魁，以武入卷' } } },
      { label: '不争了——脱族自立', effect: { ledger: { type: '记', text: '脱柳氏族，自姓氏自立' }, trait: { gang: 2 } } },
    ],
  },
  ln_yaozu_1: {
    id: 'ln_yaozu_1', title: '化形之择', triggerAge: 17,
    text: '血脉的关口到了。妖人坊的老婆婆摆了两碗酒：一碗喝了全化人形，从此血脉封存；一碗喝了守住原形，从此人间容你难。',
    options: [
      { label: '化形全人——藏起耳朵藏起眼', effect: { ledger: { type: '记', text: '化形全人，血脉深藏' }, stat: { xiwei: 15 } } },
      { label: '守住原形——我是妖，妖有妖的路', effect: { ledger: { type: '记', text: '守形存真，以妖入世' }, stat: { wugongXiuwei: 20 } } },
      { label: '两碗都不喝——第三条路自己走', effect: { ledger: { type: '记', text: '拒化形，自择前路' }, trait: { jue: 2 } } },
    ],
  },
  ln_geji_1: {
    id: 'ln_geji_1', title: '云遮月的去处', triggerAge: 17,
    text: '一位郡王听了你的曲，要买你入王府。将军府松了口——将军的意思很明白：留下是"耳朵"，走了是"人情"。',
    options: [
      { label: '入王府——更高的地方，更多的耳朵', effect: { stat: { money: 60 }, ledger: { type: '记', text: '转投王府，身价倍增' } } },
      { label: '求将军放籍——拿知道的秘密换', effect: { ledger: { type: '债', text: '以秘换籍，欠将军一回' }, trait: { mou: 1 } } },
      { label: '留下——耳朵还没听够想听的', effect: { ledger: null } },
    ],
  },
};
