// 四期 v4.0：门派扩编（五派 → 十六派）。新派多落在三期新地图，师承各占一地。
// 结构与 sects.js 完全一致：gongfa/secondGongfa/duties/annual/grudges/rule。
export const SECTS2 = {
  yaowanggu: {
    id: 'yaowanggu', name: '药王谷', kind: '药门', city: 'baicao', node: 'bc_yaowangmiao',
    masterNpc: 'bc_miaozhu',
    kaoyanEvent: 'ev_kaoyan_yaowanggu',
    motto: '药有王道，医有仁心。谷里的规矩：先学尝药，再学救人。',
    gongfa: { id: 'gf_yaowang_bianyao', name: '辨药指诀', desc: '药王谷入门手艺。三指一搭，药性自知——认药认得准，救人救得稳。', level: 1, realm: 'lianqi' },
    secondGongfa: { id: 'gf_yaowang_tangdi', name: '汤帝遗方', desc: '谷主压箱底的方子。药引只有一味：医者自己的耐性。', level: 2, realm: 'lianqi' },
    duties: [
      { label: '进山采药一日', text: '药王谷的采药规矩：采一株，留一株，再补一株籽。回谷过秤时管药的只看你的筐底——留没留籽，筐底最诚实。', effect: { stat: { xiwei: 3 }, trait: { ren: 1 }, money: 1 } },
      { label: '在药王庙义诊半日', text: '庙前的老槐树下支一张桌。你看了十几个病人，方子开得越来越轻——师父说过：药是借来的力，人的元气才是本钱。', effect: { stat: { wugongXiuwei: 2 }, trait: { ren: 1 }, dutyFlag: 'shanming' } },
      { label: '守药炉一夜', text: '文火守一夜，偏头打了个盹，药就糊了。师父没骂，把糊药倒进田里：糊药喂田，明年的药性会记得你的错。', effect: { stat: { xiwei: 4 }, flags: { yaolu_guo: true } } },
    ],
    annual: [
      '今年谷里试种成功一味新药——用百草坞的雾水浇出来的。谷主说：药也是庄稼，天时地利缺一样都不成。',
      '山下时疫，谷门大开三日。你跟着师兄们熬了三天三夜的药——药王谷的名声，就是这么一锅一锅熬出来的。',
    ],
    grudges: {},
    rule: '叛出药王谷者，天下药材行不售其药——医者的路，是自己走窄的。',
  },
  kunwu_jianzhuang: {
    id: 'kunwu_jianzhuang', name: '昆吾铸剑山庄', kind: '器门', city: 'kunwu', node: 'kw_jianlu',
    masterNpc: 'kw_laojiang',
    kaoyanEvent: 'ev_kaoyan_kunwu',
    motto: '剑是打出来的，人也是。炉火不认人，只认真东西。',
    gongfa: { id: 'gf_kunwu_duanfa', name: '锻体打铁功', desc: '山庄的看家功。锤起锤落间，把自己也炼进去——打铁的人，骨头比铁硬。', level: 2, realm: 'wudao' },
    secondGongfa: { id: 'gf_kunwu_xianghuo', name: '相火诀', desc: '看火候的眼力。炉温差一分，剑就差一命——老庄主说他看了六十年，还在学。', level: 2, realm: 'lianqi' },
    duties: [
      { label: '抡大锤一日', text: '小锤定位，大锤开坯。一天抡下来，虎口裂了三次——老师傅看了看锤印：「节奏对了一半。剩下那一半，在腰上。」', effect: { stat: { wugongXiuwei: 4 }, trait: { hen: 1 }, money: 1 } },
      { label: '守炉看火三夜', text: '三夜不合眼，盯的就是那一团火的颜色。你后来才懂：铸剑铸的不是铁，是「等」——等铁到了那一个颜色的那一瞬。', effect: { stat: { xiwei: 4 }, flags: { kanhuo: true } } },
      { label: '给矿市送一批剑坯', text: '路不远，货不轻。交割时矿市的老人翻看剑坯，多给了两成银子：「回去告诉老江，他打的坯子，还是那个味。」', effect: { stat: { wugongXiuwei: 2 }, money: 3, trait: { yi: 1 } } },
    ],
    annual: [
      '今年炉神祭，山庄开了老炉——那是三百年前铸镇山剑的炉。老师说：让年轻人看看，什么叫「一炉火，三代人」。',
      '矿上出了事，塌了半条矿道。山庄连夜打了四十根支撑的铁柱送下去——剑是凶器，可打剑的人心是软的。',
    ],
    grudges: {},
    rule: '叛出铸剑山庄？铁会冷，炉不会忘。天下的剑都记得你的名字——不是好记法。',
  },
  wanyao_meng: {
    id: 'wanyao_meng', name: '万妖盟', kind: '妖门', city: 'donghuang', node: 'dh_huaxing',
    masterNpc: 'dh_yao_yi',
    kaoyanEvent: 'ev_kaoyan_wanyao',
    motto: '妖修的是「化」，人修的是「忘」。盟里人妖同修——化形易，化心难。',
    gongfa: { id: 'gf_meng_tuina', name: '妖脉导引术', desc: '妖医亲传。人妖两脉的气走法不同——这术把两条路缝成一条，缝的时候疼，缝好了快。', level: 1, realm: 'lianqi', mai: 'yao' },
    secondGongfa: { id: 'gf_meng_huagu', name: '化骨绵章', desc: '盟里禁术外唯一的软功。化的是自己骨头里的「戾」——化一分，妖气纯一分。', level: 2, realm: 'lianqi', mai: 'yao' },
    duties: [
      { label: '妖城义诊一日', text: '你跟着妖医看诊，人一半妖一半。有个狼妖的孩子学坐学了三年，今天终于坐稳了——满堂妖都鼓掌，掌声像风过林子。', effect: { stat: { xiwei: 4 }, trait: { ren: 1 } } },
      { label: '替盟里送药去界碑', text: '药是给巡界妖卒的跌打药。界碑的妖卒收药时让你站进碑影里避风——妖域的规矩：送药的人，不受风。', effect: { stat: { wugongXiuwei: 2 }, trait: { yi: 1 }, flags: { yao_beiying: true } } },
      { label: '夜里守化形学堂', text: '学堂里的妖娃娃学「坐」学得东倒西歪。你守了一夜，帮七个尾巴藏好的娃娃掖了掖被角。化形第一课原来不是化形，是像家。', effect: { stat: { xiwei: 3 }, trait: { cha: 1 } } },
    ],
    annual: [
      '今年化形学堂来了第一个「人」学生——猎户的孩子，偷跑来学妖语。盟里议了半日，收了。妖医说：路是越走越宽的。',
      '万妖山碑纹无故发亮三日。守碑人说是好事——「碑在认人，认的是这三年盟里做下的事。」',
    ],
    grudges: {},
    rule: '叛出万妖盟者，妖域除名——碑纹不再认你。妖域的「规矩」，不进则寒。',
  },
  kuxing_tang: {
    id: 'kuxing_tang', name: '苦行堂', kind: '佛门 · 苦行', city: 'ximo', node: 'xm_foguta',
    masterNpc: 'xm_kuseng',
    kaoyanEvent: 'ev_kaoyan_kuxing',
    motto: '以身为塔，以苦为阶。塔里供的不是佛，是「受」。',
    gongfa: { id: 'gf_kuxing_shenjiao', name: '身受观', desc: '苦行堂的根本法。把苦分成十分来「受」——受得住七分，心就定；受住十分，就轮到苦怕你。', level: 1, realm: 'lianqi', mai: 'fo' },
    secondGongfa: { id: 'gf_kuxing_talin', name: '塔林坐照诀', desc: '在先代高僧骨塔之间坐照。堂里说：两百座塔就是两百位老师——它们不出声，但都在看。', level: 2, realm: 'lianqi', mai: 'fo' },
    duties: [
      { label: '大漠行脚十日', text: '日头把影子钉在沙上。第十日你回到塔林，苦行僧只问了一句：「渴吗？」——「渴。」——「好。记住这个渴，它比经文诚实。」', effect: { stat: { xiwei: 4 }, trait: { xin: 1 } } },
      { label: '为塔林扫沙半月', text: '沙永远扫不完——昨天的沙今天又落回来。扫到第十二天你忽然不烦了：原来扫沙扫的就是「扫不完」这颗心。', effect: { stat: { xiwei: 5 }, trait: { ren: 1 }, dutyFlag: 'shanming' } },
      { label: '给商队施水一程', text: '香市出发的商队，堂里每程送三桶井水。收水的驼夫合十谢佛，你说谢堂里的井——他们笑：「井是佛的。」这账，算得真好。', effect: { stat: { wugongXiuwei: 2 }, trait: { ren: 1 }, money: -1, dutyFlag: 'shanming' } },
    ],
    annual: [
      '今年大漠的沙比往年大。塔林埋了三座塔，僧人们挖了三日，又把塔立回去——堂里的规矩：塔倒了立，人倒了也立。',
      '堂里来了位还俗三十年的老僧，回来接着扫沙。苦行僧把旧扫帚还给他——扫帚一直挂在原处，没落过灰。',
    ],
    grudges: {},
    rule: '叛出苦行堂，不是罪——是「债」。你受过的每一分苦，都会在你心里换一种方式讨回来。',
  },
  gumen: {
    id: 'gumen', name: '十八峒蛊门', kind: '南疆 · 蛊道', city: 'nanjiang', node: 'nj_bazhai',
    masterNpc: 'nj_zhai_lao',
    kaoyanEvent: 'ev_kaoyan_gumen',
    motto: '蛊不是毒，是「诚」。养蛊先养心——心里有假的人，蛊第一个知道。',
    gongfa: { id: 'gf_gu_yinjian', name: '引蛊诀', desc: '蛊门入门法。引蛊不是驱使，是「商量」——你跟蛊商量，得先跟自己商量明白。', level: 1, realm: 'lianqi' },
    secondGongfa: { id: 'gf_gu_jingxin', name: '静心蛊章', desc: '峒老传下的护心法。养一枚静心蛊在腕间——心一乱，它就冷；心一假，它就咬。', level: 2, realm: 'lianqi' },
    duties: [
      { label: '入瘴林采蛊母', text: '瘴林里走了半日，采回三枚蛊母。峒老验过，退回一枚：「这枚怕生。放回去——蛊也挑人，你得让它先挑你。」', effect: { stat: { xiwei: 4 }, trait: { xin: 1 } } },
      { label: '替寨里看一次蛊诊', text: '你端着蛊碗给病家验血——两滴血在碗里「融」了。病家全家喜极而泣。你忽然懂了峒里的话：蛊验的从来不是血，是人心里的底。', effect: { stat: { xiwei: 3 }, trait: { ren: 1 }, dutyFlag: 'shanming' } },
      { label: '给十八峒送秋信', text: '一峒一峒地走，一句一句地传。走到第十八峒，你一张口就是地道的南疆话——守寨的少年笑：「你这一趟，走得比路长。」', effect: { stat: { wugongXiuwei: 3 }, trait: { cha: 1 }, flags: { nanjiang_ren: true } } },
    ],
    annual: [
      '今年两峒的旧怨解了——不是谁赢了，是两家的娃娃自己成了亲。峒老们在火塘边喝到半夜：「老账老账，就该让给小辈去翻篇。」',
      '瘴林里的蛊母今年格外肥。老峒婆说是山养得好——十八峒给山补了三年的林子，山记得。',
    ],
    grudges: {},
    rule: '叛出蛊门者，峒里不再认。南疆的路会认得你——瘴林里迷路的人，可没人再引。',
  },
  xueshan_jianyuan: {
    id: 'xueshan_jianyuan', name: '雪山剑院', kind: '剑门', city: 'beiyuan', node: 'by_jianyuan',
    masterNpc: 'by_jian_shi',
    kaoyanEvent: 'ev_kaoyan_xueshan',
    motto: '剑出如雪落——不急，不重，不停。雪下得最稳的时候，是最冷的时候。',
    gongfa: { id: 'gf_xuejian_luoxue', name: '落雪剑', desc: '剑院根本剑法。一剑递出去，像雪落下来——看着轻，落了地才知道分量。', level: 2, realm: 'wudao', mai: 'jian' },
    secondGongfa: { id: 'gf_xuejian_anken', name: '暗刃诀', desc: '剑师压箱底的东西：剑藏在鞘里那一段，才是剑。这一诀教的，是「还没出鞘」的那一段。', level: 2, realm: 'wudao', mai: 'jian' },
    duties: [
      { label: '雪中站桩一个时辰', text: '雪落在肩上不扫，桩在雪里不摇。收势时剑师只看了看你的脚印：「脚印没乱。心也没乱。明日加半个时辰。」', effect: { stat: { wugongXiuwei: 5 }, trait: { hen: 1 } } },
      { label: '扫剑院雪一日', text: '院里十万柄剑的倒影都映在雪上。你扫到日头偏西才明白：扫的不是雪——是让每一柄剑都照得见自己。', effect: { stat: { xiwei: 3 }, trait: { ren: 1 } } },
      { label: '下山送一趟剑信', text: '剑信是真剑——收信人拔剑验看，剑身上刻着sender的剑痕。「痕还在，」他说，「剑院的人，走了多远都带着痕。」', effect: { stat: { wugongXiuwei: 3 }, trait: { yi: 1 }, money: 1 } },
    ],
    annual: [
      '今年剑院大比，第一名是烧火的杂役。剑师把剑谱递给他时说了句：「剑不看出身。雪落在谁肩上，都一样冷。」',
      '北原雪封山两月。院里的课照上——在雪里上。剑师说：风雪是天下最公平的陪练，它不让你，也不害你。',
    ],
    grudges: {},
    rule: '叛出剑院者，剑冢的剑不再为你鸣——北原的雪记得每一柄剑的脾气，也记得每一个人的。',
  },
  shushan: {
    id: 'shushan', name: '蜀山', kind: '仙门 · 剑宗', city: 'shushan', node: 'ss_jianzheng',
    masterNpc: 'ss_jian_ge',
    kaoyanEvent: 'ev_kaoyan_shushan',
    motto: '云上修行，云下行走。蜀山教的第一件事：本事越大，越要下山。',
    gongfa: { id: 'gf_shushan_yujian', name: '御剑术·云篇', desc: '蜀山入门剑诀。御剑先御气，御气先御心——云海之上练这一诀，摔的每一跤都是学费。', level: 2, realm: 'lianqi' },
    secondGongfa: { id: 'gf_shushan_zhengqi', name: '浩然剑气', desc: '剑阁镇山之诀。气从「正」字上来——做一件亏心事，剑气就钝一分。仙门的账，记在心里。', level: 2, realm: 'zhuji' },
    duties: [
      { label: '剑阁守值三日', text: '守剑三日，给每一柄剑掸尘。第三日你最敬的那柄剑忽然轻鸣一声——长老说，它认了你的手。「剑阁的剑认人，比人认人快。」', effect: { stat: { xiwei: 5 }, trait: { xin: 1 } } },
      { label: '下山历练断一案', text: '山下小镇两姓争水，斗了三代。你在中间坐了七日，把水契翻了个底朝天——最后断出个两头都不满意、但都认的章程。回山时你觉得，这一趟比练剑十年值。', effect: { stat: { wuxing: 1, wugongXiuwei: 2 }, trait: { ren: 1 }, dutyFlag: 'shanming' } },
      { label: '云海采药一程', text: '云海里的灵芝长在剑气到不了的地方——只能徒手攀。回来时你手里攥着三株，长老只问：「手划破了几处？」「七处。」——「好，没用手套。药认血。」', effect: { stat: { xiwei: 4 }, money: 2 } },
    ],
    annual: [
      '今年山门收了个寒门弟子，考较的是「雪夜让伞」的旧事——蜀山收人，先看心，再看骨。',
      '山下降妖折了两位师兄。山门下半旗三日，长老在剑阁立了块新碑：碑上没有功过，只有名字。蜀山的体面，就体面在这儿。',
    ],
    grudges: {},
    rule: '叛出蜀山者，云海不留。仙门的门楣高——可叛徒的「叛」字，比门楣更高，走到哪儿都看得见。',
  },
  huangquan_hui: {
    id: 'huangquan_hui', name: '黄泉会', kind: '江湖 · 地下', city: 'huangquan', node: 'hq_dufang',
    masterNpc: 'hq_dufang_zhanggui',
    kaoyanEvent: 'ev_kaoyan_huangquan',
    motto: '地下也讲规矩——而且比地上讲得更严。地上的官府管不了的事，我们管；管得了的，我们不碰。',
    gongfa: { id: 'gf_hq_yashou', name: '押手短打', desc: '黄泉会的吃饭本事。狭路相逢，三招之内见真章——地下没有场地给你绕圈子。', level: 2, realm: 'wudao' },
    secondGongfa: { id: 'gf_hq_duyan', name: '赌眼诀', desc: '掌柜的看家眼力。一眼看穿袖里的骰子、面上的笑、背后的刀——这一诀练成，地下横着走。', level: 2, realm: 'wudao' },
    duties: [
      { label: '坐柜记账三日', text: '地下的账比地上的干净——每一笔都记着「谁欠谁」。你记到第三日才懂：黄泉集为什么没官府还乱不起来——账在，规矩就在。', effect: { stat: { xiwei: 3 }, trait: { chi: 1 }, money: 2 } },
      { label: '押一趟「夜里的货」', text: '货是什么不许问。路上遇了剪径的，你按「规矩」办：退三步，亮牌面——对方看清是黄泉会的货，拱手让了道。地下的「信」，比刀硬。', effect: { stat: { wugongXiuwei: 4 }, money: 3, trait: { yi: 1 } } },
      { label: '替会里「了」一桩旧怨', text: '两家争了十年的铺面。掌柜的只让你带一句话过去，又带一句话回来——怨就了了。你后来问那两句话是什么。掌柜的笑：「一句话给台阶，一句话给脸面。地下的学问，全在这两句里。」', effect: { stat: { wuxing: 1 }, trait: { cha: 1 }, flags: { hq_liao_yuan: true } } },
    ],
    annual: [
      '今年官府查得紧，会里歇了三桩「营生」。掌柜的召集众人：「风紧了就收帆。我们这行，活得久才是本事。」',
      '会里一位老兄弟「金盆洗手」，掌柜的亲自送出集口，递上一包路上的干粮——地下的规矩：走出去的，就别回头；回头的，也不赶。',
    ],
    grudges: {},
    rule: '叛出黄泉会——地下的门，从来只进不出。出了这个集，你欠的账会自己找到你。',
  },
  shouxu_yimai: {
    id: 'shouxu_yimai', name: '守墟一脉', kind: '古仙遗脉', city: 'kunlunxu', node: 'kx_tianjie',
    masterNpc: 'kx_shouxu',
    kaoyanEvent: 'ev_kaoyan_shouxu',
    motto: '一万年，就守一句话：「等一个看得懂剑痕的人。」你不是徒弟——你是「接班人」。',
    gongfa: { id: 'gf_kx_guanhen', name: '观痕篇', desc: '守墟一脉的根本法。不练气，练「看」——一万年前的剑痕里藏着的东西，看懂一分，得一分。', level: 2, realm: 'zhuji' },
    secondGongfa: { id: 'gf_kx_buzhen', name: '补墟诀', desc: '残殿的修补之法。补墙是假的，补「断了的一剑」是真的——这一诀没有练成的人，只有练着的人。', level: 2, realm: 'jindan' },
    duties: [
      { label: '拓印剑痕三月', text: '三个月，拓了满墙的痕。你的手上磨出茧，眼里磨出「静」——守墟人说：「现在你拓的不是痕了，是当年那一剑的『心』。」', effect: { stat: { xiwei: 6 }, trait: { ren: 1 } } },
      { label: '修补残殿一角', text: '你按古法调浆、和灰、补墙——补完那一角，一万年的断口终于合了一线。守墟人伸手摸了摸，半天没说话。最后只说：「历代守墟人，都补过这里。现在轮到你了。」', effect: { stat: { xiwei: 5 }, flags: { kx_buxu: true } } },
      { label: '为寻仙者引路一月', text: '来昆仑墟寻仙的人不少，登得上的没几个。你守在天阶下劝退了三十人、护送了三人。守墟人说：「劝退是慈悲，护送是缘分——这一脉守的，就是这两样。」', effect: { stat: { wugongXiuwei: 3 }, trait: { xin: 1 }, dutyFlag: 'shanming' } },
    ],
    annual: [
      '今年天阶上来了一位真正「看得懂」的老者——守墟人与他对坐了三日，下山时笑得像个孩子：「一万年，没白等。」',
      '残殿的主梁终于全接上了。这一代守墟人前后修了四十年——「不用修完，」守墟人说，「守墟的『守』字，是给下一代的。」',
    ],
    grudges: {},
    rule: '守墟一脉没有「叛」字——你走出昆仑墟，脉就断在你身上。天阶的雪会替你记着。',
  },
  nanhai_shangmeng: {
    id: 'nanhai_shangmeng', name: '南海商盟', kind: '江湖 · 商道', city: 'nanhai', node: 'nh_bujidao',
    masterNpc: 'nh_daoyou',
    kaoyanEvent: 'ev_kaoyan_nanhai',
    motto: '海上没有官府，只有账。商盟的船跑得远，是因为「信」比风跑得更远。',
    gongfa: { id: 'gf_shang_chuanyan', name: '船眼术', desc: '商盟跑海的根本。看云识风、看浪识流、看人识心——三样都看准了，船就丢不了。', level: 1, realm: 'lianqi' },
    secondGongfa: { id: 'gf_shang_pansuan', name: '盘算心经', desc: '盟主的算学秘本。算货、算程、算人心——最后一页只有一行字：「最贵的东西，从来不入账。」', level: 2, realm: 'lianqi' },
    duties: [
      { label: '随商船跑一趟季风', text: '三十天海路，你学会了看三种云、听两种浪、记十一个航标。回港时盟主翻看你的海记：「记得比我当年细。海不欺负记得细的人。」', effect: { stat: { xiwei: 4 }, trait: { chi: 1 }, money: 3 } },
      { label: '补给岛理货半月', text: '一箱一箱地清点、登记、盖印。半月下来你闭着眼都知道第几舱装的什么——理货理的是货，练的是「一件都不许错」的心。', effect: { stat: { xiwei: 3 }, trait: { ren: 1 }, money: 1 } },
      { label: '替盟里谈一笔小货', text: '对面是老海商，报价咬得死死的。你按盟里的规矩让了三分利、守了七分底——成交后老海商多送你一箱货：「会算的不稀奇，会「让」的，是海上真做大事的。」', effect: { stat: { wuxing: 1 }, trait: { cha: 1 }, money: 4, dutyFlag: 'shanming' } },
    ],
    annual: [
      '今年台风季，盟里折了一条船。盟主把抚恤送到每一家，然后议定新规：季风季减载三成——「银子少赚，人一个都不能少。」',
      '盟里今年的新航路开到了传说中的「无风带」边上。老船工们都摇头，盟主却笑了：「海图的边，就是船头的路。」',
    ],
    grudges: {},
    rule: '叛出商盟者，四海的码头不留你的货——海上做买卖，信字碎了，浪都不让你。',
  },
  qianji_lou: {
    id: 'qianji_lou', name: '千机楼', kind: '地下 · 奇门', city: 'tianqi', node: 'guishi',
    masterNpc: 'guishi_zhanggui',
    kaoyanEvent: 'ev_kaoyan_qianji',
    motto: '鬼市三更开，千机一线牵。楼里做的都是「信息」的营生——话比金子贵，也比金子危险。',
    gongfa: { id: 'gf_qj_qiaoshou', name: '巧手开匣术', desc: '千机楼的吃饭手艺。开的是匣，练的是「稳」——手一抖，传出去的就不是消息，是讣告。', level: 2, realm: 'wudao' },
    secondGongfa: { id: 'gf_qj_tingfeng', name: '听风辨器', desc: '楼里高手的耳功。脚步听人，语气听心，满堂喧哗里听出「那一句不该说的话」。', level: 2, realm: 'lianqi' },
    duties: [
      { label: '鬼市蹲守三日', text: '三更开市，你守在暗处看了三日的人来人往。回楼交差时大掌柜只问：「看见什么了？」——「什么都没看见。」——「好。会看的人先学会看不见。」', effect: { stat: { xiwei: 4 }, trait: { chi: 1 } } },
      { label: '替楼里送一封「口信」', text: '没有纸笔，七个字，记在脑子里。你走了半个京城，送到时一字不差——收信的人摘下帽子看了看你的脸：「告诉掌柜的，这孩子，嘴严。」', effect: { stat: { wugongXiuwei: 3 }, trait: { xin: 1 }, money: 2, flags: { qj_zuiyan: true } } },
      { label: '修一晚千机匣', text: '楼里的传信匣全是精巧机关。你拆了一整晚装不回去，老师傅接过去，三下装好：「别背图。图是死的——摸清每个机关「想干什么」，手就自己动了。」', effect: { stat: { xiwei: 3 }, trait: { wu: 1 } } },
    ],
    annual: [
      '今年楼上下了三道封口令。大掌柜的把令牌钉在梁上：「千机楼卖的是话——可有些话，买了也要替客人带进棺材。」',
      '官府来人「例行」查了鬼市。掌柜的陪着转了一夜，末了送客——第二天楼里照常开市。地下的事，地下有地下的章法。',
    ],
    grudges: {},
    rule: '叛出千机楼？楼里有一万个「知道」。你会变成其中一条——而且是最先被卖掉的那条。',
  },
};
