// 六期 v6.0：门派扩编 16 → 30。新十四派多为「业门」——江湖百业的行会化，
// 与武门/药门/妖门错落。结构同 sects.js：gongfa/secondGongfa/duties/annual/rule。
export const SECTS3 = {
  canglan_shipai: {
    id: 'canglan_shipai', name: '沧澜船行', kind: '水门', city: 'canglan', node: 'cl_chuanwu',
    masterNpc: 'cl_chuanshi',
    kaoyanEvent: 'ev_kaoyan_shipai',
    motto: '船行水上，人走浪里。行里的规矩：船老大最后一个离船。',
    gongfa: { id: 'gf_shipa_taolang', name: '踏浪桩', desc: '船行入门桩功。在摇晃的甲板上站得稳，在安稳的地面上就站得更稳。', level: 1, realm: 'wudao' },
    secondGongfa: { id: 'gf_shipa_guanchao', name: '观潮眼', desc: '行老的看家眼力。三里外的浪头一翻，就知道这潮接不接得住。', level: 2, realm: 'lianqi' },
    duties: [
      { label: '随船押货一水', text: '一水三天的航程。货舱里睡不着的时候，船老大教你看星——「罗盘会坏，星不会。人这一行，最后靠的还是抬头。」', effect: { stat: { wugongXiuwei: 3 }, money: 2, trait: { yi: 1 } } },
      { label: '修船坞打杂一日', text: '给旧船刮底换板。刨下来的木屑里有一股咸腥气——船老大说那是「船记事的味道」，跑过什么海，木头都记得。', effect: { stat: { xiwei: 3 }, flags: { chuanji: true } } },
      { label: '灯塔司联合夜巡', text: '每月初一，船行和灯塔司联合巡一遍暗礁浮标。你划着小舢板在黑浪里走了一个来回——回港时守塔老司给你递了一盏热茶：「夜海认得每一个来巡过它的人。」', effect: { stat: { xiwei: 3 }, trait: { xin: 1 } } },
    ],
    annual: [
      '今年台风季，船行折了两条船，救回十一个人。行老在码头立了块碑——不是记船，是记那十一个名字。',
      '船行今年开了夜航。行里老人们议了三天：夜航险，但山里等药的病人等不起。开。配双倍灯火。',
    ],
    grudges: {},
    rule: '叛出沧澜船行者，行内船不载——海上的路，是船连着船走出来的。',
  },
  linjiang_shuiban: {
    id: 'linjiang_shuiban', name: '临江水驳行', kind: '漕门', city: 'linjiang', node: 'lj_caobang',
    masterNpc: 'lj_bangzhong',
    kaoyanEvent: 'ev_kaoyan_shuiban',
    motto: '一篙一橹一条命，装得下货，装不下贪。',
    gongfa: { id: 'gf_shuiban_chenggan', name: '撑篙十三式', desc: '驳行吃饭的本事。一篙点底，借的是水的力——顺水省力，逆水借力，横水躲力。', level: 1, realm: 'wudao' },
    secondGongfa: { id: 'gf_shuiban_dujiang', name: '渡江诀', desc: '行内压箱的心法。浪打来的时候，先稳的不是船，是持篙那只手。', level: 2, realm: 'wudao' },
    duties: [
      { label: '驳货一日', text: '一篙一篙把大船的货驳上小船。腰酸背痛时想起行老的话：「驳行挣的是『两头都信得过』的钱——大船信你，小船也信你。」', effect: { stat: { wugongXiuwei: 4 }, money: 2 } },
      { label: '汛期守堤半日', text: '江汛涨上来，全行的人上堤扛沙袋。你扛到天亮，堤守住了——行老递给你一碗热酒：「这就是驳行每年最挣钱的一天，可谁也不许提钱。」', effect: { stat: { xiwei: 4 }, trait: { yi: 1 } } },
      { label: '清淤疏浚半日', text: '枯水季，全行下江清淤。你一锹一锹把淤泥铲出去，肩膀磨破了皮——行老看着江水重新流顺：「驳驳驳，驳的是货，养的是江。江活了，我们才活。」', effect: { stat: { wugongXiuwei: 3 }, trait: { ren: 1 } } },
    ],
    annual: [
      '今年江面出了三起沉船，行里立了新规：夜里行驳，双篙双灯——多花的是钱，省下的是命。',
      '驳行今年收了个女学徒，满行反对了三天，行老一锤定音：「篙不认男女，水也不认。」',
    ],
    grudges: {},
    rule: '叛出驳行者，江上无人肯渡你——篙把子上的规矩，比官府的告示硬。',
  },
  luanzang_shougu: {
    id: 'luanzang_shougu', name: '收骨人', kind: '阴门', city: 'huangquan', node: 'hq_luanzangling',
    masterNpc: 'hq_shouling_ren',
    kaoyanEvent: 'ev_kaoyan_shougu',
    motto: '乱葬岭上没有官府的事——死人的体面，归收骨人管。',
    gongfa: { id: 'gf_shougu_anbu', name: '安步诀', desc: '岭上传下的步法。夜行乱葬地，脚步要「稳过死人」——稳了，邪祟拿你没办法。', level: 1, realm: 'lianqi' },
    secondGongfa: { id: 'gf_shougu_zhaoGu', name: '照骨灯', desc: '守岭人的眼功。灯影里看骨相，能看出死者最后的心愿——心愿了，骨才安。', level: 2, realm: 'lianqi' },
    duties: [
      { label: '收骨归葬一趟', text: '岭上收一具无名骨，葬进义冢，立一块写得出名字的牌。师父说：「我们干的是『让死人像个人』的活——牌上有没有字，差别就是这么大。」', effect: { stat: { xiwei: 4 }, trait: { ren: 1 } } },
      { label: '守义冢一夜', text: '义冢夜守，给长明灯添三次油。后半夜风声很杂，你忽然不怕了——「怕的是亏心。收骨人的灯下，站着的是全岭最干净的人。」', effect: { stat: { xiwei: 3 }, trait: { xin: 1 } } },
      { label: '誊写义冢名册', text: '每月誊一遍义冢名册——三千块牌，一块都不能漏。师父说：「字写得慢，念的人才读得清。名册是写给生人看的，也是念给死人听的。」', effect: { stat: { xiwei: 2 }, trait: { xin: 1 }, flags: { mingCe: true } } },
    ],
    annual: [
      '今年岭上来了位官府的差官，要清岭「整顿」。守岭人把义冢名册摊开——差官看完名册，自己走了。',
      '义冢今年扩建了三十个位。师父说：岭上无主的人越来越少，这是好事——也是坏事的反面。',
    ],
    grudges: {},
    rule: '叛出收骨人者，岭上无名骨再无人收——这一行没有同门，只有同「心」。',
  },
  tianqi_baigong: {
    id: 'tianqi_baigong', name: '天启百工馆', kind: '工门', city: 'tianqi', node: 'sipailou',
    masterNpc: 'xiFu',
    kaoyanEvent: 'ev_kaoyan_baigong',
    motto: '百工百艺，门门通不如一门精；一门精不如一心正。',
    gongfa: { id: 'gf_baigong_qiao', name: '巧手诀', desc: '馆里的开手课。手艺人的手要「巧而不浮」——巧是天生，不浮是练的。', level: 1, realm: 'wudao' },
    secondGongfa: { id: 'gf_baigong_tongxin', name: '通心术', desc: '馆主压箱的本事。看一件东西做得好不好，先看做它的人当时心里在不想别的。', level: 2, realm: 'lianqi' },
    duties: [
      { label: '馆内帮工一日', text: '今天是给东市牌坊描金。描到最高处风很大，你在百尺竿头手稳如磐——馆主在楼下喊：「手艺人手抖不丢人，心里抖才丢人！」', effect: { stat: { wugongXiuwei: 3 }, money: 2 } },
      { label: '替穷巷修屋半日', text: '馆里每月一天「义工日」，给穷巷修屋顶补门窗。你修到第三家，老大娘非要塞给你两个热鸡蛋——馆主说：「这俩鸡蛋，比官府的嘉奖都值钱，收好。」', effect: { stat: { xiwei: 3 }, trait: { ren: 1 } } },
      { label: '馆内讲艺一刻', text: '每旬一次，人人上台讲自己的手艺——讲不通的回去再练。轮到你那天，你讲了半个时辰，馆主听完只问了一句：「你讲的这些，你的手做得到几成？」', effect: { stat: { wuxing: 3 }, trait: { cha: 1 } } },
    ],
    annual: [
      '今年馆里大比，木工组出了个八岁的小神童，雕的貔貅眼睛会「看人」。馆主收了——百工馆的门槛，从来不在岁数。',
      '官府来请馆主督造宫城，馆主回了：「匠人管匠活，不管宫斗。」——百工馆今年的账上，少了一笔大生意，多了一屋子的踏实。',
    ],
    grudges: {},
    rule: '叛出百工馆者，百工不与共事——手艺人的圈子小，记性长。',
  },
  guishi_hanghui: {
    id: 'guishi_hanghui', name: '鬼市行会', kind: '商门', city: 'tianqi', node: 'guishi',
    masterNpc: 'guishi_zhanggui',
    kaoyanEvent: 'ev_kaoyan_guishi',
    motto: '鬼市无欺——骗人的在白天，讲信的在天黑以后。',
    gongfa: { id: 'gf_guishi_yanshu', name: '验物手', desc: '行会吃饭的眼手功夫。一件东西上手三息，出处、年代、猫腻，八九不离十。', level: 1, realm: 'lianqi' },
    secondGongfa: { id: 'gf_guishi_shouXin', name: '守心诀', desc: '会长的压箱心法。鬼市遍地是「便宜」，守心诀护的是「不占不该占的便宜」——占过一次，手就再也验不准了。', level: 2, realm: 'lianqi' },
    duties: [
      { label: '市巡一夜', text: '跟着行会巡市，专管「以假乱真」的摊子。你识破了一尊假玉佛，摊主求饶，会长罚他「市口站三日、见客告假」——「鬼市罚人，罚的是脸，不是钱。」', effect: { stat: { xiwei: 4 }, money: 2, trait: { yi: 1 } } },
      { label: '义当一日', text: '行会每月逢七开「义当」，穷人拿旧物当活命钱，死当也赎得回。你坐柜一日，赎回的旧物比收进的多——会长说：「这就是义当的账，越当越有的账。」', effect: { stat: { xiwei: 3 }, trait: { ren: 1 } } },
      { label: '假货当众销毁', text: '行会每月月底当众销毁查获的假货——你抡锤砸了一天假玉器。会长说：「砸的是假货，立的是信。鬼市的灯为什么亮？因为照不出一件假的。」', effect: { stat: { xiwei: 3 }, trait: { yi: 1 } } },
    ],
    annual: [
      '今年官府想给鬼市「立契收税」，会长带着全行在市口摆了一夜摊——摆的全是三十年来的义当账册。官差看完走了：这市收不了税，收的是心。',
      '行会今年验出一批假丹药，追到了源头——是某大派的内门弟子在卖。会长照罚不误：「派大，脸更大。」',
    ],
    grudges: {},
    rule: '叛出鬼市行会者，市门不进——鬼市的黑名单不写字，画一张脸。',
  },
  dengta_si: {
    id: 'dengta_si', name: '沧澜灯塔司', kind: '守门', city: 'canglan', node: 'cl_dengtaya',
    masterNpc: 'cl_shoudeng',
    kaoyanEvent: 'ev_kaoyan_dengta',
    motto: '一盏灯，守一夜海。司里规矩：灯灭之前，人不能睡。',
    gongfa: { id: 'gf_dengta_shouye', name: '守夜功', desc: '司里传下的熬神法。一夜不合眼而心明如镜——守塔人靠它，海也靠它。', level: 1, realm: 'lianqi' },
    secondGongfa: { id: 'gf_dengta_bianfeng', name: '辨风听汛', desc: '老塔长的一双耳朵。风声里听得出三日后有汛——灯塔比船先知道海的事。', level: 2, realm: 'lianqi' },
    duties: [
      { label: '守塔一夜', text: '添油、擦罩、记潮。后半夜起了雾，你在雾里把灯拨到最亮—— offshore 隐隐有一声回应的螺号。「听着了，」守塔老司说，「这就是我们这行的工钱。」', effect: { stat: { xiwei: 4 }, trait: { xin: 1 } } },
      { label: '巡海岸线一日', text: '沿着塔下的海岸走一个来回，捡拾沉船漂来的遗物、补修渔民晒网的桩子。走到最远的礁石，老司指着海图上一处：「三十年前那儿沉过一条船，灯记着呢。」', effect: { stat: { wugongXiuwei: 2 }, trait: { ren: 1 } } },
      { label: '检修灯轮镜组', text: '灯轮的铜镜每月擦一遍、校一次角度。你爬上灯顶干了半天，手腕酸得端不住碗——老司说：「镜子差半分，海上的船就多走半夜的冤枉路。」', effect: { stat: { xiwei: 3 }, flags: { dengLun: true } } },
    ],
    annual: [
      '今年海难是十年最少的一年。塔长把功劳记给「天气」——只有司里的人知道，是新学的辨风听汛，提前三日挂了三次汛旗。',
      '灯塔司今年收了个哑巴学徒。塔长说：「守塔不用嘴——正好。」',
    ],
    grudges: {},
    rule: '叛出灯塔司者，司灯名录除名——海不记仇，但海记得谁没守过夜。',
  },
  nanhai_chuanbang: {
    id: 'nanhai_chuanbang', name: '南海船帮', kind: '海门', city: 'nanhai', node: 'nh_bujidao',
    masterNpc: 'nh_daoyou',
    kaoyanEvent: 'ev_kaoyan_chuanbang',
    motto: '南海浪大，帮里的字就一个：齐。船齐，人齐，心齐。',
    gongfa: { id: 'gf_chuanbang_polang', name: '破浪身法', desc: '帮里在浪尖上讨生活的底子。浪头打来不是躲——是借它的势，从浪缝里过去。', level: 2, realm: 'wudao' },
    secondGongfa: { id: 'gf_chuanbang_zhishi', name: '指汐诀', desc: '帮主的看家本事。看一眼水色就知道潮往哪走——南海的潮，比人心直。', level: 2, realm: 'lianqi' },
    duties: [
      { label: '随帮船走一趟南洋', text: '一去四十天。你经历了风、浪、盗，也经历了帮里分账——分账那天全帮的人把账册摊在甲板上对到半夜，一两银子的出入都要对出来。', effect: { stat: { wugongXiuwei: 4 }, money: 4, trait: { yi: 1 } } },
      { label: '帮渔村修船三日', text: '台风过后的渔村，帮里白修船三天。老渔户送来一筐咸鱼硬塞——帮主收了，转手分给全帮：「记住这个味。我们是吃百家咸鱼的帮。」', effect: { stat: { xiwei: 3 }, trait: { ren: 1 } } },
      { label: '帮众擂台比武', text: '帮里每月摆擂，输了的请全船吃鱼。你赢了三场输了四场——帮主拍拍你的肩：「擂台上输不丢人，记不住怎么输的才丢人。都记着？」', effect: { stat: { wugongXiuwei: 3 }, trait: { hen: 1 } } },
    ],
    annual: [
      '今年帮里和海盗谈成了一桩奇事：划界互不犯，海盗的娃病了，帮里的船照样送药。帮主说：「浪里没有死仇，只有没谈完的事。」',
      '船帮今年的新船下了水，船头不雕虎不雕龙，雕了一株稻穗——帮主说：「我们运的不是货，是人家锅里的一口饭。」',
    ],
    grudges: {},
    rule: '叛出南海船帮者，海路除名——南海的每一片帆都认得叛徒的脸。',
  },
  qundao_yihui: {
    id: 'qundao_yihui', name: '群岛义会', kind: '义门', city: 'qundao', node: 'qd_yihui',
    masterNpc: 'qd_daozhu',
    kaoyanEvent: 'ev_kaoyan_yihui',
    motto: '岛多，心齐。义会的规矩：会众有难，八岛同担。',
    gongfa: { id: 'gf_yihui_xieshou', name: '携手功', desc: '义会的合击底功。一人力薄，两人成桥，八人成城——练它先练「信旁边的人」。', level: 1, realm: 'wudao' },
    secondGongfa: { id: 'gf_yihui_diaozhong', name: '调众诀', desc: '岛主的压箱之学。灾年调八岛之力如调一指——诀窍无他：「平时把人当人。」', level: 2, realm: 'lianqi' },
    duties: [
      { label: '轮值会务一日', text: '今天轮你管账房。义会的账最琐碎：张家的药钱、李家的棺材本、王寡妇的房租……你记到半夜才明白：这就是「义」字的账本，一页都不能少。', effect: { stat: { xiwei: 4 }, trait: { ren: 1 } } },
      { label: '跨岛送信一趟', text: '帮三岛给六岛送急信。你跑了两天水路——信到了，六岛的病疫当天就得了三岛的药方。岛主说：「义会的信比官驿快，因为我们送的不是纸，是命。」', effect: { stat: { wugongXiuwei: 3 }, trait: { yi: 1 } } },
      { label: '八岛轮访', text: '每季轮访一遍八岛，替会众传口信、对账目。你走完八岛晒脱了一层皮——岛主说：「腿上的茧是义会的路引，比什么腰牌都管用。」', effect: { stat: { xiwei: 4 }, money: 1, trait: { ren: 1 } } },
    ],
    annual: [
      '今年台风毁了两岛，八岛的粮船三天内到齐。会主立在码头看着粮卸完，说了一句：「今年会费没白收。」——台下笑倒一片。',
      '义会今年议定：会众通婚，两岛各出一船嫁妆。八岛的风俗，就是这样一年年「齐」起来的。',
    ],
    grudges: {},
    rule: '叛出义会者，八岛同弃——义字头上没有个人。',
  },
  donghuang_xunshan: {
    id: 'donghuang_xunshan', name: '东荒巡山卫', kind: '猎门', city: 'donghuang', node: 'dh_yaoshi',
    masterNpc: 'dh_shibei',
    kaoyanEvent: 'ev_kaoyan_xunshan',
    motto: '妖有妖道，山有山规。卫里的规矩：猎三留一，幼者不猎。',
    gongfa: { id: 'gf_xunshan_zongji', name: '纵迹步', desc: '巡山卫的跟踪步法。妖迹在雪上、泥上、叶尖上——这步法教你「跟着痕迹走，不惊痕迹的主人」。', level: 1, realm: 'wudao' },
    secondGongfa: { id: 'gf_xunshan_yuyao', name: '御妖哨', desc: '卫长的祖传哨法。三长两短，妖闻之退；五短连吹，妖闻之定——御的是「通」，不是「杀」。', level: 2, realm: 'lianqi', mai: 'yao' },
    duties: [
      { label: '巡山七日', text: '七天巡完东段山线，记妖迹、修栈道、给猎户传汛。回来时鞋废了一双——卫长翻着你的巡山簿：「记了三十一处妖迹，一处没猎。好。猎是最后的事。」', effect: { stat: { xiwei: 4 }, money: 2, trait: { xin: 1 } } },
      { label: '救助误陷妖阵的药农', text: '一个药农误闯妖阵，你依着哨法引来巡界妖卒对质——妖卒认出药农是常给妖城送药的，亲自送他出阵。卫长听说后点头：「卫里教的不是打妖，是讲理。理讲得通，妖比人还讲理。」', effect: { stat: { wugongXiuwei: 3 }, trait: { ren: 1 } } },
      { label: '妖城互市当值', text: '每月在界碑集市当值两日，人妖两边的纠纷归巡山卫评理。你断了一件「桃子换盐」的秤头官司——两边都服。卫长说：「评理的先得两头都懂。你做到了。」', effect: { stat: { wuxing: 3 }, trait: { yi: 1 } } },
    ],
    annual: [
      '今年妖山界碑重立，人妖两边各出了一半工钱。碑文是新拟的：「山是我们共有的。」——巡山卫提的字。',
      '卫里今年破了一桩盗猎案，主犯是山外来的富商。罚银三百两，全数给了妖城的化形学堂。',
    ],
    grudges: {},
    rule: '叛出巡山卫者，卫哨除名——山里的妖不认你，山里的猎户也不再救你。',
  },
  ximo_tuodui: {
    id: 'ximo_tuodui', name: '西漠驼队', kind: '商门', city: 'ximo', node: 'xm_xiangshi',
    masterNpc: 'xm_xiangzhu',
    kaoyanEvent: 'ev_kaoyan_tuodui',
    motto: '大漠无路，驼队走过的就是路。队规：水分六份，人人一样。',
    gongfa: { id: 'gf_tuodui_shamo', name: '沙行功', desc: '驼队的走路功。沙地里省力的步法——省下的每一步，都是走出大漠的命。', level: 1, realm: 'wudao' },
    secondGongfa: { id: 'gf_tuodui_xingpan', name: '星盘术', desc: '队长的看家术。白天认沙脊，夜里认星——大漠里活下来的人，都是看天吃饭又不受天摆布的人。', level: 2, realm: 'lianqi' },
    duties: [
      { label: '随队走一趟丝路', text: '往返两月，沙漠把你的脸糙了一层。队里分水时队长把自己那份匀给了病倒的伙计——「队规写着人人一样，没写着队长可以多喝。」', effect: { stat: { wugongXiuwei: 4 }, money: 4, trait: { yi: 1 } } },
      { label: '井站打水三日', text: '丝路上的井站是驼队的命。你打水三日，给八口井都添了新绳——队长说：「井是前人打的，绳是后人接的。丝路就是这么续下来的。」', effect: { stat: { xiwei: 3 }, trait: { ren: 1 } } },
      { label: '井站淘井', text: '丝路每月淘一次井——沙子灌进去的速度比人想的快。你从井底吊上来四十筐沙，井水重新见了亮。队长说：「井清了，路就活着。这活没人看见，井看得见。」', effect: { stat: { xiwei: 3 }, trait: { ren: 1 } } },
    ],
    annual: [
      '今年丝路闹沙匪，驼队联合三支商队结阵而行——匪众围了三天，没敢下手。队长说：「大漠里最大的阵，不是刀阵，是车阵。」',
      '驼队今年带回来两筐西域的葡萄苗，试种在井站边。队长说：路要活，两边的种子都得传。',
    ],
    grudges: {},
    rule: '叛出西漠驼队者，丝路水站不供——大漠对叛徒最狠的不是追杀，是渴。',
  },
  beiyuan_lieMeng: {
    id: 'beiyuan_lieMeng', name: '北原猎盟', kind: '猎门', city: 'beiyuan', node: 'by_xueyuan',
    masterNpc: 'by_lieren',
    kaoyanEvent: 'ev_kaoyan_lieMeng',
    motto: '雪原上猎物养人，人养雪原。盟规：母兽孕中不猎，雪线之上不猎。',
    gongfa: { id: 'gf_lieMeng_fuXue', name: '伏雪诀', desc: '猎盟的雪地蹲守功。伏在雪里半日不动、体温不散——北原的猎手，一半是猎人，一半是雪。', level: 1, realm: 'wudao' },
    secondGongfa: { id: 'gf_lieMeng_shouShan', name: '守山印', desc: '盟主的压箱功。大雪封山时以真气暖一窝幼兽过冬——猎的尽头是养，这是北原最老的话。', level: 2, realm: 'lianqi' },
    duties: [
      { label: '冬猎一季', text: '一季的雪线狩猎。你猎到的每一只，都按盟规留下了一半给狼群过冬——「狼是雪原的巡山人，饿跑了的狼，比兽灾可怕。」', effect: { stat: { wugongXiuwei: 4 }, money: 3 } },
      { label: '护送雪原商队', text: '白毛风突至，你带商队躲进猎盟的地窖，守了两天两夜。出窖时商队要给钱，盟主摆手：「把你们的货带给山那边的村子——这就算账。」', effect: { stat: { xiwei: 4 }, trait: { yi: 1 } } },
      { label: '雪窖储冬粮', text: '入冬前全盟储粮进雪窖。你背了三天冻肉，肩膀压出了血印——盟主掀开窖门点了点数：「多储的那三成，是开春分给猎不够的户头的。记住这数从哪来。」', effect: { stat: { wugongXiuwei: 3 }, money: 1, trait: { yi: 1 } } },
    ],
    annual: [
      '今年雪线下降，盟里破天荒议了「减猎」——猎物少了，人先省着。盟主带头，冬天全家吃了三个月的存粮。',
      '北原猎盟和雪山剑院今年换了帖子——猎户的娃可以送去学剑，剑院的弟子冬天来猎盟学伏雪。',
    ],
    grudges: {},
    rule: '叛出北原猎盟者，盟中地窖不纳——雪原的风，专吹没窝的人。',
  },
  kunwu_kuanghang: {
    id: 'kunwu_kuanghang', name: '昆吾矿工行', kind: '工门', city: 'kunwu', node: 'kw_kuangshi',
    masterNpc: 'kw_kuangshang',
    kaoyanEvent: 'ev_kaoyan_kuanghang',
    motto: '铁矿养剑，剑养江湖——江湖别忘了矿下的人。',
    gongfa: { id: 'gf_kuanghang_zuanYan', name: '凿岩功', desc: '矿行的吃饭功。一锤一个准窝，不伤矿脉——「矿是有命的，糙人凿坏的是子孙的饭碗。」', level: 1, realm: 'wudao' },
    secondGongfa: { id: 'gf_kuanghang_bengDi', name: '辨地听', desc: '行老的保命耳功。耳朵贴着岩壁听三息，就知道顶板结不结实——矿下活到老的人，都有一对「听石头」的耳朵。', level: 2, realm: 'lianqi' },
    duties: [
      { label: '下矿半月', text: '半月的井下工夫。黑、湿、累，可你学会了听石头——「石头比人诚实，它响了，就是真要塌。」出井那天你看着太阳，看了很久。', effect: { stat: { wugongXiuwei: 5 }, money: 3, flags: { xiaKuang: true } } },
      { label: '矿难救护队当值', text: '行里救护队当值一月。真遇上了一次塌方，你跟着老队下去，挖出来三个人——两个活的。老队说：「干我们这行，两个活的，就是好年成。」', effect: { stat: { xiwei: 4 }, trait: { ren: 1 } } },
      { label: '井下支护检修', text: '每旬下井检修一遍支护木。你在黑暗里敲了一天的柱子——「响的换，闷的留。」行老验收时敲得比你快一倍：「这活急不得，也慢不得。你的耳朵，今天又养了一分。」', effect: { stat: { xiwei: 4 }, flags: { zhiHu: true } } },
    ],
    annual: [
      '今年矿行和铸剑山庄签了新约：矿价涨一成，剑价不涨——差额庄里出。行老说：「矿下的人和炉边的人，是一根铁上的两头。」',
      '矿行今年的孤儿学堂新收了十一个娃——都是去年矿难留下的。行规：矿行的税后银，第一笔永远给学堂。',
    ],
    grudges: {},
    rule: '叛出昆吾矿工行者，矿井不纳——矿下的黑暗里，藏着一本记到底的账。',
  },
  linjiang_shuyuanPai: {
    id: 'linjiang_shuyuanPai', name: '临江书院', kind: '文门', city: 'linjiang', node: 'lj_shuyuan',
    masterNpc: 'lj_xiansheng',
    kaoyanEvent: 'ev_kaoyan_shuyuanPai',
    motto: '读书不为官，为「明理」。书院的规矩：学生错，先生领一半。',
    gongfa: { id: 'gf_shuyuan_yangQi', name: '养气诀', desc: '书院的开蒙功。读书养气，气足则神定——江湖人说书生没用，书院的先生让你三天吃不下饭。', level: 1, realm: 'lianqi' },
    secondGongfa: { id: 'gf_shuyuan_shiDao', name: '识道篇', desc: '山长压箱的心法。万卷书读成一页，一页书上只有两个字：「去做。」', level: 2, realm: 'lianqi' },
    duties: [
      { label: '代课三日', text: '山长病了，你代课三日。孩子们问你「侠是什么」，你答：「侠是把别人的事，当自己的事。」——说完自己愣了半天。', effect: { stat: { xiwei: 4 }, stat2: { wuxing: 2 }, trait: { cha: 1 } } },
      { label: '书院藏书楼整书一月', text: '给三万卷书除尘、补页、归架。你补到一本缺了扉页的《山河志》，在夹层里发现前朝书生的批注——整月没白干，你和三百年前的人吵了一架（他错了三处）。', effect: { stat: { gengu: 3 }, flags: { duShu: true } } },
      { label: '书院洒扫', text: '轮值洒扫藏书楼——三万卷书，掸灰、防潮、驱蠹。你扫到第三十天，发现自己能背出三成的书名。山长说：「书认得肯扫它的人。」', effect: { stat: { gengu: 3 }, trait: { xin: 1 } } },
    ],
    annual: [
      '今年书院出了一位解元。山长没摆酒，把那篇制艺贴在照壁上，旁边贴了张纸：「文章四平，问策未通。诸生共勉。」——解元本人看了，回院重读三月。',
      '书院今年开了「夜学」，专收白日做工的孩子。山长说：灯油钱他出——「字是平等的，就看灯往哪儿照。」',
    ],
    grudges: {},
    rule: '叛出临江书院者，书院藏书楼不纳——文脉的账，记三百年。',
  },
  baicao_dujia: {
    id: 'baicao_dujia', name: '百草渡家', kind: '渡门', city: 'baicao', node: 'bc_shidu',
    masterNpc: 'bc_dushi',
    kaoyanEvent: 'ev_kaoyan_dujia',
    motto: '渡口无大小，过河就是客。渡家规矩：雨夜渡人不收钱。',
    gongfa: { id: 'gf_dujia_wenChuan', name: '稳棹功', desc: '渡家的撑船功。一篙一橹要稳——「船上坐着的人家，全指望这一篙的稳。」', level: 1, realm: 'wudao' },
    secondGongfa: { id: 'gf_dujia_duRen', name: '渡人诀', desc: '老渡头的心法。渡船渡的多了就明白：人过河靠船，心过河靠话——撑船的人，两样都得会给。', level: 2, realm: 'lianqi' },
    duties: [
      { label: '渡口当值三日', text: '三天摆渡，你数了数：赶集的、送药的、奔丧的、逃婚的……老渡头说：「渡口是个看尽人间的地方。看多了，手上这篙就稳了。」', effect: { stat: { wugongXiuwei: 3 }, money: 2 } },
      { label: '雨夜救渡', text: '暴雨夜对岸有人喊渡，你撑船过去——是个抱着孩子的母亲，孩子烧得滚烫。你一路把船撑得又快又稳，送到对岸，人家要给钱，你想起规矩：「雨夜渡人，不收钱。」', effect: { stat: { xiwei: 4 }, trait: { ren: 1 } } },
      { label: '渡船小修', text: '每逢初一，把船拖上岸检修——船底的青苔、裂缝、松了的钉，一样样过手。老渡头说：「船不在水里的时候，才看得清水给它留了多少伤。」', effect: { stat: { xiwei: 2 }, trait: { xin: 1 }, flags: { chuanXiu: true } } },
    ],
    annual: [
      '今年渡口翻修，药王谷出的木料，船行出的漆——渡头说：「渡口不是渡家的，是两岸的。」',
      '渡家今年添了条新船，船名是渡口过客们投票取的，叫「再来一碗」——因为船家娘子的面汤太出名。',
    ],
    grudges: {},
    rule: '叛出百草渡家者，渡口无船——河两边的人会记住你，用最不客气的方式。',
  },
};
