// 三期 v3.0：四大边域（东荒妖域/西漠佛国/南疆蛊地/北原大雪山）+ 仙山（昆仑墟/蜀山/蓬莱）+ 深海妖渊。
// 四件套照 02-世界蓝图 §3：城区结构/光景基调/活法/代表际遇。
export const CITIES3 = {
  donghuang: { id: 'donghuang', name: '东荒妖域', entry: 'dh_yaoshi',
    desc: '月色下的旷野，妖气如岚。这里不认皇法，认「规矩」——妖的规矩写在爪牙上，却比皇法还硬。' },
  ximo: { id: 'ximo', name: '西漠佛国', entry: 'xm_xiangshi',
    desc: '白沙如雪，塔铃如泣。两百座佛塔，是用先代高僧的骨殖起的——风过时，满漠都是诵经的呜咽。' },
  nanjiang: { id: 'nanjiang', name: '南疆蛊地', entry: 'nj_bazhai',
    desc: '绿到发黑的瘴雾里，藏着十八峒的人情世故。外人看是毒窝，寨里看是家法。' },
  beiyuan: { id: 'beiyuan', name: '北原大雪山', entry: 'by_xueyuan',
    desc: '白茫一片的雪原尽头，十万柄剑插在山上——风过时，万剑齐鸣。那是天下剑修的魂。' },
  kunlunxu: { id: 'kunlunxu', name: '昆仑墟', entry: 'kx_tianjie',
    desc: '上古仙府的废墟。断墙上还留着神战的剑痕——一万年了，石头还没愈合。' },
  shushan: { id: 'shushan', name: '蜀山', entry: 'ss_shanmen',
    desc: '云海之上的煌煌仙门。正道的体面与代价，都在这云上。' },
  penglai: { id: 'penglai', name: '蓬莱', entry: 'pl_dukou',
    desc: '海外仙山，仙凡在此一线相接。渡劫飞升的最后一程，从这里走。' },
  yuanyuan: { id: 'yuanyuan', name: '深海妖渊', entry: 'yy_shangceng',
    desc: '黑水。越深越黑，越黑越大。海图在此写：至此无忧，再往勿念。' },
};

export const AREAS3 = {
  dh_ye: { id: 'dh_ye', name: '妖域旷野', city: 'donghuang' },
  xm_sha: { id: 'xm_sha', name: '大漠', city: 'ximo' },
  nj_ling: { id: 'nj_ling', name: '瘴林', city: 'nanjiang' },
  by_xue: { id: 'by_xue', name: '雪山', city: 'beiyuan' },
  kx_xu: { id: 'kx_xu', name: '墟中', city: 'kunlunxu' },
  ss_yun: { id: 'ss_yun', name: '云海', city: 'shushan' },
  pl_hai: { id: 'pl_hai', name: '仙山海域', city: 'penglai' },
  yy_shui: { id: 'yy_shui', name: '渊水域', city: 'yuanyuan' },
};

export const NODES3 = {
  // ---------- 东荒妖域 ----------
  dh_yaoshi: { id: 'dh_yaoshi', name: '妖市', city: 'donghuang', area: 'dh_ye',
    desc: '月光下的露天市集。摊主可能是任何东西——卖珠的蚌精、收皮毛的貂妖、看摊的老树。规矩碑立在市口：「以物易物，不收人间银钱。骗市者，逐出东荒。」',
    links: ['dh_wanyao', 'dh_huaxing'], npcs: ['dh_shibei'],
    huatou: ['逛妖市', '跟规矩碑守碑人搭话', '以物易物'], events: [], tags: ['town'],
  },
  dh_wanyao: { id: 'dh_wanyao', name: '万妖山', city: 'donghuang', area: 'dh_ye',
    desc: '层层领地，界碑相望。越往山上走，妖气越沉——山巅妖王的洞府实行「谒见制」，没名帖的，连山门都近不了。',
    links: ['dh_yaoshi'], npcs: ['dh_jiebei'],
    huatou: ['拜谒界碑', '在灵药崖采药', '求见妖王'], events: [], tags: ['wild'],
  },
  dh_huaxing: { id: 'dh_huaxing', name: '化形妖城', city: 'donghuang', area: 'dh_ye',
    desc: '半人半妖混居的市镇。学堂里妖童在学人礼，街上有人拖着尾巴买菜——这座城本身，就是一个关于「何以为人」的故事。',
    links: ['dh_yaoshi'], npcs: ['dh_yao_yi'],
    huatou: ['在学堂外听讲', '看妖医门诊', '逛隐居巷'], events: [], tags: ['town'],
  },
  // ---------- 西漠佛国 ----------
  xm_xiangshi: { id: 'xm_xiangshi', name: '佛国香市', city: 'ximo', area: 'xm_sha',
    desc: '朝圣经济的中心。满街香烛、法器、有故事的脸——「佛度有缘人，也度有钱人」，卖香的这么打趣，功德箱前却从不设门槛。',
    links: ['xm_foguta', 'xm_yisi'], npcs: ['xm_xiangzhu'],
    huatou: ['逛香市', '随朝圣队伍走一段', '打听佛骨塔的规矩'], events: [], tags: ['town'],
  },
  xm_foguta: { id: 'xm_foguta', name: '佛骨塔', city: 'ximo', area: 'xm_sha',
    desc: '两百座塔，塔塔相望。塔林深处是白骨滩——苦行僧在滩上一步一叩。辩经场传来的诘问声，隔着半座漠都听得见。',
    links: ['xm_xiangshi'], npcs: ['xm_kuseng'],
    huatou: ['入塔林参拜', '上白骨滩一试苦行', '去辩经场听经'], events: [], tags: ['temple'],
  },
  xm_yisi: { id: 'xm_yisi', name: '泉眼驿寺', city: 'ximo', area: 'xm_sha',
    desc: '戈壁里的一点绿。寺前一口泉眼，寺后一片菜畦——佛国的「人情」都在驿寺的粥里：商旅挂单，不问来路，只添一双筷。',
    links: ['xm_xiangshi'], npcs: ['xm_zhou_seng'],
    huatou: ['挂单歇脚', '帮僧人挑水', '讨一碗热粥'], events: [], tags: ['temple'],
  },
  // ---------- 南疆蛊地 ----------
  nj_bazhai: { id: 'nj_bazhai', name: '十八峒总寨', city: 'nanjiang', area: 'nj_ling',
    desc: '峒寨依山而建，图腾柱上挂着风干的草药与兽骨。寨老的议事棚里烟雾缭绕——蛊母总寨的权威，写在每一根图腾柱的眼睛里。',
    links: ['nj_zhanglin'], npcs: ['nj_zhai_lao'],
    huatou: ['拜会寨老', '看蛊母总寨', '上祭天台远望'], events: [], tags: ['town'],
  },
  nj_zhanglin: { id: 'nj_zhanglin', name: '瘴林', city: 'nanjiang', area: 'nj_ling',
    desc: '绿到发黑的雾，一层比一层毒。林深处的树上偶尔挂着「药人」——逃奴或自愿试蛊者的下场。寨里的巫医说：进得来出不出，看蛊术深浅，也看心术。',
    links: ['nj_bazhai'], npcs: [],
    huatou: ['浅瘴区采毒', '循着记号救药人', '深入瘴林'], events: [], tags: ['wild'],
  },
  // ---------- 北原大雪山 ----------
  by_xueyuan: { id: 'by_xueyuan', name: '雪原猎场', city: 'beiyuan', area: 'by_xue',
    desc: '白茫一片。猎人木屋的烟是这里唯一的黑。猎的是兽，练的是心——给剑院供皮毛的凡人，活得比谁都硬。',
    links: ['by_jianzhong', 'by_jianyuan'], npcs: ['by_lieren'],
    huatou: ['进木屋烤火', '跟老猎人上山', '打听剑冢的路'], events: [], tags: ['wild'],
  },
  by_jianzhong: { id: 'by_jianzhong', name: '剑冢', city: 'beiyuan', area: 'by_xue',
    desc: '十万柄剑插在雪原上，从山脚一直排到云里。风过时，万剑齐鸣——那声音不像兵器，像千军万马在唱。剑碑林立，碑上名字有浓有淡。守冢人的茅屋在剑林深处，烟囱常年不冒烟。',
    links: ['by_xueyuan'], npcs: ['by_shouzhong'],
    huatou: ['万剑林中谒冢', '读剑碑上的名字', '访守冢人茅屋'], events: [], tags: ['wild'],
  },
  by_jianyuan: { id: 'by_jianyuan', name: '雪山剑院', city: 'beiyuan', area: 'by_xue',
    desc: '雪线之上的清苦门院。剑堂、冰瀑试剑台、藏剑楼依次而上——剑修的规矩，冷得像山顶的石头，也稳得像。',
    links: ['by_xueyuan'], npcs: ['by_jian_shi'],
    huatou: ['观冰瀑试剑', '求入剑院学剑', '登藏剑楼'], events: [], tags: ['town'],
  },
  // ---------- 仙山 ----------
  kx_tianjie: { id: 'kx_tianjie', name: '天阶遗址', city: 'kunlunxu', area: 'kx_xu',
    desc: '上万级石阶通向云中，断了的一截悬在雾里。阶旁断墙上的剑痕深可容掌——上古神战的现场，一万年了，石头还没愈合。',
    links: ['kx_yuxu'], npcs: ['kx_shouxu'],
    huatou: ['登天阶', '听守墟人说古', '临摹断墙剑痕'], events: [], tags: ['wild'],
  },
  kx_yuxu: { id: 'kx_yuxu', name: '玉虚宫残殿', city: 'kunlunxu', area: 'kx_xu',
    desc: '半座宫殿悬在云上，半座沉在雾里。殿中香火未断——守墟人说，这香是「替走不到头的人点的」。',
    links: ['kx_tianjie'], npcs: [],
    huatou: ['在残殿静坐', '探殿后藏卷处', '给长明灯添香油'], events: [], tags: ['wild', 'lingdi'],
  },
  ss_shanmen: { id: 'ss_shanmen', name: '蜀山山门', city: 'shushan', area: 'ss_yun',
    desc: '牌坊立于云海之上，匾额三个字被云洗得发亮。入山门先照壁——壁上刻着历代「下山了因果」的弟子名。正道的体面，从一面照壁开始。',
    links: ['ss_jianzheng'], npcs: ['ss_zhishi'],
    huatou: ['观照壁', '求入山门', '问藏经楼的规矩'], events: [], tags: ['town'],
  },
  ss_jianzheng: { id: 'ss_jianzheng', name: '剑阁', city: 'shushan', area: 'ss_yun',
    desc: '万剑朝宗——阁中悬剑千柄，皆朝一个方向微倾，像在拜。丹殿的炉火味从隔壁飘来，罪徒崖的风从更远处吹来。',
    links: ['ss_shanmen'], npcs: ['ss_jian_ge'],
    huatou: ['观万剑朝宗', '去丹殿求丹', '上罪徒崖看看'], events: [], tags: ['wild', 'lingdi'],
  },
  pl_dukou: { id: 'pl_dukou', name: '蓬莱渡口', city: 'penglai', area: 'pl_hai',
    desc: '凡船止步处。渡口一根系缆石桩被历代渡船磨出深槽。守渡人坐在石桩上，看每一个上岸的人，也看每一个没回来的人。',
    links: ['pl_xianshi', 'pl_jiefeng'], npcs: ['pl_shoudu'],
    huatou: ['同守渡人闲坐', '看渡船靠岸', '打听劫峰的路'], events: [], tags: ['town'],
  },
  pl_xianshi: { id: 'pl_xianshi', name: '仙市', city: 'penglai', area: 'pl_hai',
    desc: '仙凡交易的唯一合法点。摊上的东西说不清年代，买家说不清来历——市口立着牌子：「最后一桩买卖，想清楚了再成交。」',
    links: ['pl_dukou'], npcs: ['pl_shi_ya'],
    huatou: ['逛仙市', '同仙市牙人搭话', '看看那块牌子'], events: [], tags: ['town'],
  },
  pl_jiefeng: { id: 'pl_jiefeng', name: '劫峰', city: 'penglai', area: 'pl_hai',
    desc: '蓬莱最高处。峰顶常年盘着云——那不是云，是历代渡劫者留下的「未散的雷」。上来的人都抱着同一个念头：此生走到头了，就看最后一步。',
    links: ['pl_dukou'], npcs: [],
    huatou: ['在峰脚观礼', '登峰备战', '于峰顶静坐聚气'], events: [], tags: ['wild', 'lingdi'],
  },
  // ---------- 深海妖渊（三期） ----------
  yy_shangceng: { id: 'yy_shangceng', name: '妖渊上层渔场', city: 'yuanyuan', area: 'yy_shui',
    desc: '黑水从这里开始。渔场的鱼大得出奇，渔民的眼睛亮得出奇——他们不谈论深处的动静，一个字都不。',
    links: ['yy_zhongceng'], npcs: ['yy_yumin'],
    huatou: ['随渔船下网', '问渔民渊下的事', '在船头观察黑水'], events: [], tags: ['wild', 'undersea'],
  },
  yy_zhongceng: { id: 'yy_zhongceng', name: '妖域水域', city: 'yuanyuan', area: 'yy_shui',
    desc: '光到这里就折断了。水压如山，妖影如楼——传说坠海的仙山碎片就沉在这一层，夜里有微光，像谁在海底点了一盏灯。',
    links: ['yy_shangceng'], npcs: [],
    huatou: ['循微光下探', '猎渊中妖', '原路上浮'], events: [], tags: ['wild', 'undersea'],
  },
};

export const NPCS3 = {
  dh_shibei: { id: 'dh_shibei', name: '守碑人', aliases: ['守碑人', '碑守'], city: 'donghuang',
    desc: '一只成了精的老龟，背甲上刻满了市规。他在规矩碑下坐了三百年，看过来的「人」比看过的月亮多。',
    zhishi: [
      { keys: ['规矩', '市', '易'], answer: '妖市三规：不欺小、不夺爱、不问真名。真名是妖的命——拿真名换宝的，要么是傻子，要么是买命的。' },
      { keys: ['妖王', '万妖山', '谒见'], answer: '谒见妖王要「名帖」。名帖不是纸——是你在这片山里做下的事。好事坏事，都算。' },
      { keys: ['化形', '妖城', '人'], answer: '（他慢慢地说）化形易，化心难。城里那些学人过日子的娃娃——他们比人间许多人都像人。' },
    ],
    greeting: '（他掀开眼皮——那是一双很老很老的眼睛。）客人是来「易」，还是来「问」？', personality: '老而弥明' },
  dh_jiebei: { id: 'dh_jiebei', name: '界碑妖卒', aliases: ['界碑妖卒', '妖卒'], city: 'donghuang',
    desc: '狼形妖，半化形，巡着万妖山的界碑。他对自己领主的忠心，写在每次过界碑时的低头里。',
    zhishi: [
      { keys: ['界碑', '领地', '越界'], answer: '界碑以内，客随主便。越界一步——（他咧嘴，露出半口白牙）就随「主」便了。' },
      { keys: ['妖王', '寿', '谒见'], answer: '王上了年纪。这话题到此为止——再多问，你就在「话题以内」了。' },
      { keys: ['灵药崖', '采药', '药'], answer: '灵药崖的药，采一株留一株——妖界的规矩，跟你们猎户的「打三留一」是一个道理。山养妖，妖养山。' },
    ],
    greeting: '（他绕着你走了一圈，嗅了嗅。）生人。去哪儿，报个准数。', personality: '警惕而直' },
  dh_yao_yi: { id: 'dh_yao_yi', name: '妖医', aliases: ['妖医', '大夫'], city: 'donghuang',
    desc: '化形五百年的白泽后裔，在妖城开诊。医人医妖一视同仁——他说：「脉是一个脉，心是一颗心，分什么妖人。」',
    zhishi: [
      { keys: ['病', '医', '诊'], answer: '（搭脉）……气亏。你不是妖，可你身上的气「杂」——练过不止一门的路子？（他摇头）杂气伤身，择一而终。' },
      { keys: ['学堂', '妖童', '学'], answer: '娃娃们学「礼」学得辛苦——尾巴藏不住，就学怎么「坐」。你说可笑？（他笑）可笑，也可敬。' },
      { keys: ['隐居巷', '原形', '藏'], answer: '巷里住的老妖，大半是「不愿被看见」的。不是怕——是累了。你路过时脚步轻些。' },
    ],
    greeting: '（他头也不抬）坐下，伸手。哦——客人不是来看病的？那坐坐也行，茶在炉上。', personality: '温和通透' },
  xm_xiangzhu: { id: 'xm_xiangzhu', name: '香市主事', aliases: ['香市主事', '主事'], city: 'ximo',
    desc: '早年是走漠的商人，一场大病后在佛前许愿，病愈后留下来管香市。他算账极精——可功德箱的钥匙，三十年没对过账。',
    zhishi: [
      { keys: ['香', '买', '市'], answer: '上塔林的香要「净手」——不是规矩，是敬意。塔里躺着的前辈，生前都跟你我一样，爱干净。' },
      { keys: ['佛骨塔', '白骨滩', '苦行'], answer: '白骨滩的苦行，不劝——去了的，是「还」；回不来的，是「往」。都好。' },
      { keys: ['朝圣', '队伍', '人'], answer: '（他压低声音）今年的队伍里有几号人，眼神不对——朝圣的队伍，鱼龙混杂。你若同行，夜里看好自己的包袱。' },
    ],
    greeting: '客人上香还是购物？上香东边请，购物——（他一笑）您已经在了。', personality: '精明而诚' },
  xm_kuseng: { id: 'xm_kuseng', name: '苦行僧', aliases: ['苦行僧', '僧人'], city: 'ximo',
    desc: '白骨滩上叩长头的僧人。他的额头有一层厚茧，茧上又有旧疤——他拜的不是塔，是塔下埋的「自己走过的路」。',
    zhishi: [
      { keys: ['苦行', '拜', '白骨滩'], answer: '滩上一步一叩，叩的不是苦——是「慢」。人心快了一辈子，总得有地方慢下来。' },
      { keys: ['舍利', '炼体', '修'], answer: '舍利是「火候」，不是宝贝。佛修练到极处，一身业障烧成一粒光——你要问怎么练？（他合十）先学会「烧得心甘」。' },
      { keys: ['辩经', '经', '佛'], answer: '辩经场上输赢不重要——重要的你「输得服气」。服气那一刻，胜过十年苦读。' },
    ],
    greeting: '（他停下叩拜，直起身，合十一礼。）施主自远方来，先喝水。', personality: '枯而弥坚' },
  xm_zhou_seng: { id: 'xm_zhou_seng', name: '粥僧', aliases: ['粥僧', '施粥僧人'], city: 'ximo',
    desc: '驿寺里施粥的老僧，一把白胡子，一口大锅。他给每个过路人盛粥，盛得一样满——「佛国的门，从胃开始进」。',
    zhishi: [
      { keys: ['粥', '挂单', '歇'], answer: '粥管够，房管住——就一样，晨钟要起。起不来的，不是佛的客，是路的客，也管。' },
      { keys: ['漠', '路', '过'], answer: '（他指泉眼）从这里到佛骨塔，两日；到南边绿洲，三日。记住：莫贪路——大漠里，「快」死得比「慢」快。' },
      { keys: ['古经', '石窟', '经'], answer: '（他盛粥的手停了停）石窟寺的老经……懂的人都懂，不懂的人说了也不懂。你要真问——去帮抄经人抄三个月，再问。' },
    ],
    greeting: '（他舀起一勺粥）新熬的。喝吗？——不喝也坐下歇歇，漠上的风不认人。', personality: '朴而有光' },
  nj_zhai_lao: { id: 'nj_zhai_lao', name: '寨老', aliases: ['寨老'], city: 'nanjiang',
    desc: '十八峒总寨的寨老，五十年的蛊母传人。她看人的方式很直接——先看眼睛，再看手，最后看你的「名字」里有没有鬼。',
    zhishi: [
      { keys: ['蛊', '蛊母', '养'], answer: '蛊是「债」。你喂它血，它替你办事——账越欠越深。想学蛊？（她盯着你）先想清楚：你还不还得起。' },
      { keys: ['瘴林', '毒', '深'], answer: '瘴林三层：一层走商，二层采毒，三层——三层进去了就是「林子的人」。寨里不救三层的人，不是狠，是救不起。' },
      { keys: ['禁地', '药人', '救'], answer: '（她叹气）药人是「自愿的债」。你要救——带他们出来，寨里给「净身盅」解毒。但往后的日子，是他们的，也是你的。' },
    ],
    greeting: '（她放下手里的蛊盅，先看你的眼睛，再看你的手。）外客。说事。', personality: '威而不厉' },
  by_lieren: { id: 'by_lieren', name: '老猎人', aliases: ['老猎人', '猎人'], city: 'beiyuan',
    desc: '雪原上打了四十年猎，给剑院供了四十年皮毛。他见过剑冢万剑齐鸣的场面——「那一回，我的狗跪了。我差点也跪了。」',
    zhishi: [
      { keys: ['剑冢', '万剑', '路'], answer: '从这儿往北，过风雪隘口就是。记住：冢前莫喧哗——那十万柄剑「听着」呢。' },
      { keys: ['白狼王', '兽', '传说'], answer: '（他往火堆里添了根柴）白狼王是真的。我见过它三次，三次它都没吃我——（他看着火）第四次，我给它带壶酒。' },
      { keys: ['雪崩', '隘口', '险'], answer: '隘口的风雪看「云旗」——峰顶的云往东飘，能走；往西飘，就地挖雪窝。这不是猎人的规矩，是山间的规矩。' },
    ],
    greeting: '（他抬了抬下巴）外乡人。烤火随便——柴钱记着，下山时给剑院捎句话就行。', personality: '冷面热心' },
  by_shouzhong: { id: 'by_shouzhong', name: '剑冢守冢人', aliases: ['守冢人', '守冢'], city: 'beiyuan',
    desc: '雪山剑冢的守冢人。没人知道他守了多少年——他的茅屋不冒烟，可屋里永远有热茶。他给「走到头」的剑守门，也给「走不到头」的人指路。',
    zhishi: [
      { keys: ['剑', '冢', '万剑'], answer: '（他望着万剑林）每一柄剑，都是一个「没走完」的人。剑鸣是他们在「说话」——你听懂了，就替他们活一段。' },
      { keys: ['剑碑', '留名', '悟'], answer: '剑碑留名，不是「刻上去」——是你悟到那一步，名字自己「浮出来」。急着留名的，碑都不收。' },
      { keys: ['剑院', '学剑', '拜山'], answer: '剑院是「正路」，冢是「归路」。你要学剑，去剑院；你要问剑——（他指指万剑林）他们教你。' },
    ],
    greeting: '（茶已经凉了，他还是给你倒了。）来了。坐。——慢点喝，雪水寒。', personality: '守静待归' },
  by_jian_shi: { id: 'by_jian_shi', name: '剑院执剑', aliases: ['执剑', '剑院执剑'], city: 'beiyuan',
    desc: '雪山剑院的执法长老。他一生收徒只看一件事——「你拔剑的时候，心里装着什么」。',
    zhishi: [
      { keys: ['学剑', '拜山', '入门'], answer: '剑院收徒，不问出身，只问「拔剑的缘由」。为了护人，来。为了赢，也来——输几年就明白了。为了恨——（他摇头）恨练不出好剑，练得出凶器。' },
      { keys: ['冰瀑', '试剑', '台'], answer: '冰瀑试剑台，试的不是招——是「稳」。冰面上站不稳的人，人生也站不稳。' },
      { keys: ['剑阵', '护山', '下山'], answer: '学成下山那天，山门会问你一句话：「你的因果清了没有？」清了，走；没清——（他看着你）回来清。剑院的门，一直开着。' },
    ],
    greeting: '（他没停下手里的剑，只侧了侧身，让出半个试剑台。）上来。还是说话？', personality: '冷正无私' },
  kx_shouxu: { id: 'kx_shouxu', name: '守墟人', aliases: ['守墟人'], city: 'kunlunxu',
    desc: '昆仑墟的守墟人，自称「看门的」——门里是上古仙府，门外是等了一万年也等不来的「有缘人」。他不着急。他有的是时间。',
    zhishi: [
      { keys: ['天阶', '墟', '仙府'], answer: '天阶一万级，走上去的人不少，走「到」的人没有——不是阶太高，是心里太重。空着手来，才走得动。' },
      { keys: ['剑痕', '神战', '断墙'], answer: '那一剑，把「旧天地」劈成了新天地。你摸摸看——（他让你摸）石头到现在还热着。一万年了。' },
      { keys: ['悟道', '道', '传承'], answer: '传承不在殿里，在你身上。（他指你的心口）这里空了，道才进得来。守墟人只是个看门的——门，一直开着。' },
    ],
    greeting: '（他拨着长明灯的灯芯，头也不抬。）来了？随便坐。茶是自己倒——这儿的规矩，自己动手，心才诚。', personality: '旷达守一' },
  ss_zhishi: { id: 'ss_zhishi', name: '蜀山知客', aliases: ['知客', '知客道人'], city: 'shushan',
    desc: '蜀山山门的知客道人，见过太多「来求道」的年轻人。他劝退的比收下的多——「蜀山不缺人，缺的是能下山的人」。',
    zhishi: [
      { keys: ['入门', '拜山', '考'], answer: '入门大考三关：心关、剑关、因果关。前两关考的是本事，第三关——（他指照壁）考的是「下山的本事」。上得来下不去的，这山上太多了。' },
      { keys: ['藏经楼', '经', '书'], answer: '藏经楼的书随便看——除了顶层。顶层那几卷，是「以业换页」：你做多少善举，换看多少页。楼里的账，比人间书店还清。' },
      { keys: ['罪徒崖', '旧案', '罚'], answer: '罪徒崖的风大。去那儿思过的弟子，回来都不太一样——有的更好了，有的……（他顿了顿）崖底埋着几个「没想通」的。莫学他们。' },
    ],
    greeting: '（他拂尘一摆）客从何来，往何处去？——蜀山虽大，两条路：上山，下山。', personality: '清正有节' },
  ss_jian_ge: { id: 'ss_jian_ge', name: '剑阁长老', aliases: ['剑阁长老', '长老'], city: 'shushan',
    desc: '蜀山剑阁的守阁长老。他一生只做三件事：擦剑、看书、看着万剑「朝宗」。他说那些剑「比人诚实」。',
    zhishi: [
      { keys: ['万剑', '朝宗', '阁'], answer: '（他望着悬剑）这些剑都认一个「宗」字——宗是「本源」。剑出千般变化，落到根上就一个字：「直」。' },
      { keys: ['丹', '丹殿', '求'], answer: '丹殿求丹，不收钱——收「愿」。求长生的人给长生的丹，求护人的给护人的丹。你要什么，丹殿看得比你说得准。' },
      { keys: ['正道', '魔', '五脉'], answer: '正道魔道，谱系有别，根上无别——都是「问道」。差别在：正道绕着心魔走，魔道踩着心魔过。走法不同，摔的跤一样疼。' },
    ],
    greeting: '（他不回头）看剑可以，莫出声——它们「说话」呢。', personality: '守拙藏锋' },
  pl_shoudu: { id: 'pl_shoudu', name: '守渡人', aliases: ['守渡人'], city: 'penglai',
    desc: '蓬莱渡口的守渡人，坐着看了一切的开头和结尾。他说自己的活是「给走到头的人守门」——语气平常得像在说看渡船。',
    zhishi: [
      { keys: ['渡', '劫', '飞升'], answer: '渡劫在劫峰，不在渡口。（他指指山上的云）上去的人我不送——「送」字太重。我在这里，就是让他们敢上去。' },
      { keys: ['仙市', '买卖', '交易'], answer: '仙市买东西，用「念想」付账——最舍不得的那个念想。别问为什么。仙凡两界的规矩，谁定的，谁也说不清了。' },
      { keys: ['归墟', '航路', '海'], answer: '归墟是「海的路尽头」。船到不了，人去得了——去的方式，不是坐船。（他一笑）到了你自然知道，现在说了你也不懂。' },
    ],
    greeting: '（他看着海，没看你。）来了。坐。等船的，等人的，等自己的——渡口都收。', personality: '静水流深' },
  pl_shi_ya: { id: 'pl_shi_ya', name: '仙市牙人', aliases: ['仙市牙人', '牙人'], city: 'penglai',
    desc: '仙市唯一的牙人，成交的规矩只有一条：「最后一桩买卖，想清楚了再成交。」他从不催客——他有的是耐心，客人的念想跑不了。',
    zhishi: [
      { keys: ['买', '卖', '货'], answer: '仙市的货不认钱——认「念想」。你最舍不得什么，就能换什么。（他压低声音）所以最贵的东西，都是客人「哭着走的」那几桩。' },
      { keys: ['牌子', '规矩', '最后一桩'], answer: '市口那块牌子？老辈传的。意思是：成交前，把你这个人「称一称」——称过了还想要，那就买。称完不想了——恭喜，你省下的东西比货贵。' },
      { keys: ['仙', '飞升', '渡劫'], answer: '（他收拾着摊子）飞升的人，最后都来我这儿「清仓」——一生的东西，一件一件卖。卖到最后剩什么，什么就跟你上劫峰。' },
    ],
    greeting: '（他给你让出摊前最好的位置。）看看？不急——仙市三百天，天天开门。', personality: '洞悉人情' },
  yy_yumin: { id: 'yy_yumin', name: '渊边渔民', aliases: ['渊边渔民', '渔民'], city: 'yuanyuan',
    desc: '在妖渊上层渔场讨生活的渔民。他们的船小，网密，规矩大——「网住会说话的，放」是祖训。他们的眼睛很亮，嘴很紧。',
    zhishi: [
      { keys: ['渊', '深', '下'], answer: '（他摇头，朝黑水努努嘴）上头是我们讨生活的地方。再往下——（他比了个「停」的手势）祖训：网放三层，人不放第四层。' },
      { keys: ['妖', '网', '祖训'], answer: '网住会说话的，放——祖宗传的。去年网住个会哭的，全船人跪着送它下水。（他低声）它哭着说「谢谢」。' },
      { keys: ['灯', '碎片', '仙山'], answer: '（他的手抖了一下）夜里的光？……你听见就当我没说。老辈人说那是「山上掉下来的东西」在找路。找了一千年了。' },
    ],
    greeting: '（他压着嗓子）客人，下层别去。——我这话，一年说三百遍，听的三遍。', personality: '谨小慎微' },
};
