// 二期 v2.0：三镇（百草坞/沧澜澳/昆吾镇）+ 海洋三区（东海群岛/海底龙宫遗迹/南海商路）。
// 结构与 world.js 一致，尾部 Object.assign 合入。
export const CITIES2 = {
  baicao:  { id: 'baicao',  name: '百草坞', entry: 'bc_yaomen',
    desc: '药谷山镇。四季药香，晨雾漫坞——山民说这里的雾都带药性，吸一口，咳都能压三分。' },
  canglan: { id: 'canglan', name: '沧澜澳', entry: 'cl_aogang',
    desc: '东海渔港，陆地的尽头。咸腥的风、成排的帆、灯塔崖上长明的那盏灯——出海的人，先给它磕个头。' },
  kunwu:   { id: 'kunwu',   name: '昆吾镇', entry: 'kw_jianshan',
    desc: '铸剑山镇。镇子不大，锤声不停——百年了，炉火没熄过。剑客们说：好剑认火，火认人。' },
  qundao:  { id: 'qundao',  name: '东海群岛', entry: 'qd_yucun',
    desc: '星罗棋布的咸腥世界。岛与岛之间，船就是命。老渔民说：看那最高的崖——天晴的时候，有人说能看见仙山。' },
  longgong:{ id: 'longgong', name: '海底龙宫遗迹', entry: 'lg_gongmen',
    desc: '沉在海底的辉煌。宫门倾颓，龙骨成廊——水是静的，光是从上面漏下来的，绿得发蓝。' },
  nanhai:  { id: 'nanhai',  name: '南海商路', entry: 'nh_bujidao',
    desc: '帆影与季风的世界。海图在此写：至此无忧，再往勿念——可每年还是有人往深处去。' },
};

export const AREAS2 = {
  bc_yaogu:  { id: 'bc_yaogu',  name: '药谷', city: 'baicao' },
  cl_aogang: { id: 'cl_aogang', name: '澳港', city: 'canglan' },
  kw_shan:   { id: 'kw_shan',   name: '铸剑山', city: 'kunwu' },
  qd_haiyu:  { id: 'qd_haiyu',  name: '群岛海域', city: 'qundao' },
  lg_haidi:  { id: 'lg_haidi',  name: '海底', city: 'longgong' },
  nh_hailu:  { id: 'nh_hailu',  name: '季风航路', city: 'nanhai' },
};

export const NODES2 = {
  // ---------- 百草坞 ----------
  bc_yaomen: { id: 'bc_yaomen', name: '入坞山门', city: 'baicao', area: 'bc_yaogu',
    desc: '山道两侧药田层叠，雾气里全是苦香。石坊上刻着"百草坞"三个字，字缝里塞满经年的药渣——坞里人说，那是"药魂归山"。',
    links: ['bc_yaoshi', 'bc_yaotian'], npcs: ['bc_daoyao_ren'],
    huatou: ['跟采药人进坞', '闻闻雾里的药香', '问路去药市'], events: [], tags: ['town'],
  },
  bc_yaoshi: { id: 'bc_yaoshi', name: '药市大街', city: 'baicao', area: 'bc_yaogu',
    desc: '一条街的药香。铺子门口挂着成串的干药，牙人扯着嗓子报价——"上好的七叶胆！陈年的茯苓！"讨价还价的声音，比药香还冲。',
    links: ['bc_yaomen', 'bc_yaowangmiao', 'bc_kezhan', 'bc_shidu'], npcs: ['bc_yaren'],
    huatou: ['逛药市', '跟药市牙人搭话', '打听稀罕药材', '去采药人客栈'], events: ['ev_bc_yaoshi_qie'], tags: ['town'],
  },
  bc_yaowangmiao: { id: 'bc_yaowangmiao', name: '药王庙', city: 'baicao', area: 'bc_yaogu',
    desc: '坞里最气派的庙。药王像前常年摆着还愿的干药——一把一把，全是活人命换回来的谢礼。庙祝在侧面晒药，翻动的声音沙沙的。',
    links: ['bc_yaoshi', 'bc_yaotian'], npcs: ['bc_miaozhu'],
    huatou: ['拜药王', '帮庙祝晒药', '求医问药'], events: ['ev_bc_yaowang_huan'], tags: ['temple'],
  },
  bc_yaotian: { id: 'bc_yaotian', name: '山谷药田', city: 'baicao', area: 'bc_yaogu',
    desc: '整条山谷的药田顺着山势铺下去，雾在田垄间流。田里立着草人——不是为了吓鸟，坞里人不肯说为了吓什么。',
    links: ['bc_yaomen', 'bc_yaoshi', 'bc_yaowangmiao'], npcs: ['bc_tianhu'],
    huatou: ['帮忙侍弄药田', '打听药田的传闻', '在田埂上打坐'], events: ['ev_bc_yaotian_jing'], tags: ['wild'],
  },
  bc_shidu: { id: 'bc_shidu', name: '试毒巷', city: 'baicao', area: 'bc_yaogu',
    desc: '巷子窄，光少，门都关着。墙上钉着一块牌子：非请莫入。可门口的竹凳上永远坐着几个人——他们在等"活儿"。药香到这儿就变了味，发苦，发麻。',
    links: ['bc_yaoshi'], npcs: ['bc_dushi'],
    huatou: ['在巷口坐下', '向毒师讨教', '接试毒的活计'], events: ['ev_bc_shidu_huo'], tags: ['slum'],
  },
  bc_kezhan: { id: 'bc_kezhan', name: '采药人客栈', city: 'baicao', area: 'bc_yaogu',
    desc: '客栈的房梁上挂满了各国药商的木牌。掌柜的同时是医师、是保人、是消息贩子——在这儿住店的，一半是来卖药的，一半是来卖命的。',
    links: ['bc_yaoshi'], npcs: ['bc_zhanggui'],
    huatou: ['住店歇脚', '听药商们闲谈', '向掌柜打听行情'], events: [], tags: ['town'],
  },

  // ---------- 沧澜澳 ----------
  cl_aogang: { id: 'cl_aogang', name: '澳港码头', city: 'canglan', area: 'cl_aogang',
    desc: '成排的桅杆像冬天的树林。码头工扛着货在跳板上跑，号子一声接一声——浪打上来，号子就更高一分。海风里全是咸腥和鱼鳞的光。',
    links: ['cl_yushi', 'cl_chuanwu', 'cl_huozhan'], npcs: ['cl_laoban'],
    huatou: ['看船队进港', '跟码头老班头搭话', '打听出海的门路'], events: [], tags: ['town'],
  },
  cl_yushi: { id: 'cl_yushi', name: '鱼市', city: 'canglan', area: 'cl_aogang',
    desc: '天不亮就开市，晌午就散。地上永远湿漉漉的，鱼贩子的吆喝带着海腥气——今日的渔获旺不旺，看鱼市人的脸色就知道。',
    links: ['cl_aogang', 'cl_haishenmiao'], npcs: ['cl_yufan'],
    huatou: ['逛鱼市', '买条鲜鱼', '听渔家讲海上的事'], events: ['ev_cl_yushi_yi'], tags: ['town'],
  },
  cl_haishenmiao: { id: 'cl_haishenmiao', name: '海神庙', city: 'canglan', area: 'cl_aogang',
    desc: '庙是拿沉船的木料修的，梁上还带着旧船的漆。神像的脸被香火熏得乌黑，看不清表情——渔家说，海神不需要表情，海自己会说话。',
    links: ['cl_yushi', 'cl_dengtaya'], npcs: ['cl_miaozhu'],
    huatou: ['给海神上香', '求老庙祝解签', '听庙祝讲古'], events: ['ev_cl_haishen_qi'], tags: ['temple'],
  },
  cl_chuanwu: { id: 'cl_chuanwu', name: '船坞', city: 'canglan', area: 'cl_aogang',
    desc: '新船的骨架立在坞里，像巨兽的肋骨。刨花的清香混着桐油的味——造船的师傅们不苟言笑，他们说船是海里唯一靠得住的"伙伴"。',
    links: ['cl_aogang'], npcs: ['cl_chuanshi'],
    huatou: ['看造船', '向船师请教水性', '打听修补海船的价钱'], events: [], tags: ['town'],
  },
  cl_huozhan: { id: 'cl_huozhan', name: '番商货栈', city: 'canglan', area: 'cl_aogang',
    desc: '栈里堆着异域的货：香料、宝石、说不出名字的干货。番商们皮肤黝黑，说官话带着古怪的调子——他们卖货，也收货，收的是"海里捞上来的东西"。',
    links: ['cl_aogang'], npcs: ['cl_fanshang'],
    huatou: ['逛货栈', '跟番商搭话', '卖海里捞的东西', '打听南海商路'], events: ['ev_cl_huozhan_yiwu'], tags: ['town'],
  },
  cl_dengtaya: { id: 'cl_dengtaya', name: '灯塔崖', city: 'canglan', area: 'cl_aogang',
    desc: '崖高百尺，塔顶的灯彻夜不熄。守灯人一年只下一回崖。崖下是海，再远处是天——老人们说，天海相接的那条线，就是"人间"的最后一笔。',
    links: ['cl_haishenmiao'], npcs: ['cl_shoudeng'],
    huatou: ['登塔看海', '跟守灯人说说话', '在崖边眺望远方'], events: ['ev_cl_dengta_xianying'], tags: ['wild'],
  },

  // ---------- 昆吾镇 ----------
  kw_jianshan: { id: 'kw_jianshan', name: '剑山道', city: 'kunwu', area: 'kw_shan',
    desc: '山道两旁全是矿石的碎光。运矿的骡队叮当作响，越往镇里走，锤声越密——像整座山在打铁。',
    links: ['kw_jianlu', 'kw_kuangshi'], npcs: ['kw_kuanggong'],
    huatou: ['跟矿队进镇', '捡块矿石看看', '问路去剑炉街'], events: [], tags: ['town'],
  },
  kw_jianlu: { id: 'kw_jianlu', name: '剑炉街', city: 'kunwu', area: 'kw_shan',
    desc: '一条街全是炉子。风箱声、锤声、淬火的滋滋声混成一片，白汽从各家门里涌出来。街中央那座老炉的火，据说百年没熄过。',
    links: ['kw_jianshan', 'kw_gongfang', 'kw_kuangshi'], npcs: ['kw_laojiang'],
    huatou: ['看铸剑', '请老师傅掌眼', '打听炼器的门路', '访问铸剑世家'], events: ['ev_kw_jianlu_shixin'], tags: ['town'],
  },
  kw_kuangshi: { id: 'kw_kuangshi', name: '矿石市', city: 'kunwu', area: 'kw_shan',
    desc: '满地碎光。矿工们把各色矿石摆开，吆喝声此起彼伏——"看这纹！这是龙纹铁！""星髓！真星髓！"十句里九句是吹，可真东西，就在那九句里藏着。',
    links: ['kw_jianshan', 'kw_jianlu'], npcs: ['kw_kuangshang'],
    huatou: ['逛矿石市', '买块矿石', '听矿工讲山里的传说'], events: [], tags: ['town'],
  },
  kw_gongfang: { id: 'kw_gongfang', name: '铸剑世家工坊', city: 'kunwu', area: 'kw_shan',
    desc: '高墙深院，门口的石狮子嘴里衔着剑。门房拦人，可院墙里传出的锤声，比外头的炉子都沉——世家锻的剑，从不摆上市。',
    links: ['kw_jianlu', 'kw_jianzhong'], npcs: ['kw_shijia_zhu'],
    huatou: ['求见世家主', '投帖拜师', '打听世家的规矩'], events: [], tags: ['town'],
  },
  kw_jianzhong: { id: 'kw_jianzhong', name: '剑冢下院', city: 'kunwu', area: 'kw_shan',
    desc: '山坡上一片坟茔，埋的全是剑。断的、锈的、主人战死的——剑冢不留尸，只留剑。守冢人扫着落叶，扫帚过处，坟头的草纹丝不动。',
    links: ['kw_gongfang'], npcs: ['kw_shouzhong'],
    huatou: ['拜谒剑冢', '跟守冢人搭话', '给无名剑坟上一炷香'], events: ['ev_kw_jianzhong_ming'], tags: ['wild'],
  },

  // ---------- 东海群岛 ----------
  qd_yucun: { id: 'qd_yucun', name: '岛链渔村', city: 'qundao', area: 'qd_haiyu',
    desc: '渔村建在礁盘上，屋子拿沉船板搭的，风一过满村吱呀。村口的滩上晒着渔网，孩子们光着脚追浪——他们的船就是命，命就是船。',
    links: ['qd_yihui', 'qd_wangxianya'], npcs: ['cl_yumin'],
    huatou: ['在渔村歇脚', '跟渔民学看潮信', '打听望仙崖的传说'], events: ['ev_qd_yucun_chao'], tags: ['town'],
  },
  qd_yihui: { id: 'qd_yihui', name: '岛主议会', city: 'qundao', area: 'qd_haiyu',
    desc: '议会设在最大的岛上，是拿整条巨船的龙骨搭的堂。岛主们吵吵嚷嚷——海盟松散，吵架就是他们的议事。堂外拴着各岛的船，船头雕纹各不相同。',
    links: ['qd_yucun'], npcs: ['qd_daozhu'],
    huatou: ['旁听岛主议事', '递名帖拜会岛主', '接海盟的活计'], events: [], tags: ['town'],
  },
  qd_wangxianya: { id: 'qd_wangxianya', name: '望仙崖', city: 'qundao', area: 'qd_haiyu',
    desc: '群岛最高的崖。崖头立着块碑，碑文被风磨平了，只剩一个"望"字。天晴的日子，海天相接处偶尔会浮起一线山影——看见的人，一辈子都忘不掉。',
    links: ['qd_yucun'], npcs: ['qd_shouya'],
    huatou: ['在崖头望海', '跟守崖人长谈', '在崖边静坐观想'], events: ['ev_qd_wangxian_xianying'], tags: ['wild'],
  },

  // ---------- 海底龙宫遗迹 ----------
  lg_gongmen: { id: 'lg_gongmen', name: '沉没宫门', city: 'longgong', area: 'lg_haidi',
    desc: '两扇宫门倒在海底，门上盘龙的鳞片还泛着微光。水从门缝里流过，带着一种庄严的静——几百年了，守门的石兽还保持着"跪迎"的姿势。',
    links: ['lg_huilang', 'lg_jiaoluo'], npcs: [],
    huatou: ['察看宫门石刻', '在水里屏息静观', '往回廊深处游'], events: ['ev_lg_gongmen_ren'], tags: ['wild', 'undersea'],
  },
  lg_huilang: { id: 'lg_huilang', name: '龙骨回廊', city: 'longgong', area: 'lg_haidi',
    desc: '回廊的柱子是真正的龙骨——粗得三人合抱，骨纹里流转着将熄未熄的灵光。廊壁的夜明珠大半熄了，剩下几颗，在水里幽幽地亮。',
    links: ['lg_gongmen'], npcs: [],
    huatou: ['探查龙骨廊柱', '摸一摸夜明珠', '在回廊尽头搜索'], events: ['ev_lg_huilang_bao'], tags: ['wild', 'undersea'],
  },
  lg_jiaoluo: { id: 'lg_jiaoluo', name: '鲛人遗族聚落', city: 'longgong', area: 'lg_haidi',
    desc: '珊瑚搭成的村落，织网的声音像唱歌。鲛人们不肯多话——他们的祖辈守着这座废宫，守了太多代。外来的客人，要看的是"心"，不是"礼"。',
    links: ['lg_gongmen'], npcs: ['lg_jiaozu'],
    huatou: ['拜会鲛人长老', '帮鲛人修补织网', '听鲛人唱古老的歌'], events: ['ev_lg_jiaoren_ge'], tags: ['town', 'undersea'],
  },

  // ---------- 南海商路 ----------
  nh_bujidao: { id: 'nh_bujidao', name: '补给岛', city: 'nanhai', area: 'nh_hailu',
    desc: '一座孤零零的小岛，却是整条商路的命脉。淡水、瓜果、修船的木料——海图上写着"至此无忧"，岛上码头的酒肆里，写满了航过深海的人的余悸。',
    links: ['nh_haishi'], npcs: ['nh_daoyou'],
    huatou: ['补给淡水', '在酒肆听海客说海', '打听海市的行情'], events: [], tags: ['town'],
  },
  nh_haishi: { id: 'nh_haishi', name: '海市', city: 'nanhai', area: 'nh_hailu',
    desc: '十几条大船首尾相连，甲板连成集市。季风起时开市，风停就散——牙人们说这是"海上唯一讲价的地方"。货真货假，全看你的眼力和运气。',
    links: ['nh_bujidao'], npcs: ['nh_yaren'],
    huatou: ['逛海市', '跟海市牙人砍价', '打听蜃楼的传闻'], events: ['ev_nh_haishi_shen'], tags: ['town'],
  },
};

export const NPCS2 = {
  // 百草坞
  bc_daoyao_ren: { id: 'bc_daoyao_ren', name: '采药人', aliases: ['采药人', '药农'], city: 'baicao',
    desc: '背篓比人大，脚力比骡好。他识得药谷每一条兽道，也识得哪些山头"采药人不进"。',
    zhishi: [
      { keys: ['药', '采', '山'], answer: '采药三戒：戒贪、戒晚、戒声张。山里的东西，你敬它三分，它让你三分。' },
      { keys: ['坞', '去处', '逛'], answer: '药市晌午最旺；药王庙常年有人求医；试毒巷——那地方，你少去。' },
      { keys: ['毒', '试毒巷', '灰'], answer: '毒师们手上有真本事，可那活计拿命换钱。年轻人，别把命看轻了。' },
    ],
    greeting: '（他直起腰，捶了捶背）客人是抓药，还是进山？',
    personality: '话糙理细' },
  bc_yaren: { id: 'bc_yaren', name: '药市牙人', aliases: ['牙人', '药牙'], city: 'baicao',
    desc: '一双眼毒得很——药好药坏，他上手一捻就知道。规矩是"牙人嘴上无谎话"，他偏能句句是真、句句带钩。',
    zhishi: [
      { keys: ['药', '买', '行情'], answer: '今春的茯苓涨了三成——北边打仗，军中收得多。你要出货，趁早。' },
      { keys: ['稀罕', '奇药', '灵药'], answer: '稀罕药？九节兰、空青、龙涎……这些东西药市没有，山里有，海里也有。就看你敢不敢去取。' },
      { keys: ['消息', '打听', '传闻'], answer: '近来南边的客商老问"鲛绡"——海里出的东西。问的人多了，这海底下，怕是要出事。' },
    ],
    greeting: '哟，客官看药？我这儿童叟无欺——贵，是无欺。', personality: '嘴利心明' },
  bc_miaozhu: { id: 'bc_miaozhu', name: '药王庙庙祝', aliases: ['庙祝'], city: 'baicao',
    desc: '白眉白须，一辈子晒药翻药。他给人看病不收钱，只收"还愿的药"——庙前那些干药，是他的账本。',
    zhishi: [
      { keys: ['病', '医', '药'], answer: '（搭脉）……无碍。是劳损。回去拿三钱黄芪两片甘草，泡水。人啊，别把自己当铁打的。' },
      { keys: ['药王', '拜', '愿'], answer: '药王面前许愿，得许"活人的愿"。求财求寿的，庙门朝东——那是出去的路。' },
      { keys: ['试毒', '毒', '巷'], answer: '（叹气）巷里那些孩子……都是苦命人。你要去，记一句话：试药之前，先嚼半片甘草——能保心脉一时。' },
    ],
    greeting: '（他头也不抬）香在案上，愿在心里。', personality: '悲悯通透' },
  bc_tianhu: { id: 'bc_tianhu', name: '药田田户', aliases: ['田户', '药农'], city: 'baicao',
    desc: '守了半辈子药田。田里的草人他亲手扎的——你问他防鸟还是防什么，他往山里努努嘴："防夜里来的。"',
    zhishi: [
      { keys: ['药田', '草人', '夜'], answer: '草人防的不是鸟。前年夜里来过"东西"，把药田踩了一溜印子——那印子，人的脚没有那么长。' },
      { keys: ['人参', '地精', '娃娃'], answer: '（压低声音）药田底下老参成精的事，书上写的不算稀奇。你夜里听见田里有小孩哭，千万别应声。' },
      { keys: ['活', '帮工'], answer: '搭把手？行啊，垅里的草要除。工钱没有，管一顿饭——我老伴熬的药膳，城里买不着。' },
    ],
    greeting: '别踩垅！——（看清是你）哦，客人。看药？', personality: '警觉热心' },
  bc_dushi: { id: 'bc_dushi', name: '老毒师', aliases: ['毒师'], city: 'baicao',
    desc: '十指指甲泛青，笑起来眼睛眯成缝。他试毒试了四十年，如今喝口水都要先闻一闻。规矩人躲他，可药铺掌柜们都敬他——他一眼能看出药里"多了一味"。',
    zhishi: [
      { keys: ['毒', '试', '活'], answer: '试毒的活，一次五十文，试完躺三天。想学？先拿自己练——三年不死，我再教你认草。' },
      { keys: ['草', '认', '教'], answer: '百草谷里三百六十种草，能入药的不到一百。剩下那些——你认全了，天下就没有你能被人暗算的地方。' },
      { keys: ['债', '恩', '欠'], answer: '我这条命是药王庙老庙祝捡回来的。他收愿，我还债——债没还完，死不了。' },
    ],
    greeting: '（他抬了抬眼皮）生面孔。巷口坐坐可以，往里——得有个由头。', personality: '亦正亦邪' },
  bc_zhanggui: { id: 'bc_zhanggui', name: '客栈掌柜', aliases: ['掌柜'], city: 'baicao',
    desc: '算盘打得好，药理也通。住店的药商都服他——他报的行情比牙人准，他劝的架比和事佬灵。',
    zhishi: [
      { keys: ['住', '歇', '房'], answer: '上房二十文一晚，通铺五文。住三天以上，送一壶祛湿的药茶——山里的雾，进了骨头就麻烦了。' },
      { keys: ['行情', '消息', '打听'], answer: '（压低声音）最近药市上"龙涎"的价翻着番地涨——海里出的东西，可南边的船都说是从"海市"淘的。你去问番商，他们懂行。' },
      { keys: ['昆吾', '剑', '铁'], answer: '铸剑的昆吾镇？往北两日山路。药商们常带药材去换铁器——那儿的老师傅，认药材不认钱。' },
    ],
    greeting: '客官打尖还是住店？（他眼里带着笑）这年头能笑出来的，都是好日子。', personality: '圆融热络' },
  // 沧澜澳
  cl_laoban: { id: 'cl_laoban', name: '码头老班头', aliases: ['班头', '老班头'], city: 'canglan',
    desc: '扛了四十年货，一条胳膊被缆绳绞断过又接上。码头上的事没有他不知道的——包括哪条船"不该上"。',
    zhishi: [
      { keys: ['出海', '船', '航'], answer: '出海？先看船，再看人，最后看天。船坞的船底要敲——空的不能上；船老大要看他爷爷的坟——坟头草齐的，是老海狗，稳。' },
      { keys: ['群岛', '海路', '去'], answer: '去东海群岛，走季风要两日。春冬浪大，夏秋稳。班头我劝你——上船前把身后事交代清楚，不是咒你，是规矩。' },
      { keys: ['海难', '黑风', '传闻'], answer: '黑风……（他摸了摸断过的胳膊）三年前那一夜，七条船回来两条。回来的两个人如今疯了疯、哑了哑——他们看见了什么，没人敢问。' },
    ],
    greeting: '让让让让——（货卸完他才回头）找班头我？说事。', personality: '粗中有细' },
  cl_yufan: { id: 'cl_yufan', name: '鱼贩', aliases: ['鱼贩子'], city: 'canglan',
    desc: '嗓子是鱼市最亮的。他卖鱼看天色——天好卖活鱼，天要变，他收摊比谁都快。"鱼贩子收摊"在澳港是句谚语，意思是"要变天"。',
    zhishi: [
      { keys: ['鱼', '买', '鲜'], answer: '今日的黄鱼刚上滩！（他捞出一条拍拍水）要不说渔汛看天——明儿要变天，这鱼再不卖就臭在手里喽。' },
      { keys: ['海', '怪', '传闻'], answer: '上个月有渔民网上来一块"龙鳞"——巴掌大，青黑色，沉得压手。番商出一百两收，他没卖。后来……他家就再没出过海。' },
      { keys: ['变天', '收摊', '天色'], answer: '（他抬头看了看）今儿的云脚发毛。客人，你若要出海，等两天——这一等，兴许就是一条命。' },
    ],
    greeting: '鲜鱼嘞——（见你看他）客人称鱼？还是听风？', personality: '爽利识天' },
  cl_miaozhu: { id: 'cl_miaozhu', name: '海神庙庙祝', aliases: ['庙祝'], city: 'canglan',
    desc: '年轻时是船老大，一场海难后独他生还，从此守庙。他解签从不直说吉凶，只说"海想让你知道的事"。',
    zhishi: [
      { keys: ['签', '解', '吉凶'], answer: '（他摇签、看签，又看你）……海说你心里存着一口气，没咽下去。出海之前，先把这口气咽了——不然海上，它会替你翻出来。' },
      { keys: ['海神', '拜', '祭'], answer: '海神不收香火钱，收"真话"。你心里怎么想海，海就知道。拜它，先别骗它。' },
      { keys: ['龙宫', '海底', '古迹'], answer: '（他盯着你看了很久）……老辈人说，海底有座宫。进去的人要么满载而归，要么成了一尾"鱼"。你要真想去——去问鲛人。他们的眼泪能换一次深潜。' },
    ],
    greeting: '（他扫着香灰）施主是出海前求平安，还是海里回来还愿？', personality: '渡尽劫波' },
  cl_chuanshi: { id: 'cl_chuanshi', name: '老船师', aliases: ['船师', '造船师傅'], city: 'canglan',
    desc: '三代造船。他闭着眼摸船板，能报出木料产自哪座山。他常说的话："船欺不了海，人别想欺船。"',
    zhishi: [
      { keys: ['船', '修', '造'], answer: '修船看三处：龙骨、水密舱、桅根。这三处好的船，敢走远海。你要买船，我给你掌眼——不收钱，收"别糟蹋好船"的承诺。' },
      { keys: ['水性', '学', '教'], answer: '水性不在手脚，在气。憋气先学"咽"——气咽进丹田，人在水里能撑一炷香。剩下的，靠海教你。' },
      { keys: ['龙骨', '海图', '旋水'], answer: '（他手一顿）……旋水。你知道旋水？（他压低声音）三十年前有条官船沉在那儿，海图从此改了道。你若要去——先学会闭气，再找鲛人引路。' },
    ],
    greeting: '（他敲着船板）听声。木头不骗人——客人，你也一样？', personality: '匠人风骨' },
  cl_fanshang: { id: 'cl_fanshang', name: '番商', aliases: ['番商', '胡商'], city: 'canglan',
    desc: '从南海来，皮肤晒得像老船板。官话生硬，算账飞快。他收"海里捞的东西"——龙鳞、夜光贝、说不上来的骨头，给价公道，从不问来路。',
    zhishi: [
      { keys: ['卖', '收', '货'], answer: '海里捞的？拿来我看。（他上手一掂）……真东西。这样的货，澳洲我给公道价——但你记住，此物认主，卖出去了，未必是福。' },
      { keys: ['海市', '南海', '航路'], answer: '海市？季风起来的时候，跟着燕子的方向走。海市开在风里——风停了，它就沉了。货价，一成真九成话，你眼睛要毒。' },
      { keys: ['家乡', '番邦', '来历'], answer: '（他笑了笑）我的家乡，坐船三个月。那里的人说，海的那边还有海，天的上面还有天。你们这里的书上也这么写——"山外有山"。是一个道理。' },
    ],
    greeting: '（他摊开手）看货，还是听故事？两样都行——故事不要钱。', personality: '豪爽识货' },
  cl_shoudeng: { id: 'cl_shoudeng', name: '守灯人', aliases: ['守灯人'], city: 'canglan',
    desc: '一年下一回崖，话比灯油还省。他守灯二十三年，救回的船没有一百也有八十——他自己数得清，可从不提。',
    zhishi: [
      { keys: ['灯', '守', '崖'], answer: '灯亮着，船就知道岸在哪。（他望着海）我爹守了三十年，我守了二十三年。灯不能灭——灭了，海上的“人”会顺着黑摸上岸。' },
      { keys: ['海', '雾', '怪'], answer: '雾天别靠近崖边。雾里有“影子”会学人喊名字——你听见有人喊你，应一声没事，多应就有事。' },
      { keys: ['仙山', '现影', '蓬莱'], answer: '（他罕见地笑了）你倒是问对人了。天最晴的清晨，天海相接处偶尔浮出一线青山——那就是老人们说的“仙山现影”。看见它的人……（他看着你）会有事发生。好事，还是坏事，看你的道行。' },
    ],
    greeting: '（他点点头，算是招呼。海风把他灰白的头发吹得竖起来。）', personality: '寡言有故' },
  // 昆吾镇
  kw_kuanggong: { id: 'kw_kuanggong', name: '老矿工', aliases: ['矿工'], city: 'kunwu',
    desc: '脸和手全是矿粉染的黑，笑起来牙齿雪白。他敲石头听声辨矿，四十年的手艺——"石头会说话，就看你耳朵灵不灵"。',
    zhishi: [
      { keys: ['矿', '石', '铁'], answer: '昆吾山的矿分三层：面上是凡铁，里头是寒铁——最深处有"星髓"，那是天上掉下来的东西。但最深那层，矿工们不下去。' },
      { keys: ['星髓', '深处', '禁'], answer: '（他压低声音）最深那层早年挖出过"不该挖的东西"，一口井封了。井口镇着一块碑，碑上的字没人认得——可摸过碑的人都说，碑是温的。' },
      { keys: ['妖兽', '山', '传闻'], answer: '山里近来不太平。矿道七号支洞前日塌了，掘出来的洞壁上全是爪印——三指，深三寸。矿上都封了口，可纸包不住火。' },
    ],
    greeting: '（他直起腰，眯眼看你）生人？镇里就一条街，你走两步就熟了。', personality: '厚道有畏' },
  kw_laojiang: { id: 'kw_laojiang', name: '老师傅', aliases: ['铁匠', '老铁匠', '铸剑师傅'], city: 'kunwu',
    desc: '剑炉街最老的炉主。他铸的剑没有一把超过十两银——因为"值钱的不卖，卖的不值钱"。昆吾镇的剑客提起他，都得叫声"师叔祖"。',
    zhishi: [
      { keys: ['铸剑', '炼器', '锻'], answer: '铸剑三关：料、火、心。料要真，火要沉，心要静——三关都过，剑才有"性子"。你要带材料来，我给你掌眼：材料真假，我一锤听音就知道。' },
      { keys: ['材料', '妖兽', '龙鳞'], answer: '（他眼睛亮了）妖兽的材料？（他放下锤子）活取的龙鳞、堕地的星核、深山的寒髓……这些是好东西。但丑话说前头——杀兽取材的料，我这炉子不认。' },
      { keys: ['掌眼', '兵器', '剑'], answer: '（他掂了掂你的兵器）……普通货色，胜在皮实。想换好的？攒材料。好剑不认钱，认料——料到了，火候我给你留三个月。' },
    ],
    greeting: '（锤声停了）客人看剑，还是带料？看剑这边走，带料——先让我听声。', personality: '匠气凛然' },
  kw_kuangshang: { id: 'kw_kuangshang', name: '矿商', aliases: ['矿商'], city: 'kunwu',
    desc: '包了山里三条矿道，算盘比矿锤还响。他什么都敢收——妖兽骨、海底铁、天上陨星，只要你能拿出来，他就敢开价。',
    zhishi: [
      { keys: ['收', '卖', '价'], answer: '矿石按斤，妖骨按根，星髓按钱——（他掰着指头）你要有货，咱们按"货"谈，不按"话"谈。' },
      { keys: ['世家', '规矩', '铸剑世家'], answer: '铸剑世家不接外活，除非……（他意味深长地笑）除非那料，够格。什么叫够格？龙鳞星核，凤毛麟角——你懂的。' },
      { keys: ['剑冢', '守冢', '山'], answer: '剑冢下院那位守冢人，是个有故事的人。他扫了一辈子剑坟——坟里每把剑的事他都记得。你要听故事，带壶酒。' },
    ],
    greeting: '（他头也不抬地拨着算盘）买矿？卖货？说话。', personality: '精明世故' },
  kw_shijia_zhu: { id: 'kw_shijia_zhu', name: '世家主', aliases: ['世家主', '铸剑世家主'], city: 'kunwu',
    desc: '昆吾铸剑世家当代家主，五十来岁，手背全是炉火的疤。他一年只亲手铸三把剑——铸谁的剑，看"缘"，不看钱。',
    zhishi: [
      { keys: ['铸剑', '拜', '求'], answer: '（他看着你的手）……手上有茧，是握过兵器的。我这工坊不收徒，但收"缘"——你若有好料，或者有故事，坐下说。' },
      { keys: ['规矩', '家风', '传承'], answer: '世家立世五百年，就一条规矩：炉火不熄。战乱、灾荒、王朝更替——火不能熄。熄一年，愧对列祖；熄十年，愧对"铸剑"二字。' },
      { keys: ['剑冢', '先祖', '坟'], answer: '剑冢里埋的剑，一半是我先祖的——他们铸完平生最后一剑，剑随人去，人随剑葬。你若去拜，替我看一眼第七排那座无字碑——碑下埋的，是一把没铸完的剑。' },
    ],
    greeting: '（他放下锤子，先看你的手，再看你的眼。）说吧——什么事。', personality: '沉静如炉' },
  kw_shouzhong: { id: 'kw_shouzhong', name: '守冢人', aliases: ['守冢人'], city: 'kunwu',
    desc: '扫了剑冢三十年。他知道每座坟里剑的名字、剑主的名字、剑主最后一战的地方——可他只讲给"带酒来"的人听。',
    zhishi: [
      { keys: ['剑', '坟', '冢'], answer: '（他扫着落叶）这第七排的无名碑……那把剑的主人，是个瞎子。剑没铸完，人就走了。剑坯在碑下埋了两百年——剑坯没成剑，剑魂一直没散。' },
      { keys: ['北原', '通', '雪山'], answer: '剑冢下院有条旧道通北原，早年剑修们走的那条。如今封了——不是封路，是"山那边的东西"下来过一回，先祖们把路"堵"上了。' },
      { keys: ['酒', '故事', '讲'], answer: '（他接过酒壶闻了闻）……好酒。（他往坟群深处努努嘴）坐。今晚讲"断水"——那把剑的主人，一剑断过一条河。' },
    ],
    greeting: '（扫帚停了）带酒了吗？——没带的话，看坟也行，轻声些。', personality: '守静怀故' },
  // 群岛/南海/龙宫
  cl_yumin: { id: 'cl_yumin', name: '老渔民', aliases: ['渔民', '渔家'], city: 'qundao',
    desc: '看潮信五十年的眼睛。他不用罗盘，看云脚、闻水味就知道明天是什么天——"海写在脸上，就看你识不识字"。',
    zhishi: [
      { keys: ['潮', '信', '出海'], answer: '初一十五大潮，初八廿三小潮。要看潮信去望仙崖——崖头看下去，潮头一线白，那就是"海的呼吸"。' },
      { keys: ['仙山', '望仙崖', '传说'], answer: '（他朝天边看）我爷爷的爷爷见过仙山现影——回来以后他就疯了，天天往崖头跑。老人们说，看见了"不该看见的"……可我倒觉得，他是看见了"想看见的"。' },
      { keys: ['龙宫', '海底', '深'], answer: '海底的宫？（他压低声音）渔村祖上传下规矩：网到"宫砖"要扔回海里——那是龙宫的东西，拿了，全村遭殃。可去年……有人拿了，没扔。' },
    ],
    greeting: '（他补着网，头也不抬）看潮，还是问路？', personality: '宿命通透' },
  qd_daozhu: { id: 'qd_daozhu', name: '岛主', aliases: ['岛主'], city: 'qundao',
    desc: '海盟的轮值岛主，船老大出身，一条胳膊上的刺青是他打赢过的船。他议事全靠嗓门，可拨算盘的手比谁都稳——"海上没有白打的架，也没有白吃的亏"。',
    zhishi: [
      { keys: ['海盟', '议事', '活'], answer: '海盟的活计三样：护航、传信、打捞。打捞最挣钱——沉船多，宝贝多，死人更多。你要接，先签"生死状"。' },
      { keys: ['龙宫', '海底', '打捞'], answer: '（他声音沉了）龙宫的事，海盟禁谈。二十年前三艘打捞船下去，回来一艘——船上八个人，七个疯了。剩下那个，就是如今望仙崖的守崖人。' },
      { keys: ['南海', '商路', '航'], answer: '去南海走季风航路，四日。带上淡水，带上运气——海市开市的日子，跟燕群走。海市里有真货，也有"假人"。买货别过夜，过夜就不是你的了。' },
    ],
    greeting: '（他嗓门极大）说事！——海上的事，长话短说。', personality: '豪横爽直' },
  qd_shouya: { id: 'qd_shouya', name: '守崖人', aliases: ['守崖人'], city: 'qundao',
    desc: '二十年前龙宫打捞唯一没疯的人。他如今守着望仙崖，守着那块磨平的碑——他说是"等"，等什么，他不说。',
    zhishi: [
      { keys: ['碑', '望', '仙山'], answer: '（他望着海平线）碑上的字是我磨的。原先刻的是"长生"。我下去过一回，看见的东西让我明白——长生不长生，不看你活多久，看你记得多少。' },
      { keys: ['龙宫', '海底', '下'], answer: '（他久久不语）……你要下去？（他转身从崖屋里拿出一只小瓶）鲛人泪。她们长老欠我一个人情——这瓶泪，是我存的。你带下去，见了鲛人，说"守崖人还愿"。' },
      { keys: ['疯', '劫', '余'], answer: '（他笑了，笑得很淡）疯的不是看见了什么，是看见了"回不来"的东西还想着回来。我回来，是因为我下潜前，把"回"这件事想清楚了。你去——你也想清楚。' },
    ],
    greeting: '（他没回头，风声很大）……来望仙山的？还是来望自己的？', personality: '历劫归静' },
  lg_jiaozu: { id: 'lg_jiaozu', name: '鲛人长老', aliases: ['鲛人长老', '长老'], city: 'longgong',
    desc: '鲛人遗族的长老，眼瞳是深海的蓝。她的歌声能让珊瑚开谢——族人说，她记着龙宫沉没那夜所有的歌。她对外客只说一句古语，翻译过来是："陆上来的人，先学会「归还」，再学会「拿取」。"',
    zhishi: [
      { keys: ['鲛人泪', '深潜', '还愿'], answer: '（她接过小瓶，眼瞳里的光变了）……守崖人还愿来了。（她看你良久）他欠的不是我，是这片海。你替他把愿带到了——你要什么，说。' },
      { keys: ['龙宫', '遗迹', '宝'], answer: '宫里的东西都有主。你想"拿"，先想清楚拿来做"什么"。龙骨认心，夜明珠认眼——心不正的，摸到的都是石头。' },
      { keys: ['金丹', '契机', '修'], answer: '（她久久看着你）……你身上有"海"的气。海底灵眼在回廊深处——历代修士的"关"在这儿破，因为海的静，压得住破境时心里的"躁"。你去坐一夜，成不成的，看你自己。' },
    ],
    greeting: '（她的歌声停了，眼瞳望着你，像两片深海。）……陆上来客。', personality: '幽静深邃' },
  nh_daoyou: { id: 'nh_daoyou', name: '岛友', aliases: ['岛友', '补给岛主事'], city: 'nanhai',
    desc: '补给岛的主事，自称"岛友"——"四海之内皆兄弟，到了我这岛，都是友"。他给每个过路船记一笔账："账都记着，海替我讨。"',
    zhishi: [
      { keys: ['补给', '水', '歇'], answer: '淡水管够，果子管够——（他笑）账记着。别紧张，这账不是钱，是"回头客"。海上跑的人，最讲回头。' },
      { keys: ['海客', '传闻', '深海'], answer: '（他斟了杯酒）深海再往南，海图上写"勿念"。可每年都有人念——去年走了三条船，回来一条。回来的人变了个人，钱多得吓人，可他夜里从来不睡黑屋。' },
      { keys: ['海市', '行情', '货'], answer: '海市的风向日一开。真货三成——龙涎、星砂、鲛绡。牙人们嘴里的"仙家遗物"别碰，十件里九件是蜃景变的，太阳一出来就化水。' },
    ],
    greeting: '（他大笑着迎上来）友！到我这岛，都是友！喝一口再说话！', personality: '豪爽如风' },
  nh_yaren: { id: 'nh_yaren', name: '海市牙人', aliases: ['牙人', '海牙'], city: 'nanhai',
    desc: '海市最好的牙人，一双眼能在蜃景里认出真货。他的规矩："风停前成交"——过了时辰的东西，他绝不沾手。',
    zhishi: [
      { keys: ['货', '买', '价'], answer: '（他眯眼打量你）真货三成，假货七成，你眼力够，就淘得着。今日到的货里有块"海底铁"——你要识货，风停前来。' },
      { keys: ['蜃景', '假', '辨'], answer: '蜃景变的假货有个破绽——（他压低声音）真东西压手，蜃景轻。还有，海市里"太便宜的好货"和"太贵口的坏货"都别碰——行情之外，必有鬼。' },
      { keys: ['沉船', '打捞', '航路'], answer: '南边的沉船多，宝贝也多。（他忽然正经）但丑话说前头：有些沉船"捞不得"——船上挂着的东西你不认识，就别动。去年有船捞了面"铜镜"，如今那条船的人，一个都不在了。' },
    ],
    greeting: '（他摇着扇子）客官看货？——风快停了，长话短说。', personality: '滑头有度' },
};
